import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { Dialog } from '../../../design-system/primitives';
import { PdfViewer } from './pdf-viewer';

const embedPdfMocks = vi.hoisted(() => ({
  saveAsCopy: vi.fn(() => ({
    toPromise: vi.fn(async () => Uint8Array.from([37, 80, 68, 70]).buffer),
  })),
}));

vi.mock('@embedpdf/react-pdf-viewer', async () => {
  const React = await import('react');
  const registry = {
    pluginsReady: vi.fn(async () => undefined),
    getPlugin: vi.fn(() => ({
      provides: () => ({ saveAsCopy: embedPdfMocks.saveAsCopy }),
    })),
  };
  return {
    PDFViewer: ({
      config,
      onReady,
    }: {
      config: Record<string, unknown>;
      onReady?: (value: typeof registry) => void;
    }) => {
      const hostRef = React.useRef<HTMLDivElement>(null);
      React.useLayoutEffect(() => {
        const host = document.createElement('embedpdf-container');
        const root = host.attachShadow({ mode: 'open' });
        const overflowItem = document.createElement('div');
        overflowItem.dataset.epdfI = 'overflow-tabs-button';
        overflowItem.append(document.createElement('button'));
        const zoom = document.createElement('input');
        zoom.name = 'zoom';
        zoom.type = 'text';
        zoom.setAttribute('aria-label', 'Set zoom');
        const searchItem = document.createElement('div');
        searchItem.dataset.epdfI = 'search-button';
        const searchButton = document.createElement('button');
        searchButton.setAttribute('aria-label', '搜索');
        searchButton.addEventListener('click', () => {
          const current = root.querySelector('input[data-pdf-search]');
          if (current) {
            current.remove();
            return;
          }
          const input = document.createElement('input');
          input.type = 'text';
          input.dataset.pdfSearch = '';
          root.append(input);
        });
        searchItem.append(searchButton);
        root.append(overflowItem, zoom, searchItem);
        hostRef.current?.append(host);
        return () => host.remove();
      }, []);
      React.useEffect(() => onReady?.(registry), [onReady]);
      return (
        <>
          <output data-testid='embedpdf-viewer'>{JSON.stringify(config)}</output>
          <div data-testid='embedpdf-shadow-host' ref={hostRef} />
        </>
      );
    },
  };
});

if (!URL.createObjectURL) Object.defineProperty(URL, 'createObjectURL', { configurable: true, value: vi.fn() });
if (!URL.revokeObjectURL) Object.defineProperty(URL, 'revokeObjectURL', { configurable: true, value: vi.fn() });

describe('Work EmbedPDF editor', () => {
  beforeEach(() => {
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:a3s-pdf');
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
    embedPdfMocks.saveAsCopy.mockClear();
  });

  afterEach(() => {
    cleanup();
    vi.restoreAllMocks();
  });

  it('loads the full EmbedPDF editor with the local PDFium runtime and Chinese UI', async () => {
    render(
      <PdfViewer
        fileName='方案.pdf'
        loadSource={async () => new Blob(['pdf'], { type: 'application/pdf' })}
        onSave={vi.fn(async () => true)}
      />
    );

    const viewer = await screen.findByTestId('embedpdf-viewer');
    const config = JSON.parse(viewer.textContent ?? '{}') as {
      export?: { defaultFileName?: string };
      i18n?: { defaultLocale?: string };
      src?: string;
      wasmUrl?: string;
      worker?: boolean;
    };
    expect(config.src).toBe('blob:a3s-pdf');
    expect(config.wasmUrl).toMatch(/^https?:\/\//);
    expect(new URL(config.wasmUrl ?? '').pathname).toBe('/workspace/vendor/embedpdf/pdfium.wasm');
    expect(config.worker).not.toBe(false);
    expect(config.i18n?.defaultLocale).toBe('zh-CN');
    expect(config.export?.defaultFileName).toBe('方案.pdf');
    expect(screen.queryByText(/EmbedPDF|PDFium|批注、表单/)).not.toBeInTheDocument();
  });

  it('saves a real PDF copy generated by the EmbedPDF export plugin', async () => {
    const onSave = vi.fn(async (_pdf: Blob) => true);
    render(
      <PdfViewer
        loadSource={async () => new Blob(['pdf'], { type: 'application/pdf' })}
        saveLabel='保存并写回本地'
        onSave={onSave}
      />
    );

    await screen.findByTestId('embedpdf-viewer');
    const saveButton = await screen.findByRole('button', { name: '保存并写回本地' });
    await waitFor(() => expect(saveButton).toBeEnabled());
    fireEvent.click(saveButton);

    await waitFor(() => expect(onSave).toHaveBeenCalledOnce());
    const savedPdf = onSave.mock.calls[0]?.[0];
    expect(savedPdf).toBeInstanceOf(Blob);
    expect(savedPdf?.type).toBe('application/pdf');
    expect(Array.from(new Uint8Array(await savedPdf!.arrayBuffer()))).toEqual([37, 80, 68, 70]);
    expect(screen.getByLabelText('PDF 保存状态')).toHaveTextContent('已保存');
    expect(screen.getByText('已保存')).toHaveClass('ds-status-badge', 'success');
  });

  it('handles only the plain Cmd/Ctrl+S save shortcut', async () => {
    const onSave = vi.fn(async (_pdf: Blob) => true);
    render(<PdfViewer loadSource={async () => new Blob(['pdf'], { type: 'application/pdf' })} onSave={onSave} />);
    await screen.findByTestId('embedpdf-viewer');
    await waitFor(() => expect(screen.getByRole('button', { name: '保存' })).toBeEnabled());

    fireEvent.keyDown(window, { key: 's', ctrlKey: true, shiftKey: true });
    fireEvent.keyDown(window, { key: 's', ctrlKey: true, altKey: true });
    fireEvent.keyDown(window, { key: 's', ctrlKey: true, repeat: true });
    expect(onSave).not.toHaveBeenCalled();

    fireEvent.keyDown(window, { key: 's', ctrlKey: true });
    await waitFor(() => expect(onSave).toHaveBeenCalledOnce());
  });

  it('does not save the PDF behind an open Office dialog', async () => {
    const onSave = vi.fn(async (_pdf: Blob) => true);
    render(
      <>
        <PdfViewer loadSource={async () => new Blob(['pdf'], { type: 'application/pdf' })} onSave={onSave} />
        <Dialog title='版本记录' onClose={vi.fn()}>
          <input aria-label='版本备注' />
        </Dialog>
      </>
    );
    await screen.findByTestId('embedpdf-viewer');
    await waitFor(() => expect(screen.getByRole('button', { name: '保存' })).toBeEnabled());

    await act(async () => {
      expect(fireEvent.keyDown(screen.getByRole('textbox', { name: '版本备注' }), { key: 's', ctrlKey: true })).toBe(
        false
      );
      await Promise.resolve();
    });

    expect(onSave).not.toHaveBeenCalled();
  });

  it('labels compact viewer controls and opens focused PDF search with Cmd/Ctrl+F', async () => {
    const { container } = render(
      <PdfViewer
        loadSource={async () => new Blob(['pdf'], { type: 'application/pdf' })}
        onSave={vi.fn(async () => true)}
      />
    );
    await screen.findByTestId('embedpdf-viewer');
    await waitFor(() => expect(screen.getByRole('button', { name: '保存' })).toBeEnabled());
    const root = container.querySelector('embedpdf-container')?.shadowRoot;
    expect(root).not.toBeNull();

    const overflowButton = root?.querySelector<HTMLButtonElement>('[data-epdf-i="overflow-tabs-button"] button');
    const zoomInput = root?.querySelector<HTMLInputElement>('input[name="zoom"]');
    await waitFor(() => expect(overflowButton).toHaveAccessibleName('更多工具'));
    expect(zoomInput).toHaveAccessibleName('缩放比例');

    expect(fireEvent.keyDown(window, { key: 'f', ctrlKey: true, shiftKey: true })).toBe(true);
    expect(root?.querySelector('input[data-pdf-search]')).not.toBeInTheDocument();
    const searchButton = root?.querySelector<HTMLButtonElement>('[data-epdf-i="search-button"] button');
    fireEvent.click(searchButton!);
    const clickSearchInput = await waitFor(() => {
      const input = root?.querySelector<HTMLInputElement>('input[data-pdf-search]');
      expect(input).toBeInTheDocument();
      return input!;
    });
    await waitFor(() => expect(root?.activeElement).toBe(clickSearchInput));
    expect(fireEvent.keyDown(clickSearchInput, { key: 'Escape' })).toBe(false);
    await waitFor(() => expect(root?.querySelector('input[data-pdf-search]')).not.toBeInTheDocument());
    await waitFor(() => expect(root?.activeElement).toBe(searchButton));

    expect(fireEvent.keyDown(window, { key: 'f', ctrlKey: true })).toBe(false);
    const searchInput = await waitFor(() => {
      const input = root?.querySelector<HTMLInputElement>('input[data-pdf-search]');
      expect(input).toBeInTheDocument();
      return input!;
    });
    await waitFor(() => expect(root?.activeElement).toBe(searchInput));
    expect(searchInput).toHaveAccessibleName('在 PDF 中搜索');
  });

  it('uses a read-only native viewer when no persistence callback is provided', async () => {
    render(<PdfViewer loadSource={async () => new Blob(['pdf'], { type: 'application/pdf' })} />);

    const viewer = await screen.findByTestId('embedpdf-viewer');
    expect(viewer).toHaveTextContent('annotation');
    expect(viewer).toHaveTextContent('redaction');
    expect(screen.queryByRole('button', { name: '保存' })).not.toBeInTheDocument();
  });
});
