import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { PdfViewer } from './pdf-viewer';

const embedPdfMocks = vi.hoisted(() => ({
  saveAsCopy: vi.fn(() => ({
    toPromise: vi.fn(async () => Uint8Array.from([37, 80, 68, 70]).buffer),
  })),
}));

vi.mock('@embedpdf/react-pdf-viewer', async () => {
  const React = await import('react');
  const registry = {
    pluginsReady: vi.fn(async () => undefined),
    getPlugin: vi.fn(() => ({
      provides: () => ({ saveAsCopy: embedPdfMocks.saveAsCopy }),
    })),
  };
  return {
    PDFViewer: ({
      config,
      onReady,
    }: {
      config: Record<string, unknown>;
      onReady?: (value: typeof registry) => void;
    }) => {
      React.useEffect(() => onReady?.(registry), [onReady]);
      return <output data-testid='embedpdf-viewer'>{JSON.stringify(config)}</output>;
    },
  };
});

if (!URL.createObjectURL) Object.defineProperty(URL, 'createObjectURL', { configurable: true, value: vi.fn() });
if (!URL.revokeObjectURL) Object.defineProperty(URL, 'revokeObjectURL', { configurable: true, value: vi.fn() });

describe('Work EmbedPDF editor', () => {
  beforeEach(() => {
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:a3s-pdf');
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
    embedPdfMocks.saveAsCopy.mockClear();
  });

  afterEach(() => {
    cleanup();
    vi.restoreAllMocks();
  });

  it('loads the full EmbedPDF editor with the local PDFium runtime and Chinese UI', async () => {
    render(
      <PdfViewer
        fileName='方案.pdf'
        loadSource={async () => new Blob(['pdf'], { type: 'application/pdf' })}
        onSave={vi.fn(async () => true)}
      />
    );

    const viewer = await screen.findByTestId('embedpdf-viewer');
    const config = JSON.parse(viewer.textContent ?? '{}') as {
      export?: { defaultFileName?: string };
      i18n?: { defaultLocale?: string };
      src?: string;
      wasmUrl?: string;
      worker?: boolean;
    };
    expect(config.src).toBe('blob:a3s-pdf');
    expect(config.wasmUrl).toMatch(/^https?:\/\//);
    expect(new URL(config.wasmUrl ?? '').pathname).toBe('/workspace/vendor/embedpdf/pdfium.wasm');
    expect(config.worker).not.toBe(false);
    expect(config.i18n?.defaultLocale).toBe('zh-CN');
    expect(config.export?.defaultFileName).toBe('方案.pdf');
    expect(screen.queryByText(/EmbedPDF|PDFium|批注、表单/)).not.toBeInTheDocument();
  });

  it('saves a real PDF copy generated by the EmbedPDF export plugin', async () => {
    const onSave = vi.fn(async (_pdf: Blob) => true);
    render(
      <PdfViewer
        loadSource={async () => new Blob(['pdf'], { type: 'application/pdf' })}
        saveLabel='保存并写回本地'
        onSave={onSave}
      />
    );

    await screen.findByTestId('embedpdf-viewer');
    const saveButton = await screen.findByRole('button', { name: '保存并写回本地' });
    await waitFor(() => expect(saveButton).toBeEnabled());
    fireEvent.click(saveButton);

    await waitFor(() => expect(onSave).toHaveBeenCalledOnce());
    const savedPdf = onSave.mock.calls[0]?.[0];
    expect(savedPdf).toBeInstanceOf(Blob);
    expect(savedPdf?.type).toBe('application/pdf');
    expect(Array.from(new Uint8Array(await savedPdf!.arrayBuffer()))).toEqual([37, 80, 68, 70]);
    expect(screen.getByLabelText('PDF 保存状态')).toHaveTextContent('已保存');
  });

  it('uses a read-only native viewer when no persistence callback is provided', async () => {
    render(<PdfViewer loadSource={async () => new Blob(['pdf'], { type: 'application/pdf' })} />);

    const viewer = await screen.findByTestId('embedpdf-viewer');
    expect(viewer).toHaveTextContent('annotation');
    expect(viewer).toHaveTextContent('redaction');
    expect(screen.queryByRole('button', { name: '保存' })).not.toBeInTheDocument();
  });
});
