import type { ComponentType } from 'react';
import type { IconProps } from '@phosphor-icons/react';
import {
  ArrowsClockwise,
  Brain,
  BracketsCurly,
  Broadcast,
  CalendarDots,
  ChatCenteredText,
  ChatsCircle,
  Code,
  FileText,
  Funnel,
  GitBranch,
  Globe,
  Infinity,
  PlugsConnected,
  Robot,
  SignIn,
  SignOut,
  Stack,
  TextT,
  UserFocus,
  Wrench,
} from '@phosphor-icons/react';
import type { WorkflowNodeProfile } from './workflow-model';

export const workflowIconByProfile: Record<WorkflowNodeProfile, ComponentType<IconProps>> = {
  agent: Robot,
  answer: ChatCenteredText,
  code: Code,
  'document-extractor': FileText,
  'http-request': Globe,
  'human-input': UserFocus,
  'if-else': GitBranch,
  'integration-trigger': PlugsConnected,
  iteration: ArrowsClockwise,
  'knowledge-retrieval': BracketsCurly,
  'list-operator': Funnel,
  llm: Brain,
  loop: Infinity,
  output: SignOut,
  'parameter-extractor': BracketsCurly,
  'question-classifier': ChatsCircle,
  'schedule-trigger': CalendarDots,
  template: TextT,
  tool: Wrench,
  'user-input': SignIn,
  'variable-aggregator': Stack,
  'variable-assigner': BracketsCurly,
  'webhook-trigger': Broadcast,
};
