import type { MemoryOverview } from '../../types/api';

export function memoryTestData(): MemoryOverview {
  return {
    root: '/Users/test/.a3s/memory',
    entries: [
      {
        id: 'semantic-1',
        content: 'Prefer Rust for systems services and keep APIs explicit.',
        preview: 'Prefer Rust for systems services and keep APIs explicit.',
        tags: ['rust', 'preference', 'llm'],
        importance: 0.9,
        timestamp: '2026-07-20T08:00:00Z',
        memoryType: 'semantic',
        metadata: {
          source: 'preference',
          provider: 'Codex',
          confidence: '0.96',
          scope: 'user',
          reason: 'A stable language and API-style preference changes future implementation choices.',
          workspace: '/Users/test/project',
          schema: 'a3s.memory.durable.v1',
        },
        accessCount: 4,
        lastAccessed: '2026-07-20T09:00:00Z',
      },
      {
        id: 'procedure-1',
        content: 'Run focused cargo tests after changing the memory store.',
        preview: 'Run focused cargo tests after changing the memory store.',
        tags: ['memory', 'tests', 'consolidated'],
        importance: 0.78,
        timestamp: '2026-06-18T08:00:00Z',
        memoryType: 'procedural',
        metadata: {
          source: 'workflow',
          confidence: '0.91',
          scope: 'workspace',
          reason: 'This repeatable verification catches future persistence regressions.',
          workspace: '/Users/test/project',
          supersedes: 'procedure-old',
          conflicts_with: 'legacy-flow',
        },
        accessCount: 2,
        lastAccessed: '2026-07-01T08:00:00Z',
      },
      {
        id: 'episodic-old',
        content: 'An old low-value experiment used a temporary shell script.',
        preview: 'An old low-value experiment used a temporary shell script.',
        tags: ['experiment'],
        importance: 0.2,
        timestamp: '2025-01-02T08:00:00Z',
        memoryType: 'episodic',
        metadata: { source: 'ctx', provider: 'Claude Code' },
        accessCount: 0,
        lastAccessed: null,
      },
    ],
    stats: {
      entries: 3,
      types: { semantic: 1, procedural: 1, episodic: 1 },
      tags: 7,
      important: 2,
      ctxSources: 1,
    },
    graph: {
      stats: {
        events: 3,
        entities: 7,
        relations: 7,
        aliases: 1,
        short: 1,
        mid: 0,
        long: 2,
        forgetCandidates: 1,
        llmExtracted: 2,
        consolidated: 1,
        conflicts: 1,
      },
      events: [
        {
          id: 'event:semantic-1',
          memoryId: 'semantic-1',
          label: 'Prefer Rust for systems services',
          source: 'preference',
          tier: 'short',
          forget: 'protected',
          retentionScore: 0.94,
          timestamp: '2026-07-20T08:00:00Z',
          entityIds: ['provider:codex', 'tag:rust', 'file:src/lib.rs'],
        },
        {
          id: 'event:procedure-1',
          memoryId: 'procedure-1',
          label: 'Run focused cargo tests',
          source: 'workflow',
          tier: 'long',
          forget: 'protected',
          retentionScore: 0.81,
          timestamp: '2026-06-18T08:00:00Z',
          entityIds: ['tool:cargo', 'tag:tests'],
        },
        {
          id: 'event:episodic-old',
          memoryId: 'episodic-old',
          label: 'Old shell experiment',
          source: 'ctx',
          tier: 'long',
          forget: 'candidate',
          retentionScore: 0.18,
          timestamp: '2025-01-02T08:00:00Z',
          entityIds: ['provider:claude-code', 'tag:experiment'],
        },
      ],
      entities: [
        {
          id: 'provider:codex',
          kind: 'provider',
          name: 'Codex',
          aliases: ['OpenAI Codex'],
          mentions: 1,
          importance: 0.9,
          firstSeen: '2026-07-20T08:00:00Z',
          lastSeen: '2026-07-20T08:00:00Z',
          memoryIds: ['semantic-1'],
        },
        {
          id: 'tag:rust',
          kind: 'tag',
          name: 'rust',
          aliases: [],
          mentions: 1,
          importance: 0.9,
          firstSeen: '2026-07-20T08:00:00Z',
          lastSeen: '2026-07-20T08:00:00Z',
          memoryIds: ['semantic-1'],
        },
        {
          id: 'file:src/lib.rs',
          kind: 'file',
          name: 'src/lib.rs',
          aliases: [],
          mentions: 1,
          importance: 0.9,
          firstSeen: '2026-07-20T08:00:00Z',
          lastSeen: '2026-07-20T08:00:00Z',
          memoryIds: ['semantic-1'],
        },
        {
          id: 'tool:cargo',
          kind: 'tool',
          name: 'cargo',
          aliases: [],
          mentions: 1,
          importance: 0.78,
          firstSeen: '2026-06-18T08:00:00Z',
          lastSeen: '2026-06-18T08:00:00Z',
          memoryIds: ['procedure-1'],
        },
        {
          id: 'tag:tests',
          kind: 'tag',
          name: 'tests',
          aliases: [],
          mentions: 1,
          importance: 0.78,
          firstSeen: '2026-06-18T08:00:00Z',
          lastSeen: '2026-06-18T08:00:00Z',
          memoryIds: ['procedure-1'],
        },
        {
          id: 'provider:claude-code',
          kind: 'provider',
          name: 'Claude Code',
          aliases: [],
          mentions: 1,
          importance: 0.2,
          firstSeen: '2025-01-02T08:00:00Z',
          lastSeen: '2025-01-02T08:00:00Z',
          memoryIds: ['episodic-old'],
        },
        {
          id: 'tag:experiment',
          kind: 'tag',
          name: 'experiment',
          aliases: [],
          mentions: 1,
          importance: 0.2,
          firstSeen: '2025-01-02T08:00:00Z',
          lastSeen: '2025-01-02T08:00:00Z',
          memoryIds: ['episodic-old'],
        },
      ],
      relations: [
        { id: 0, from: 'event:semantic-1', to: 'provider:codex', kind: 'via', memoryId: 'semantic-1', weight: 0.9 },
        { id: 1, from: 'event:semantic-1', to: 'tag:rust', kind: 'tagged', memoryId: 'semantic-1', weight: 0.8 },
        {
          id: 2,
          from: 'event:semantic-1',
          to: 'file:src/lib.rs',
          kind: 'touches',
          memoryId: 'semantic-1',
          weight: 0.7,
        },
        { id: 3, from: 'event:procedure-1', to: 'tool:cargo', kind: 'used', memoryId: 'procedure-1', weight: 0.9 },
        { id: 4, from: 'event:procedure-1', to: 'tag:tests', kind: 'tagged', memoryId: 'procedure-1', weight: 0.8 },
        { id: 5, from: 'tool:cargo', to: 'tag:tests', kind: 'co-occurs', memoryId: 'procedure-1', weight: 0.35 },
        {
          id: 6,
          from: 'event:episodic-old',
          to: 'provider:claude-code',
          kind: 'via',
          memoryId: 'episodic-old',
          weight: 0.8,
        },
      ],
      facets: {
        'semantic-1': {
          eventId: 'event:semantic-1',
          tier: 'short',
          forget: 'protected',
          retentionScore: 0.94,
          llmExtracted: true,
          consolidated: false,
          conflicts: false,
          entityIds: ['provider:codex', 'tag:rust', 'file:src/lib.rs'],
          relationIds: [0, 1, 2],
        },
        'procedure-1': {
          eventId: 'event:procedure-1',
          tier: 'long',
          forget: 'protected',
          retentionScore: 0.81,
          llmExtracted: true,
          consolidated: true,
          conflicts: true,
          entityIds: ['tool:cargo', 'tag:tests'],
          relationIds: [3, 4, 5],
        },
        'episodic-old': {
          eventId: 'event:episodic-old',
          tier: 'long',
          forget: 'candidate',
          retentionScore: 0.18,
          llmExtracted: false,
          consolidated: false,
          conflicts: false,
          entityIds: ['provider:claude-code', 'tag:experiment'],
          relationIds: [6],
        },
      },
    },
  };
}
