export type CapabilityLocale = 'zh' | 'en';

export const codeCapabilityContent = {
  zh: {
    eyebrow: 'A3S CODE · 五个可见闭环',
    title: '编码 Agent 的能力和边界，都应该看得见。',
    description:
      'A3S Code 不把语义检索、工具披露、人工授权、远程执行和历史召回藏在聊天框后。每一步都有明确的输入、状态与结果。',
    action: '查看完整契约',
    intelligence: {
      index: '01',
      label: '代码智能',
      status: 'SAVED-FILE 语义',
      title: '按语义理解代码，而不只是搜索文本。',
      description:
        '原生 symbols、定义、引用、实现和诊断，在 Agent 工具、`/ide` 与 Monaco 之间共享同一套 saved-file 契约。',
      href: '/code/code-intelligence',
      windowTitle: 'workspace / 语义导航',
      command: ':definition',
      tabs: ['agent.rs', 'session.rs', 'tools.rs'],
      symbol: 'SessionBuilder',
      location: 'src/agent/session.rs:148',
      evidence: 'saved rev 184 · 12 个引用 · 0 个诊断',
    },
    hitl: {
      index: '02',
      label: 'HUMAN IN THE LOOP',
      status: '精确调用已暂停',
      title: '把风险变成一次明确决策。',
      description:
        '越过边界的调用会在副作用发生前暂停。用户可以只批准本次调用、记录精确规则，或拒绝并给出新指引。',
      href: '/code/capabilities#human-in-the-loop',
      prompt: '需要授权',
      run: 'Bash(git push origin main)',
      risk: '外部副作用 · 修改远程 Git',
      options: [
        '仅允许一次',
        '本会话允许该精确能力',
        '把精确能力规则写入项目',
        '拒绝并告诉 Agent 原因',
      ],
      outcome: '本次已批准 · 精确调用继续执行',
    },
    progressive: {
      index: '03',
      label: '渐进式工具 API',
      status: '按 TURN 披露',
      title: '每个 Turn，只提供当前需要的 API。',
      description:
        'Executor 保留完整注册表；模型只接收核心编码 schema，以及根据当前意图选出的专用工具，让常规 Turn 保持紧凑。',
      href: '/code/capabilities#progressive-tool-api',
      prompt: '测试通过后，提交 parser 修复。',
      rows: [
        ['核心编码工具', '保留'],
        ['git', '本轮披露'],
        ['web / batch / program', '延后'],
        ['MCP 工具目录', '按需'],
      ],
      registry: 'Executor 中的完整注册表保持不变',
      result: '模型上下文只接收本轮相关 schemas',
    },
    runtime: {
      index: '04',
      label: 'RUNTIME 工具',
      status: '登录后远程批处理',
      title: '并行分发独立任务，再汇总结果。',
      description:
        '登录后，`runtime` 可以把独立任务提交给远程 Worker，流式展示 Batch 进度，并返回完整或明确标记为 partial 的结果。',
      href: '/code/capabilities#runtime-tool',
      windowTitle: 'runtime / release-research',
      gate: '/login → runtime 已注册',
      call: 'runtime({ tasks: ["risk", "upgrade", "notes"], worker: "release-research" })',
      submitted: '已提交 3 个并行子任务',
      tasks: ['依赖风险', '升级路径', '发布说明'],
      complete: '3 / 3 完成 · 汇总结果已就绪',
      footer: '幂等重试 · 有界超时 · partial-safe · 需要确认',
    },
    context: {
      index: '05',
      label: '跨会话上下文',
      status: '本地召回',
      title: '找回当时的决策，而不只是找到文件。',
      description:
        '`/ctx` 可以搜索历史会话，把有界 transcript window 暂存给下一条消息，或将选中结果保存为带来源证明的长期记忆。',
      href: '/code/capabilities#cross-session-context',
      query: '/ctx 为什么 auth refresh 会失败？',
      hits: [
        [
          '1.',
          'a3s · 2026-07-18',
          'Refresh token 边界',
          '重试时必须保留原始 session revision…',
        ],
        [
          '2.',
          'a3s · 2026-07-11',
          'Retry policy 审查',
          '超时后不能再次执行非幂等 token exchange…',
        ],
        [
          '3.',
          'a3s · 2026-06-29',
          'Session 恢复',
          '刷新 credential 前先恢复 provider identity…',
        ],
      ],
      attach: '/ctx 1',
      staged: '上下文已暂存 · 只附加到下一条消息一次',
      save: '/ctx save 1',
      saved: '长期记忆 · 保留 source provenance',
      safety: '最多 8 条 · 6000 bytes · quoted + untrusted',
    },
  },
  en: {
    eyebrow: 'A3S CODE · FIVE VISIBLE LOOPS',
    title: 'A coding agent should expose its operations—and its boundaries.',
    description:
      'A3S Code makes semantic lookup, tool disclosure, human authority, remote execution, and prior-session recall observable instead of hiding them behind a chat box.',
    action: 'See the full contract',
    intelligence: {
      index: '01',
      label: 'CODE INTELLIGENCE',
      status: 'SAVED-FILE SEMANTICS',
      title: 'Ask the codebase by meaning.',
      description:
        'Native symbols, definitions, references, implementations, and diagnostics share one saved-file contract across agent tools, `/ide`, and Monaco.',
      href: '/code/code-intelligence',
      windowTitle: 'workspace / semantic navigation',
      command: ':definition',
      tabs: ['agent.rs', 'session.rs', 'tools.rs'],
      symbol: 'SessionBuilder',
      location: 'src/agent/session.rs:148',
      evidence: 'saved rev 184 · 12 references · 0 diagnostics',
    },
    hitl: {
      index: '02',
      label: 'HUMAN IN THE LOOP',
      status: 'EXACT CALL PAUSED',
      title: 'Risk becomes an explicit decision.',
      description:
        'Boundary-crossing calls pause before side effects. The person approves one invocation, records a precise rule, or denies it with guidance.',
      href: '/code/capabilities#human-in-the-loop',
      prompt: 'Permission required',
      run: 'Bash(git push origin main)',
      risk: 'external side effect · mutating Git',
      options: [
        'Allow once',
        'Allow exact capability for this session',
        'Add exact capability rule to project',
        'Deny and tell the agent why',
      ],
      outcome: 'approved once · exact invocation resumed',
    },
    progressive: {
      index: '03',
      label: 'PROGRESSIVE TOOL API',
      status: 'PER-TURN DISCLOSURE',
      title: 'Only this turn’s relevant API surface.',
      description:
        'The executor keeps the full registry. The model receives core coding schemas plus specialized tools selected from current intent, keeping routine turns compact.',
      href: '/code/capabilities#progressive-tool-api',
      prompt: 'Commit the parser fix after tests.',
      rows: [
        ['core coding', 'retained'],
        ['git', 'revealed'],
        ['web / batch / program', 'deferred'],
        ['MCP catalog', 'on demand'],
      ],
      registry: 'the executor registry remains complete',
      result: 'model context receives only this turn’s relevant schemas',
    },
    runtime: {
      index: '04',
      label: 'RUNTIME TOOL',
      status: 'LOGIN-GATED REMOTE BATCH',
      title: 'Fan out independent work, then recombine it.',
      description:
        'After login, `runtime` submits independent tasks to remote workers, streams batch progress, and returns complete or explicitly partial results.',
      href: '/code/capabilities#runtime-tool',
      windowTitle: 'runtime / release-research',
      gate: '/login → runtime registered',
      call: 'runtime({ tasks: ["risk", "upgrade", "notes"], worker: "release-research" })',
      submitted: '3 parallel subtasks submitted',
      tasks: ['Dependency risk', 'Upgrade path', 'Release notes'],
      complete: '3 / 3 complete · combined result ready',
      footer:
        'idempotent retry · bounded timeout · partial-safe · confirmation required',
    },
    context: {
      index: '05',
      label: 'CROSS-SESSION CONTEXT',
      status: 'LOCAL RECALL',
      title: 'Recover the decision, not just the file.',
      description:
        '`/ctx` searches prior sessions, stages a bounded transcript window for the next message, or promotes a selected hit into durable memory with source provenance.',
      href: '/code/capabilities#cross-session-context',
      query: '/ctx why did auth refresh fail?',
      hits: [
        [
          '1.',
          'a3s · 2026-07-18',
          'Refresh token boundary',
          'The retry must keep the original session revision…',
        ],
        [
          '2.',
          'a3s · 2026-07-11',
          'Retry policy review',
          'Do not re-run a non-idempotent exchange after timeout…',
        ],
        [
          '3.',
          'a3s · 2026-06-29',
          'Session restore',
          'Restore the provider identity before refreshing credentials…',
        ],
      ],
      attach: '/ctx 1',
      staged: 'context staged · attached to the next message once',
      save: '/ctx save 1',
      saved: 'durable memory · source provenance preserved',
      safety: 'up to 8 hits · 6000 bytes · quoted + untrusted',
    },
  },
} as const;
