/* eslint-disable */
/* auto-generated by napi-rs */

export interface AgentOptions {
  /** LLM model identifier (e.g., "claude-sonnet-4-20250514", "gpt-4o") */
  model: string
  /** API key for the LLM provider */
  apiKey: string
  /** Path to the workspace directory (sandbox root) */
  workspace?: string
  /** System prompt for the agent */
  systemPrompt?: string
  /** Base URL override for the LLM API */
  baseUrl?: string
  /** Maximum tool execution rounds per turn */
  maxToolRounds?: number
}

export interface AgentResult {
  /** The final text response from the agent */
  text: string
  /** Number of tool calls made during execution */
  toolCallsCount: number
  /** Total prompt tokens used */
  promptTokens: number
  /** Total completion tokens used */
  completionTokens: number
  /** Total tokens used */
  totalTokens: number
}

export interface AgentEvent {
  /** Event type: "start", "text_delta", "tool_start", "tool_end", "turn_start", "turn_end", "end", "error" */
  type: string
  /** Text content (for text_delta and end events) */
  text?: string
  /** Tool name (for tool_start and tool_end events) */
  toolName?: string
  /** Tool ID (for tool_start and tool_end events) */
  toolId?: string
  /** Tool output (for tool_end events) */
  toolOutput?: string
  /** Exit code (for tool_end events) */
  exitCode?: number
  /** Turn number (for turn_start and turn_end events) */
  turn?: number
  /** Prompt text (for start events) */
  prompt?: string
  /** Error message (for error events) */
  error?: string
  /** Token usage (for turn_end and end events) */
  totalTokens?: number
}

export interface ToolResult {
  /** Tool name */
  name: string
  /** Tool output text */
  output: string
  /** Exit code (0 = success) */
  exitCode: number
}

/**
 * AI coding agent with tool execution capabilities.
 *
 * Create an Agent by providing a model name, API key, and workspace path.
 * The agent auto-detects whether to use the Anthropic or OpenAI API based
 * on the model name.
 */
export class Agent {
  constructor(options: AgentOptions)
  /** Send a prompt and wait for the complete response */
  send(prompt: string): Promise<AgentResult>
  /** Send a prompt and get all streaming events as an array */
  stream(prompt: string): Promise<AgentEvent[]>
  /** Execute a tool by name, bypassing the LLM */
  tool(name: string, args: Record<string, unknown>): Promise<ToolResult>
  /** Read a file from the workspace */
  readFile(path: string): Promise<string>
  /** Execute a bash command in the workspace */
  bash(command: string): Promise<string>
  /** Search for files matching a glob pattern */
  glob(pattern: string): Promise<string[]>
  /** Search file contents with a regex pattern */
  grep(pattern: string): Promise<string>
}
