import {
  architectureEdge as edge,
  architectureGroup as group,
  architectureNode as node,
  localized,
  type ArchitectureProject,
} from './architecture-types';
import { interfaceArchitectureProjects } from './interfaces';
import { productArchitectureProjects } from './products';
import { runtimeArchitectureProjects } from './runtime';

export type {
  ArchitectureCategory,
  ArchitectureEdge,
  ArchitectureEdgeKind,
  ArchitectureEvidence,
  ArchitectureGroup,
  ArchitectureNode,
  ArchitectureNodeKind,
  ArchitecturePoint,
  ArchitectureProject,
  LocalizedArchitectureText,
} from './architecture-types';

export const systemArchitectureProject: ArchitectureProject = {
  id: 'a3s-system',
  name: 'A3S',
  category: 'products',
  role: localized(
    'A3S 不是一个大进程。CLI、Desktop、Web、Code、Use、Bench、Test 和 Cloud 通过各自公开接口连接到工作流、数据、运行时与安全组件。',
    'A3S is not one large process. CLI, Desktop, Web, Code, Use, Bench, Test, and Cloud connect through public interfaces to workflow, data, runtime, and security components.',
  ),
  href: 'https://github.com/A3S-Lab/a3s',
  evidence: [
    {
      label: 'Repository map',
      href: 'https://github.com/A3S-Lab/a3s#repository-map',
    },
  ],
  groups: [
    group('products', '产品入口', 'Product entrypoints', 2, 7, 23, 86),
    group('work', 'Agent 与能力', 'Agents and capabilities', 28, 7, 25, 86),
    group('coordination', '编排与数据', 'Coordination and data', 56, 7, 19, 86),
    group('execution', '服务与执行', 'Services and execution', 78, 7, 20, 86),
  ],
  nodes: [
    node(
      'cli',
      'CLI',
      'entry',
      9,
      20,
      '统一命令、Code TUI 和本地组件生命周期。',
      'Umbrella commands, the Code TUI, and local component lifecycle.',
    ),
    node(
      'web',
      'Web / Desktop',
      'entry',
      18,
      43,
      '浏览器工作台与直接连接 Code Core 的原生桌面宿主。',
      'The browser workbench and the native desktop host connected directly to Code Core.',
    ),
    node(
      'cloud',
      'Cloud',
      'service',
      10,
      76,
      '保存期望状态并协调节点上的长期操作。',
      'Stores desired state and coordinates long-running node operations.',
    ),
    node(
      'code',
      'Code',
      'process',
      35,
      20,
      'Agent 和 AgentSession 的可嵌入运行核心。',
      'The embeddable Agent and AgentSession runtime core.',
    ),
    node(
      'use',
      'Use',
      'service',
      45,
      46,
      'Browser、OCR、Box 和扩展包的路由与生命周期。',
      'Routing and lifecycle for Browser, OCR, Box, and extension packages.',
    ),
    node(
      'capabilities',
      'Search / Browser / OCR / Parser / Office / Science',
      'runtime',
      36,
      79,
      '独立发布的检索、浏览器、识别、文档解析、编辑和科研实现。',
      'Independently released search, browser, OCR, parsing, editing, and science implementations.',
    ),
    node(
      'bench',
      'Bench',
      'process',
      48,
      17,
      '冻结 Task 和 Candidate，并运行 Candidate 与 Judge。',
      'Freezes Tasks and Candidates and runs Candidates and Judges.',
    ),
    node(
      'test',
      'Test',
      'process',
      50,
      78,
      '运行确定性场景或受策略与预算约束的 LLM action loop，并保存证据。',
      'Runs deterministic scenarios or policy- and budget-bounded LLM action loops and records evidence.',
    ),
    node(
      'flow',
      'Flow / Event / Lane',
      'service',
      64,
      21,
      '持久工作流、事件传递和有界异步调度。',
      'Durable workflows, event delivery, and bounded async scheduling.',
    ),
    node(
      'data',
      'Memory / ORM',
      'store',
      64,
      52,
      'Agent memory 与类型化 SQL 存储。',
      'Agent memory and typed SQL storage.',
    ),
    node(
      'contracts',
      'ACL / Common / AHP',
      'adapter',
      65,
      80,
      '配置语言、共享 wire types 和 Agent 监督协议。',
      'Configuration language, shared wire types, and the Agent supervision protocol.',
    ),
    node(
      'services',
      'Boot / Gateway / Power',
      'service',
      85,
      18,
      '应用框架、流量代理和本地模型服务。',
      'Application framework, traffic proxy, and local model serving.',
    ),
    node(
      'runtime',
      'Runtime',
      'service',
      84,
      48,
      '通用 Task 与 Service 生命周期。',
      'General Task and Service lifecycle.',
    ),
    node(
      'isolation',
      'Box / OCI Runtime',
      'runtime',
      91,
      73,
      'OCI workload、MicroVM 和共享内核隔离。',
      'OCI workloads, MicroVMs, and shared-kernel isolation.',
    ),
    node(
      'security',
      'Observer / Sentry',
      'security',
      78,
      82,
      '内核信号、分层判断和可选执行拦截。',
      'Kernel signals, tiered decisions, and optional enforcement.',
    ),
  ],
  edges: [
    edge('cli', 'code', 'call', 'a3s code', 'a3s code'),
    edge('web', 'code', 'call', 'session API', 'session API'),
    edge('cli', 'use', 'call', 'a3s use', 'a3s use'),
    edge(
      'web',
      'use',
      'data',
      'verified workbench packages',
      'verified workbench packages',
    ),
    edge(
      'use',
      'capabilities',
      'call',
      'built-in / extension routes',
      'built-in / extension routes',
    ),
    edge('cli', 'bench', 'call', 'a3s bench', 'a3s bench'),
    edge('cli', 'test', 'call', 'a3s-test', 'a3s-test'),
    edge('test', 'capabilities', 'call', 'surface drivers', 'surface drivers'),
    edge(
      'bench',
      'flow',
      'call',
      'durable evaluation steps',
      'durable evaluation steps',
    ),
    edge(
      'code',
      'flow',
      'optional',
      'optional workflow bridge',
      'optional workflow bridge',
    ),
    edge(
      'code',
      'data',
      'data',
      'memory / session data',
      'memory / session data',
    ),
    edge(
      'code',
      'contracts',
      'call',
      'AHP + shared types',
      'AHP + shared types',
    ),
    edge('cloud', 'flow', 'call', 'operations + outbox', 'operations + outbox'),
    edge('cloud', 'data', 'data', 'business state', 'business state'),
    edge(
      'cloud',
      'services',
      'call',
      'API / routes / inference',
      'API / routes / inference',
    ),
    edge(
      'bench',
      'runtime',
      'call',
      'Candidate / Judge units',
      'Candidate / Judge units',
    ),
    edge('cloud', 'runtime', 'call', 'node units', 'node units'),
    edge(
      'runtime',
      'isolation',
      'call',
      'provider operations',
      'provider operations',
    ),
    edge(
      'security',
      'services',
      'control',
      'deny / inline gate',
      'deny / inline gate',
    ),
    edge(
      'isolation',
      'security',
      'event',
      'runtime activity',
      'runtime activity',
    ),
  ],
};

export const architectureProjects: readonly ArchitectureProject[] = [
  ...productArchitectureProjects,
  ...runtimeArchitectureProjects,
  ...interfaceArchitectureProjects,
];

export const architectureProjectCount = architectureProjects.length;
export const architectureNodeCount = architectureProjects.reduce(
  (count, project) => count + project.nodes.length,
  0,
);
