import {
  architectureEdge as edge,
  architectureGroup as group,
  architectureNode as node,
  localized,
  type ArchitectureProject,
} from './architecture-types';

export const serviceArchitectureProjects: readonly ArchitectureProject[] = [
  {
    id: 'boot',
    name: 'Boot',
    category: 'interfaces',
    role: localized(
      '模块化异步服务框架：Module 和 Provider 先编译成 handler，再经过统一 pipeline，最后交给 HTTP、WebSocket 或消息 Transport。',
      'A modular async service framework: Modules and Providers compile into handlers, pass through one execution pipeline, then run through HTTP, WebSocket, or message transports.',
    ),
    href: 'https://github.com/A3S-Lab/Boot',
    evidence: [
      {
        label: 'Boot application model',
        href: 'https://github.com/A3S-Lab/Boot#application-model',
      },
    ],
    groups: [
      group('definition', '应用定义', 'Application definition', 2, 7, 28, 86),
      group(
        'pipeline',
        '协议无关执行',
        'Protocol-neutral execution',
        33,
        7,
        35,
        86,
      ),
      group('adapters', '协议 Adapter', 'Protocol adapters', 71, 7, 27, 86),
    ],
    nodes: [
      node(
        'modules',
        'Modules',
        'entry',
        10,
        20,
        '声明 imports、providers、controllers、gateways 和 lifecycle hooks。',
        'Declares imports, providers, controllers, gateways, and lifecycle hooks.',
      ),
      node(
        'providers',
        'DI providers + scopes',
        'service',
        22,
        44,
        '解析 singleton、request 和 transient 依赖。',
        'Resolves singleton, request, and transient dependencies.',
      ),
      node(
        'definitions',
        'Controllers / gateways / patterns',
        'entry',
        10,
        72,
        '把 HTTP route、WebSocket event 和 message pattern 编译成定义。',
        'Compiles HTTP routes, WebSocket events, and message patterns into definitions.',
      ),
      node(
        'router',
        'Compiled handler registry',
        'process',
        39,
        22,
        '组合 route、middleware 和 module visibility。',
        'Combines routes, middleware, and module visibility.',
      ),
      node(
        'pipeline',
        'Execution pipeline',
        'process',
        51,
        51,
        '按 middleware、guard、interceptor、pipe、validation、handler 执行。',
        'Runs middleware, guards, interceptors, pipes, validation, and handlers in order.',
      ),
      node(
        'filters',
        'Exception filters',
        'control',
        39,
        79,
        '接管未恢复错误并生成协议对应回复。',
        'Handles unrecovered errors and creates protocol-specific replies.',
      ),
      node(
        'messages',
        'Typed request contexts',
        'adapter',
        64,
        22,
        '统一 BootRequest、WebSocketMessage 和 TransportMessage。',
        'Unifies BootRequest, WebSocketMessage, and TransportMessage.',
      ),
      node(
        'http',
        'Axum HTTP + OpenAPI',
        'runtime',
        80,
        18,
        '处理 HTTP/SSE/files/versioning，并生成 OpenAPI/Swagger。',
        'Handles HTTP, SSE, files, versioning, and OpenAPI/Swagger.',
      ),
      node(
        'websocket',
        'WebSocket adapter',
        'runtime',
        89,
        47,
        '负责 upgrade、rooms、broadcast 和连接生命周期。',
        'Owns upgrades, rooms, broadcasts, and connection lifecycle.',
      ),
      node(
        'transport',
        'MessageTransport',
        'runtime',
        80,
        78,
        '连接 in-process、TCP、Redis、NATS、MQTT、RabbitMQ、Kafka 或 gRPC。',
        'Connects in-process, TCP, Redis, NATS, MQTT, RabbitMQ, Kafka, or gRPC.',
      ),
    ],
    edges: [
      edge('modules', 'providers', 'data', 'provider graph', 'provider graph'),
      edge(
        'modules',
        'definitions',
        'data',
        'feature definitions',
        'feature definitions',
      ),
      edge(
        'providers',
        'router',
        'data',
        'resolved dependencies',
        'resolved dependencies',
      ),
      edge('definitions', 'router', 'data', 'handlers', 'handlers'),
      edge('router', 'pipeline', 'call', 'matched handler', 'matched handler'),
      edge(
        'pipeline',
        'filters',
        'event',
        'unrecovered error',
        'unrecovered error',
      ),
      edge(
        'messages',
        'pipeline',
        'data',
        'execution context',
        'execution context',
      ),
      edge('http', 'messages', 'call', 'BootRequest', 'BootRequest'),
      edge(
        'websocket',
        'messages',
        'call',
        'WebSocketMessage',
        'WebSocketMessage',
      ),
      edge(
        'transport',
        'messages',
        'call',
        'TransportMessage',
        'TransportMessage',
      ),
    ],
  },
  {
    id: 'gateway',
    name: 'Gateway',
    category: 'interfaces',
    role: localized(
      '多协议数据平面：入口完成 TLS，Router 匹配规则，Middleware 处理请求，Service pool 做负载与健康，Proxy 转发到具体后端。',
      'A multi-protocol data plane: entrypoints terminate TLS, the Router matches rules, Middleware processes requests, Service pools handle load and health, and Proxies forward to concrete backends.',
    ),
    href: '/docs/gateway',
    evidence: [
      {
        label: 'Gateway architecture',
        href: 'https://github.com/A3S-Lab/Gateway#architecture',
      },
    ],
    groups: [
      group('traffic', '流量路径', 'Traffic path', 2, 7, 70, 86),
      group(
        'control',
        '配置与运维',
        'Configuration and operations',
        75,
        7,
        23,
        86,
      ),
    ],
    nodes: [
      node(
        'clients',
        'HTTP / WS / SSE / gRPC / TCP / UDP',
        'entry',
        8,
        26,
        '客户端连接 Gateway 的协议入口。',
        'Clients connect to protocol-specific Gateway entrypoints.',
      ),
      node(
        'entrypoint',
        'Entrypoints',
        'runtime',
        21,
        26,
        '持有 HTTP/HTTPS/TCP/UDP listener 和连接生命周期。',
        'Owns HTTP/HTTPS/TCP/UDP listeners and connection lifecycle.',
      ),
      node(
        'tls',
        'TLS + ACME',
        'security',
        34,
        26,
        '使用 rustls、SNI、证书和可选 ACME 终止 TLS。',
        'Terminates TLS with rustls, SNI, certificates, and optional ACME.',
      ),
      node(
        'router',
        'Router',
        'process',
        47,
        26,
        '按 Host、Path、Header、Method、SNI 和 priority 匹配。',
        'Matches Host, Path, Header, Method, SNI, and priority.',
      ),
      node(
        'middleware',
        'Middleware pipeline',
        'process',
        60,
        26,
        '执行 auth、rate limit、retry、circuit breaker、CORS、rewrite 等。',
        'Runs auth, rate limits, retries, circuit breakers, CORS, rewrites, and more.',
      ),
      node(
        'service',
        'Service pool',
        'service',
        47,
        68,
        '管理 backend health、load balancing、sticky、mirror 和 failover。',
        'Manages backend health, load balancing, stickiness, mirroring, and failover.',
      ),
      node(
        'scaling',
        'Autoscaler + buffer',
        'control',
        60,
        68,
        '跟踪 concurrency，缓冲请求并按 revision 路由。',
        'Tracks concurrency, buffers requests, and routes by revision.',
      ),
      node(
        'proxies',
        'Protocol proxies',
        'adapter',
        69,
        46,
        '分别转发 HTTP/WS/SSE、gRPC、TCP 和 UDP。',
        'Forwards HTTP/WS/SSE, gRPC, TCP, and UDP through dedicated proxies.',
      ),
      node(
        'backends',
        'Backend endpoints',
        'output',
        69,
        80,
        '接收经过路由和 middleware 处理的流量。',
        'Receives routed and middleware-processed traffic.',
      ),
      node(
        'providers',
        'Config providers',
        'service',
        83,
        20,
        '从文件、DNS、discovery 或 Kubernetes 生成配置。',
        'Builds configuration from files, DNS, discovery, or Kubernetes.',
      ),
      node(
        'reload',
        'Atomic runtime snapshot',
        'store',
        89,
        48,
        '热更新 Router 和 Service registry，尽量保留未变 listener。',
        'Hot-swaps Router and Service registries while preserving unchanged listeners where possible.',
      ),
      node(
        'ops',
        'Management + observability',
        'output',
        84,
        79,
        '提供独立管理 listener、metrics、access log 和 tracing。',
        'Provides a separate management listener, metrics, access logs, and tracing.',
      ),
    ],
    edges: [
      edge('clients', 'entrypoint', 'call', '连接', 'connection'),
      edge('entrypoint', 'tls', 'call', 'TLS / cleartext', 'TLS / cleartext'),
      edge('tls', 'router', 'data', 'request + SNI', 'request + SNI'),
      edge('router', 'middleware', 'call', 'matched route', 'matched route'),
      edge('middleware', 'service', 'call', '处理后请求', 'processed request'),
      edge(
        'service',
        'scaling',
        'control',
        'revision + capacity',
        'revision + capacity',
      ),
      edge(
        'scaling',
        'proxies',
        'call',
        'selected backend',
        'selected backend',
      ),
      edge(
        'proxies',
        'backends',
        'call',
        'protocol traffic',
        'protocol traffic',
      ),
      edge(
        'providers',
        'reload',
        'data',
        'validated config',
        'validated config',
      ),
      edge('reload', 'router', 'control', 'router table', 'router table'),
      edge(
        'reload',
        'service',
        'control',
        'service registry',
        'service registry',
      ),
      edge(
        'entrypoint',
        'ops',
        'event',
        'connections / errors',
        'connections / errors',
      ),
      edge('service', 'ops', 'event', 'health / latency', 'health / latency'),
    ],
  },
  {
    id: 'power',
    name: 'Power',
    category: 'interfaces',
    role: localized(
      '本地模型服务：OpenAI-compatible API 经过 admission 与 autoload，BackendRegistry 选择推理引擎，Model 层管理内容寻址文件，TEE 层横切保护。',
      'A local model server: OpenAI-compatible APIs pass admission and autoload, BackendRegistry selects an inference engine, the Model layer manages content-addressed files, and the TEE layer provides cross-cutting protection.',
    ),
    href: '/docs/power',
    evidence: [
      {
        label: 'Power architecture',
        href: 'https://github.com/A3S-Lab/Power#architecture',
      },
    ],
    groups: [
      group('request', '请求与服务', 'Request and serving', 2, 7, 37, 86),
      group('inference', '推理后端', 'Inference backends', 42, 7, 31, 86),
      group('model', '模型与安全', 'Models and security', 76, 7, 22, 86),
    ],
    nodes: [
      node(
        'runtime-service',
        'Runtime Service / Box',
        'entry',
        9,
        18,
        '可编译成 digest-pinned、带健康检查的 Box Runtime Service。',
        'Can compile into a digest-pinned Box Runtime Service with health checks.',
      ),
      node(
        'api',
        'OpenAI-compatible API',
        'entry',
        12,
        49,
        '提供 chat、completion、embedding、models、pull、attestation 和 health。',
        'Exposes chat, completion, embeddings, models, pull, attestation, and health.',
      ),
      node(
        'server',
        'Server middleware',
        'security',
        28,
        28,
        '处理 rate limit、admission、auth、audit、metrics、TCP/TLS/Vsock。',
        'Handles rate limits, admission, auth, audit, metrics, and TCP/TLS/Vsock.',
      ),
      node(
        'autoload',
        'Model autoload + LRU',
        'process',
        30,
        68,
        '按请求执行 eviction、decrypt、integrity check 和 load。',
        'Performs eviction, decryption, integrity checks, and loading on demand.',
      ),
      node(
        'registry',
        'BackendRegistry',
        'process',
        48,
        43,
        '按 capability、priority、模型格式和 TEE 状态选择 backend。',
        'Selects a backend by capability, priority, model format, and TEE state.',
      ),
      node(
        'mistral',
        'Mistral.rs',
        'runtime',
        63,
        18,
        '纯 Rust 运行 GGUF、SafeTensors、HF 和 vision 模型。',
        'Runs GGUF, SafeTensors, Hugging Face, and vision models in Rust.',
      ),
      node(
        'llama',
        'llama.cpp',
        'runtime',
        64,
        48,
        '提供 GGUF、KV cache、LoRA、grammar 和 vision。',
        'Provides GGUF, KV cache, LoRA, grammar, and vision.',
      ),
      node(
        'picolm',
        'picolm',
        'runtime',
        62,
        78,
        '按 layer streaming 以 O(layer size) 内存运行。',
        'Uses layer streaming with O(layer size) memory.',
      ),
      node(
        'model-registry',
        'Model registry + manifests',
        'store',
        83,
        18,
        '保存模型身份、格式、加载状态和 manifest。',
        'Stores model identity, format, load state, and manifests.',
      ),
      node(
        'blobs',
        'SHA-256 blobs + pull',
        'store',
        90,
        45,
        '下载、断点续传、校验并去重模型 blob。',
        'Downloads, resumes, verifies, and deduplicates model blobs.',
      ),
      node(
        'tee',
        'TEE / encryption / seal',
        'security',
        81,
        72,
        '提供 attestation、加密模型、RA-TLS、privacy、EPC 和 model seal。',
        'Provides attestation, encrypted models, RA-TLS, privacy, EPC, and model sealing.',
      ),
      node(
        'verify',
        'Client verifier',
        'output',
        94,
        84,
        '校验 nonce、measurement、model hash 和硬件证明链。',
        'Verifies nonces, measurements, model hashes, and hardware attestation chains.',
      ),
    ],
    edges: [
      edge(
        'runtime-service',
        'server',
        'control',
        'Service profile',
        'Service profile',
      ),
      edge('api', 'server', 'call', 'HTTP request', 'HTTP request'),
      edge('server', 'autoload', 'call', 'model request', 'model request'),
      edge('autoload', 'registry', 'call', 'loaded model', 'loaded model'),
      edge(
        'registry',
        'mistral',
        'control',
        'backend selection',
        'backend selection',
      ),
      edge(
        'registry',
        'llama',
        'control',
        'backend selection',
        'backend selection',
      ),
      edge(
        'registry',
        'picolm',
        'control',
        'backend selection',
        'backend selection',
      ),
      edge('model-registry', 'autoload', 'data', 'manifest', 'manifest'),
      edge('blobs', 'autoload', 'data', 'verified weights', 'verified weights'),
      edge(
        'tee',
        'autoload',
        'control',
        'decrypt / integrity',
        'decrypt / integrity',
      ),
      edge(
        'tee',
        'registry',
        'control',
        'TEE-aware routing',
        'TEE-aware routing',
      ),
      edge('tee', 'verify', 'data', 'attestation report', 'attestation report'),
    ],
  },
  {
    id: 'ahp',
    name: 'AHP',
    category: 'interfaces',
    role: localized(
      'Agent 与监督 Harness 之间的 JSON-RPC 协议：先握手协商能力，再用 request 处理阻塞决策、notification 发送非阻塞运行状态。',
      'A JSON-RPC protocol between an Agent and a supervision Harness: negotiate capabilities first, then use requests for blocking decisions and notifications for non-blocking runtime state.',
    ),
    href: '/docs/ahp',
    evidence: [
      {
        label: 'AHP protocol',
        href: 'https://github.com/A3S-Lab/AgentHarnessProtocol#message-model',
      },
    ],
    groups: [
      group('agent', 'Agent 侧', 'Agent side', 2, 7, 25, 86),
      group('wire', '协议与传输', 'Protocol and transport', 30, 7, 37, 86),
      group('harness', 'Harness 侧', 'Harness side', 70, 7, 28, 86),
    ],
    nodes: [
      node(
        'agent',
        'Agent runtime',
        'entry',
        10,
        22,
        '在 action、prompt、planning、memory 等控制点发送事件。',
        'Emits events at action, prompt, planning, memory, and related control points.',
      ),
      node(
        'client',
        'AHP client',
        'adapter',
        20,
        49,
        '保留 session、agent、depth、context 和 request ID。',
        'Preserves session, agent, depth, context, and request IDs.',
      ),
      node(
        'enforce',
        'Agent enforcement',
        'runtime',
        10,
        78,
        'Agent 自己执行 Harness 返回的 allow、block、modify 或专用决定。',
        'The Agent applies allow, block, modify, or specialized decisions returned by the Harness.',
      ),
      node(
        'handshake',
        'Handshake + capabilities',
        'security',
        39,
        20,
        '检查 protocol major、能力和 batch / depth 限制。',
        'Checks protocol major version, capabilities, and batch/depth limits.',
      ),
      node(
        'jsonrpc',
        'JSON-RPC envelopes',
        'process',
        48,
        48,
        'ahp/event、ahp/query 和 ahp/batch 使用稳定 message shape。',
        'ahp/event, ahp/query, and ahp/batch use stable message shapes.',
      ),
      node(
        'transports',
        'stdio / HTTP / WS / Unix',
        'adapter',
        58,
        76,
        '同一协议可通过四种已实现 transport 传输。',
        'Carries the same protocol over four implemented transports.',
      ),
      node(
        'server',
        'Harness server',
        'service',
        76,
        28,
        '校验 envelope、request ID、auth、timeout 和 advertised limits。',
        'Validates envelopes, request IDs, auth, timeouts, and advertised limits.',
      ),
      node(
        'handlers',
        'Policy handlers',
        'process',
        87,
        51,
        '处理 approval、safety、context、memory、reasoning、rate limit 等。',
        'Handles approval, safety, context, memory, reasoning, rate limits, and more.',
      ),
      node(
        'decision',
        'Typed decision',
        'output',
        76,
        78,
        '返回通用 Decision 或 Context、Memory、Planning 等专用 payload。',
        'Returns a generic Decision or specialized Context, Memory, Planning, and similar payload.',
      ),
      node(
        'telemetry',
        'Runtime notifications',
        'output',
        92,
        20,
        'run_lifecycle、task_list、verification 等事件用于 UI、replay 和 audit。',
        'run_lifecycle, task_list, verification, and similar events feed UIs, replay, and audit.',
      ),
    ],
    edges: [
      edge('agent', 'client', 'call', 'AHP event', 'AHP event'),
      edge('client', 'handshake', 'call', 'ahp/handshake', 'ahp/handshake'),
      edge(
        'handshake',
        'jsonrpc',
        'control',
        'negotiated limits',
        'negotiated limits',
      ),
      edge(
        'client',
        'jsonrpc',
        'data',
        'request / notification',
        'request / notification',
      ),
      edge('jsonrpc', 'transports', 'data', 'JSON-RPC 2.0', 'JSON-RPC 2.0'),
      edge(
        'transports',
        'server',
        'call',
        'transport message',
        'transport message',
      ),
      edge('server', 'handlers', 'call', 'typed event', 'typed event'),
      edge(
        'handlers',
        'decision',
        'data',
        'blocking result',
        'blocking result',
      ),
      edge(
        'decision',
        'enforce',
        'control',
        'allow / block / modify',
        'allow / block / modify',
      ),
      edge(
        'server',
        'telemetry',
        'event',
        'non-blocking contract events',
        'non-blocking contract events',
      ),
    ],
  },
  {
    id: 'acl',
    name: 'ACL',
    category: 'interfaces',
    role: localized(
      'A3S Agent Configuration Language：Lexer 和 Parser 生成带 span 的 AST，Schema 做封闭校验，Generator 产出跨 Rust/Node 一致的 canonical bytes 与 digest。',
      'The A3S Agent Configuration Language: Lexer and Parser produce a spanned AST, Schema performs closed validation, and Generator emits canonical bytes and digests identical across Rust and Node.',
    ),
    href: '/docs/acl',
    evidence: [
      {
        label: 'ACL language and APIs',
        href: 'https://github.com/A3S-Lab/ACL#readme',
      },
    ],
    groups: [
      group('parse', '解析', 'Parsing', 2, 7, 43, 86),
      group(
        'admit',
        '校验与规范化',
        'Validation and canonicalization',
        48,
        7,
        32,
        86,
      ),
      group('sdk', 'SDK', 'SDKs', 83, 7, 15, 86),
    ],
    nodes: [
      node(
        'source',
        'ACL source',
        'entry',
        9,
        25,
        '包含 block、attribute、label、list、object 和 function call。',
        'Contains blocks, attributes, labels, lists, objects, and function calls.',
      ),
      node(
        'limits',
        'Parse limits',
        'security',
        9,
        72,
        '限制 UTF-8 bytes、nesting、items、token 和 diagnostics 数量。',
        'Bounds UTF-8 bytes, nesting, items, tokens, and diagnostic counts.',
      ),
      node(
        'lexer',
        'Lexer',
        'process',
        24,
        25,
        '产生 token、UTF-8 byte offset、line 和 column。',
        'Produces tokens, UTF-8 byte offsets, lines, and columns.',
      ),
      node(
        'parser',
        'Parser',
        'process',
        38,
        25,
        '按 ACL 自身语法构建文档；不使用 HCL parser。',
        'Builds documents according to ACL’s own grammar without an HCL parser.',
      ),
      node(
        'ast',
        'Typed AST',
        'store',
        31,
        72,
        '保存 block、attribute、expression、labels 和 source spans。',
        'Stores blocks, attributes, expressions, labels, and source spans.',
      ),
      node(
        'schema',
        'Closed schema validator',
        'security',
        56,
        24,
        '校验 document shape、cardinality、value kind 和 logical path。',
        'Validates document shape, cardinality, value kinds, and logical paths.',
      ),
      node(
        'diagnostics',
        'Stable diagnostics',
        'output',
        69,
        49,
        '返回稳定 code 和 span，不回显敏感 token value。',
        'Returns stable codes and spans without echoing sensitive token values.',
      ),
      node(
        'generator',
        'Canonical generator',
        'process',
        56,
        76,
        '稳定排序并生成可 round-trip 的原生 ACL。',
        'Generates stably ordered, round-trippable native ACL.',
      ),
      node(
        'digest',
        'Canonical bytes + SHA-256',
        'output',
        72,
        78,
        'Rust 与 Node 对同一 AST 产生逐字节一致结果。',
        'Rust and Node produce byte-identical output for the same AST.',
      ),
      node(
        'sdks',
        'Rust crate / Node SDK',
        'adapter',
        90,
        45,
        '向产品提供 parse、validate、generate 和 digest API。',
        'Exposes parse, validate, generate, and digest APIs to products.',
      ),
    ],
    edges: [
      edge('source', 'lexer', 'data', 'UTF-8 text', 'UTF-8 text'),
      edge('limits', 'lexer', 'control', 'resource bounds', 'resource bounds'),
      edge('lexer', 'parser', 'data', 'tokens', 'tokens'),
      edge('parser', 'ast', 'data', 'Document', 'Document'),
      edge('ast', 'schema', 'call', 'document shape', 'document shape'),
      edge('parser', 'diagnostics', 'event', 'parse errors', 'parse errors'),
      edge('schema', 'diagnostics', 'event', 'schema errors', 'schema errors'),
      edge('ast', 'generator', 'call', 'canonical form', 'canonical form'),
      edge('generator', 'digest', 'data', 'UTF-8 bytes', 'UTF-8 bytes'),
      edge('schema', 'sdks', 'data', 'validation report', 'validation report'),
      edge('digest', 'sdks', 'data', 'canonical output', 'canonical output'),
    ],
  },
];
