import { architectureNode as node, localized, type ArchitectureProject } from './architecture-types';
import { getProjectPrimaryHref } from '../project-links';

export const interfaceArchitectureProjects: readonly ArchitectureProject[] = [
  {
    id: 'boot',
    name: 'Boot',
    category: 'interfaces',
    role: localized('用模块和 Adapter 构建异步服务。', 'Builds async services from modules and adapters.'),
    href: getProjectPrimaryHref('boot'),
    nodes: [
      node('modules', 'Modules + Providers', 'surface', '注册显式模块、依赖与类型化基础设施 Provider。', 'Registers explicit modules, dependencies, and typed infrastructure providers.'),
      node('controllers', 'Controllers / Gateways', 'core', '把路由、消息 pattern 与 handler 编译成定义。', 'Compiles routes, message patterns, and handlers into definitions.'),
      node('pipeline', 'Neutral Pipeline', 'contract', '在协议无关执行管道中处理 scope、guard 与 interceptor。', 'Processes scopes, guards, and interceptors in a protocol-neutral pipeline.'),
      node('messages', 'Typed Messages', 'runtime', '统一 BootRequest、WebSocketMessage 与 TransportMessage。', 'Unifies BootRequest, WebSocketMessage, and TransportMessage.'),
      node('adapters', 'HTTP / WS / Transport', 'evidence', '通过 Axum、WebSocket 或消息传输 Adapter 落地。', 'Runs through Axum, WebSocket, or message transport adapters.'),
    ],
  },
  {
    id: 'gateway',
    name: 'Gateway',
    category: 'interfaces',
    role: localized('在本地代理 AI 请求，并支持多种网络协议。', 'Routes AI requests locally across HTTP, WebSocket, gRPC, TCP, and UDP.'),
    href: getProjectPrimaryHref('gateway'),
    nodes: [
      node('entry', 'Entrypoint + TLS', 'surface', '接收 HTTP、HTTPS、WebSocket、SSE、gRPC、TCP 与 UDP。', 'Accepts HTTP, HTTPS, WebSocket, SSE, gRPC, TCP, and UDP.'),
      node('router', 'Router', 'core', '按 Host、Path、Header、SNI 与优先级匹配规则。', 'Matches rules by Host, Path, Header, SNI, and priority.'),
      node('middleware', 'Middleware Pipeline', 'contract', '预编译认证、限流、熔断、重试、CORS 与改写。', 'Precompiles auth, rate limit, circuit breaker, retry, CORS, and rewrites.'),
      node('service', 'Service Pool', 'runtime', '负责负载均衡、健康、镜像、故障切换与扩缩容。', 'Owns load balancing, health, mirroring, failover, and scaling.'),
      node('backends', 'Protocol Backends', 'evidence', '转发到 HTTP、gRPC、TCP/UDP 后端并保留可观测状态。', 'Forwards to HTTP, gRPC, and TCP/UDP backends with observable state.'),
    ],
  },
  {
    id: 'power',
    name: 'Power',
    category: 'interfaces',
    role: localized('在本地运行模型，并提供 OpenAI 兼容 API。', 'Runs models locally behind an OpenAI-compatible API.'),
    href: getProjectPrimaryHref('power'),
    nodes: [
      node('api', 'OpenAI API', 'surface', '提供 chat、completion、embedding、models、attestation 与 health。', 'Exposes chat, completion, embedding, models, attestation, and health.'),
      node('server', 'Server Layer', 'core', '执行 admission、auth、audit、metrics、TCP/TLS/Vsock 与模型生命周期。', 'Runs admission, auth, audit, metrics, TCP/TLS/Vsock, and model lifecycle.'),
      node('registry', 'Backend Registry', 'contract', '按能力、优先级与 TEE 状态路由推理后端。', 'Routes inference backends by capability, priority, and TEE state.'),
      node('models', 'Model Layer', 'runtime', '管理内容寻址 blob、manifest、pull、LRU 与完整性。', 'Manages content-addressed blobs, manifests, pulls, LRU, and integrity.'),
      node('security', 'TEE + Evidence', 'evidence', '提供 attestation、加密模型、隐私、seal 与 RA-TLS 证据。', 'Provides attestation, encrypted models, privacy, sealing, and RA-TLS evidence.'),
    ],
  },
  {
    id: 'ahp',
    name: 'AHP',
    category: 'interfaces',
    role: localized('让 Agent 在执行关键操作前接受宿主检查。', 'Lets the host inspect and decide on key agent actions before they run.'),
    href: getProjectPrimaryHref('ahp'),
    nodes: [
      node('agent', 'Agent Event', 'surface', 'Agent 在关键控制点发出结构化、类型化事件。', 'The agent emits structured typed events at meaningful control points.'),
      node('transport', 'Transport', 'core', '用 in-process、stdio、HTTP 或其他边界传输同一 envelope。', 'Carries one envelope over in-process, stdio, HTTP, or another boundary.'),
      node('harness', 'Harness', 'contract', '按顺序运行独立 handler，并保持 Agent 与策略解耦。', 'Runs independent handlers in order while separating agent and policy.'),
      node('handlers', 'Policy Handlers', 'runtime', '执行审批、安全、上下文、记忆、审计与自定义判断。', 'Evaluates approval, safety, context, memory, audit, and custom policy.'),
      node('decision', 'Typed Decision', 'evidence', '返回 allow、deny、modify 或附带上下文的显式决定。', 'Returns an explicit allow, deny, modify, or context-bearing decision.'),
    ],
  },
  {
    id: 'acl',
    name: 'ACL',
    category: 'interfaces',
    role: localized('读取和生成 A3S Agent Configuration Language 配置。', 'Reads and writes A3S Agent Configuration Language files.'),
    href: getProjectPrimaryHref('acl'),
    nodes: [
      node('source', 'ACL Source', 'surface', '接收面向 Agent 产品的可读配置文本。', 'Accepts human-readable configuration for agent products.'),
      node('lexer', 'Lexer + Parser', 'core', '按 ACL 自身语法生成有位置信息的结构。', 'Builds positioned structures according to ACL syntax itself.'),
      node('ast', 'Typed AST', 'contract', '用明确 block、attribute、expression 与 diagnostic 表达配置。', 'Represents configuration with explicit blocks, attributes, expressions, and diagnostics.'),
      node('generator', 'Canonical Generator', 'runtime', '从 AST 生成稳定、排序且可 round-trip 的 ACL。', 'Generates stable, sorted, round-trippable ACL from the AST.'),
      node('sdks', 'Rust / Node SDK', 'evidence', '让 Rust 与 Node 消费同一语言边界和 canonical form。', 'Lets Rust and Node consume the same language boundary and canonical form.'),
    ],
  },
  {
    id: 'tui',
    name: 'TUI',
    category: 'interfaces',
    role: localized('用 Rust 构建终端界面和可复用组件。', 'Builds terminal interfaces and reusable components in Rust.'),
    href: getProjectPrimaryHref('tui'),
    nodes: [
      node('events', 'Terminal Events', 'surface', '统一键盘、鼠标、resize、tick 与应用消息。', 'Unifies keyboard, mouse, resize, tick, and application messages.'),
      node('model', 'Model + Update', 'core', '用 TEA 单向更新保持界面状态可预测。', 'Keeps interface state predictable through TEA-style unidirectional updates.'),
      node('layout', 'Layout + View', 'contract', '通过 Flexbox、宽度测量与纯视图函数生成帧。', 'Builds frames through Flexbox, width measurement, and pure view functions.'),
      node('components', 'Shared Components', 'runtime', '组合 menu、table、diff、timeline、overlay、editor 与 status。', 'Composes menus, tables, diffs, timelines, overlays, editors, and status surfaces.'),
      node('terminal', 'Terminal Backend', 'evidence', '渲染确定性 cell buffer，并支持 snapshot 与交互测试。', 'Renders deterministic cell buffers with snapshot and interaction testing.'),
    ],
  },
  {
    id: 'gui',
    name: 'GUI',
    category: 'interfaces',
    role: localized('用 Rust 组件构建 AppKit、WinUI 和 GTK 原生界面。', 'Builds native AppKit, WinUI, and GTK interfaces from Rust components.'),
    href: getProjectPrimaryHref('gui'),
    nodes: [
      node('rsx', 'RSX / Semantic UI', 'surface', '用 Rust 组件树描述界面与可访问语义。', 'Describes interfaces and accessibility semantics with Rust component trees.'),
      node('reducer', 'Reducer Runtime', 'core', '把事件归约为可预测状态和下一棵 UI tree。', 'Reduces events into predictable state and the next UI tree.'),
      node('ir', 'Native IR', 'contract', '将平台中立节点、属性与动作降级到稳定中间表示。', 'Lowers platform-neutral nodes, properties, and actions into stable intermediate representation.'),
      node('backend', 'Platform Backend', 'runtime', '由 AppKit、WinUI 或 GTK Adapter 创建真实控件。', 'Creates real controls through AppKit, WinUI, or GTK adapters.'),
      node('events', 'Native Events', 'evidence', '把焦点、输入、布局和可访问事件返回 reducer。', 'Returns focus, input, layout, and accessibility events to the reducer.'),
    ],
  },
  {
    id: 'webview',
    name: 'WebView',
    category: 'interfaces',
    role: localized('在原生窗口中安全打开 Agent 提供的 RemoteUI。', 'Opens agent-provided RemoteUI safely in a native window.'),
    href: getProjectPrimaryHref('webview'),
    nodes: [
      node('host', 'Code / Host UI', 'surface', '从可信 Agent surface 发起一个明确的远程 UI 请求。', 'Starts an explicit remote UI request from a trusted agent surface.'),
      node('url', 'Trusted Runtime URL', 'core', '只接受通过宿主验证的 runtime origin 与目标。', 'Accepts only runtime origins and destinations validated by the host.'),
      node('auth', 'Auth Bootstrap', 'contract', '用短期 bootstrap 建立认证且不把凭据暴露给页面。', 'Establishes authentication with a short-lived bootstrap without exposing credentials to the page.'),
      node('window', 'Native WebView', 'runtime', '通过平台窗口加载受限 RemoteUI。', 'Loads the bounded RemoteUI through a platform-native window.'),
      node('bridge', 'Island Events', 'evidence', '将窗口生命周期与经过验证的动作返回宿主。', 'Returns window lifecycle and validated actions to the host.'),
    ],
  },
  {
    id: 'ui',
    name: 'UI',
    category: 'interfaces',
    role: localized('A3S 工作区、文档工具和运维控制台共用的设计系统。', 'The shared design system for A3S workspaces, document tools, and operations consoles.'),
    href: getProjectPrimaryHref('ui'),
    nodes: [
      node('surfaces', 'Product Surfaces', 'surface', '为 Agent 工作区、Office 工具和运维控制台提供同一套交互语言。', 'Gives agent workspaces, Office tools, and operational consoles one interaction language.'),
      node('patterns', 'Workbench Patterns', 'core', '组合 App Shell、Activity Bar、Ribbon、Split Pane 与 Task Pane。', 'Composes App Shell, Activity Bar, Ribbon, Split Pane, and Task Pane patterns.'),
      node('contracts', 'Semantic Contracts', 'contract', '用语义 HTML、设计 token 与可访问状态定义稳定组件边界。', 'Defines stable component boundaries with semantic HTML, design tokens, and accessible states.'),
      node('runtime', 'Controller Runtime', 'runtime', '按需加载小型原生 JavaScript controller，不绑定框架运行时。', 'Loads small native JavaScript controllers on demand without binding a framework runtime.'),
      node('catalog', 'Versioned Catalog', 'evidence', '通过双语、版本化文档和真实预览验证每个公开组件。', 'Verifies every public component through bilingual versioned docs and live previews.'),
    ],
  },
  {
    id: 'observer',
    name: 'Observer',
    category: 'interfaces',
    role: localized('用 eBPF 记录 Agent 的进程、文件、DNS 和网络活动。', 'Uses eBPF to record agent process, file, DNS, and network activity.'),
    href: getProjectPrimaryHref('observer'),
    nodes: [
      node('probes', 'eBPF Probes', 'surface', '从内核捕获 exec、file、DNS、egress 与身份信号。', 'Captures exec, file, DNS, egress, and identity signals from the kernel.'),
      node('collector', 'Collector', 'core', '加载 probes、关联进程并保持有界事件流。', 'Loads probes, correlates processes, and maintains a bounded event stream.'),
      node('contracts', 'Resolver + Classifier', 'contract', '通过可替换 identity、service、exporter 与 policy trait 丰富事件。', 'Enriches events through replaceable identity, service, exporter, and policy traits.'),
      node('export', 'NDJSON / OTel', 'runtime', '输出稳定 NDJSON，再由 Collector 路由到 OTLP 后端。', 'Emits stable NDJSON for collector routing into OTLP backends.'),
      node('guards', 'Kernel Guards', 'evidence', '可选热加载 egress、file 与 exec deny policy。', 'Optionally hot-loads egress, file, and exec deny policy.'),
    ],
    links: [['probes', 'collector'], ['collector', 'contracts'], ['contracts', 'export'], ['contracts', 'guards']],
  },
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'interfaces',
    role: localized('根据 Observer 事件判断风险，并执行 Agent 运行时策略。', 'Evaluates Observer events and enforces agent runtime policy.'),
    href: getProjectPrimaryHref('sentry'),
    nodes: [
      node('events', 'Observer Events', 'surface', '接收 ToolExec、Egress、FileAccess 与模型信号。', 'Receives ToolExec, Egress, FileAccess, and model signals.'),
      node('rules', 'L1 Rules', 'core', '用确定性 ACL 规则处理每个完整事件。', 'Evaluates every complete event with deterministic ACL rules.'),
      node('models', 'L2 / L3 / SAE', 'contract', '仅对升级事件调用快速 LLM、深度 Agent 或特征判断。', 'Invokes a fast LLM, deep agent, or feature judgment only for escalated events.'),
      node('decision', 'Decision + Enforcer', 'runtime', '生成稳定 verdict、risk、reason 与 deny action。', 'Produces stable verdict, risk, reason, and deny actions.'),
      node('kernel', 'Observer Guards', 'evidence', '写入 deny state，由 Observer 的内核 guard 实际执行。', 'Writes deny state that Observer kernel guards actually enforce.'),
    ],
  },
  {
    id: 'updater',
    name: 'Updater',
    category: 'interfaces',
    role: localized('下载、校验和切换 A3S 版本，升级失败时可以回滚。', 'Downloads, verifies, and switches A3S versions, with rollback after a failed update.'),
    href: getProjectPrimaryHref('updater'),
    nodes: [
      node('source', 'Release Source', 'surface', '查询明确仓库、channel 与当前平台版本。', 'Queries an explicit repository, channel, and current platform version.'),
      node('manifest', 'Manifest + Signature', 'core', '验证 release metadata、checksum、签名与兼容条件。', 'Validates release metadata, checksums, signatures, and compatibility conditions.'),
      node('asset', 'Asset Selection', 'contract', '为 OS、architecture 与安装类型选择唯一资产。', 'Selects one asset for the OS, architecture, and installation type.'),
      node('install', 'Staged Install', 'runtime', '在安全路径中下载、校验、暂存并原子替换。', 'Downloads, verifies, stages, and atomically replaces within a safe path.'),
      node('health', 'Health + Rollback', 'evidence', '用健康门与可恢复状态确认升级或回滚。', 'Confirms or rolls back the update through health gates and recoverable state.'),
    ],
  },
  {
    id: 'homebrew',
    name: 'Homebrew Tap',
    category: 'interfaces',
    role: localized('通过 Homebrew 安装和更新已发布的 A3S 命令。', 'Installs and updates released A3S commands through Homebrew.'),
    href: getProjectPrimaryHref('homebrew'),
    nodes: [
      node('releases', 'Release Archives', 'surface', '消费项目发布的版本化平台资产与 checksum。', 'Consumes versioned platform assets and checksums published by projects.'),
      node('formula', 'Formula / Cask', 'core', '声明版本、URL、哈希、依赖与安装步骤。', 'Declares version, URL, hash, dependencies, and installation steps.'),
      node('tap', 'Tap Repository', 'contract', '为 a3s-lab/tap 维护可审查的分发索引。', 'Maintains a reviewable distribution index for a3s-lab/tap.'),
      node('brew', 'Homebrew Lifecycle', 'runtime', '执行 tap、install、upgrade、uninstall 与 source build。', 'Executes tap, install, upgrade, uninstall, and source-build lifecycle.'),
      node('commands', 'Installed Commands', 'evidence', '把已验证的 Box、Code、Search、Power 等命令放入 PATH。', 'Places verified Box, Code, Search, Power, and other commands on PATH.'),
    ],
  },
];
