import {
  architectureEdge as edge,
  architectureGroup as group,
  architectureNode as node,
  localized,
  type ArchitectureProject,
} from './architecture-types';

export const uiSecurityArchitectureProjects: readonly ArchitectureProject[] = [
  {
    id: 'tui',
    name: 'TUI',
    category: 'interfaces',
    role: localized(
      'TEA 终端 UI：Event 转成 Msg，update 修改 Model，view 生成 Element tree，Taffy 布局后画入 cell grid，再只刷新变化的行。',
      'A TEA terminal UI: Events become Msg values, update changes the Model, view builds an Element tree, Taffy lays it out into a cell grid, and only changed lines are redrawn.',
    ),
    href: '/docs/tui',
    evidence: [
      {
        label: 'TUI architecture',
        href: 'https://github.com/A3S-Lab/TUI#architecture',
      },
    ],
    groups: [
      group('state', '状态循环', 'State loop', 2, 7, 38, 86),
      group('render', '布局与绘制', 'Layout and paint', 43, 7, 39, 86),
      group('terminal', '终端', 'Terminal', 85, 7, 13, 86),
    ],
    nodes: [
      node(
        'events',
        'Keyboard / mouse / resize / tick',
        'entry',
        10,
        22,
        '统一 Crossterm 事件、定时器和应用消息。',
        'Unifies Crossterm events, timers, and application messages.',
      ),
      node(
        'msg',
        'Event → Msg',
        'adapter',
        25,
        22,
        '把平台事件转换为应用定义的类型化消息。',
        'Converts platform events into application-defined typed messages.',
      ),
      node(
        'update',
        'Model.update(msg)',
        'process',
        25,
        58,
        '单向修改状态并返回异步 Cmd。',
        'Updates state in one direction and returns asynchronous commands.',
      ),
      node(
        'view',
        'view()',
        'process',
        10,
        76,
        '从当前 Model 纯函数式构建界面。',
        'Builds the interface from the current Model as a pure function.',
      ),
      node(
        'components',
        'Components + Element tree',
        'store',
        49,
        22,
        '组合菜单、表格、diff、timeline、editor、overlay 等组件。',
        'Composes menus, tables, diffs, timelines, editors, overlays, and other components.',
      ),
      node(
        'layout',
        'Taffy Flexbox',
        'process',
        62,
        40,
        '计算 width、gap、padding、alignment 和嵌套布局。',
        'Computes widths, gaps, padding, alignment, and nested layout.',
      ),
      node(
        'paint',
        'Paint to cell grid',
        'process',
        49,
        72,
        '把 Element tree 画成确定性的 terminal cells。',
        'Paints the Element tree into deterministic terminal cells.',
      ),
      node(
        'diff',
        'Incremental line diff',
        'process',
        72,
        72,
        '比较前后 frame，只生成需要刷新的 ANSI 输出。',
        'Compares frames and emits ANSI output only for changed lines.',
      ),
      node(
        'terminal',
        'Crossterm terminal',
        'runtime',
        91,
        45,
        '写入终端并把新的键鼠事件送回循环。',
        'Writes to the terminal and feeds new input events back into the loop.',
      ),
      node(
        'snapshots',
        'Headless snapshots',
        'output',
        72,
        18,
        '在无终端环境验证 layout、paint、resize 和交互命中。',
        'Validates layout, paint, resize, and interaction hit-testing headlessly.',
      ),
    ],
    edges: [
      edge('events', 'msg', 'data', 'terminal event', 'terminal event'),
      edge('msg', 'update', 'call', 'Msg', 'Msg'),
      edge('update', 'view', 'control', 'new Model', 'new Model'),
      edge('view', 'components', 'data', 'Element tree', 'Element tree'),
      edge('components', 'layout', 'call', 'layout nodes', 'layout nodes'),
      edge('layout', 'paint', 'data', 'computed boxes', 'computed boxes'),
      edge('paint', 'diff', 'data', 'cell grid', 'cell grid'),
      edge('diff', 'terminal', 'call', 'ANSI changes', 'ANSI changes'),
      edge('terminal', 'events', 'event', 'input', 'input'),
      edge(
        'components',
        'snapshots',
        'data',
        'headless frames',
        'headless frames',
      ),
      edge('paint', 'snapshots', 'data', 'grid snapshots', 'grid snapshots'),
    ],
  },
  {
    id: 'gui',
    name: 'GUI',
    category: 'interfaces',
    role: localized(
      '原生 GUI 编译与渲染链：RSX 降级为 Semantic UI 和 Native IR，keyed diff 生成平台命令，AppKit、WinUI、GTK 再把事件送回 Action。',
      'A native GUI compilation and rendering chain: RSX lowers into Semantic UI and Native IR, keyed diff emits platform commands, and AppKit, WinUI, or GTK returns events as Actions.',
    ),
    href: '/docs/gui',
    evidence: [
      {
        label: 'GUI architecture',
        href: 'https://github.com/A3S-Lab/GUI/blob/main/docs/architecture.md',
      },
    ],
    groups: [
      group('authoring', 'RSX authoring', 'RSX authoring', 2, 7, 24, 86),
      group('portable', '可移植运行时', 'Portable runtime', 29, 7, 43, 86),
      group('native', '平台后端', 'Platform backends', 75, 7, 23, 86),
    ],
    nodes: [
      node(
        'component',
        'ComponentCx / .rsx',
        'entry',
        10,
        20,
        'Rust component function 或注册的 RSX template 产生界面输入。',
        'Rust component functions or registered RSX templates produce interface input.',
      ),
      node(
        'parser',
        'RSX parser + registry',
        'process',
        20,
        48,
        '解析 intrinsic、semantic component、props、style 和 event handler。',
        'Parses intrinsics, semantic components, props, styles, and event handlers.',
      ),
      node(
        'compiled',
        'CompiledRsxNode',
        'store',
        10,
        78,
        '保存已编译节点、stable key 和 action ID。',
        'Stores compiled nodes, stable keys, and action IDs.',
      ),
      node(
        'frame',
        'UiFrame + compiler bridge',
        'adapter',
        37,
        20,
        '把结构化 RSX frame 送入运行时，不传 component instance。',
        'Moves structured RSX frames into the runtime without component instances.',
      ),
      node(
        'semantic',
        'Semantic UI tree',
        'process',
        50,
        20,
        '把 HTML/SVG/rsx_ui 名称映射为可访问语义。',
        'Maps HTML, SVG, and rsx_ui names into accessible semantics.',
      ),
      node(
        'ir',
        'A3S Native UI IR',
        'store',
        62,
        43,
        '保存平台无关 role、props、style、children 和 actions。',
        'Stores platform-neutral roles, props, styles, children, and actions.',
      ),
      node(
        'diff',
        'Keyed diff engine',
        'process',
        48,
        66,
        '复用 stable node，只生成 create、update、insert 和 remove。',
        'Reuses stable nodes and emits only create, update, insert, and remove operations.',
      ),
      node(
        'commands',
        'Native command stream',
        'output',
        65,
        78,
        '不包含线程绑定的 native handle。',
        'Contains no thread-affine native handles.',
      ),
      node(
        'appkit',
        'AppKit',
        'runtime',
        82,
        17,
        '在 macOS 创建真实控件并管理主线程对象。',
        'Creates real controls and manages main-thread objects on macOS.',
      ),
      node(
        'winui',
        'WinUI',
        'runtime',
        90,
        43,
        '在 Windows 执行相同 native command。',
        'Executes the same native commands on Windows.',
      ),
      node(
        'gtk',
        'GTK4',
        'runtime',
        82,
        72,
        '在 Linux 创建 GTK widget 并映射可访问状态。',
        'Creates GTK widgets and maps accessibility state on Linux.',
      ),
      node(
        'events',
        'HostEvent → Action ID',
        'adapter',
        92,
        82,
        '把 focus、input、selection 和 native action 返回应用。',
        'Returns focus, input, selection, and native actions to the application.',
      ),
    ],
    edges: [
      edge('component', 'parser', 'call', 'RSX source', 'RSX source'),
      edge('parser', 'compiled', 'data', 'compiled nodes', 'compiled nodes'),
      edge('compiled', 'frame', 'data', 'UiFrame', 'UiFrame'),
      edge('frame', 'semantic', 'call', 'protocol nodes', 'protocol nodes'),
      edge('semantic', 'ir', 'data', 'semantic roles', 'semantic roles'),
      edge('ir', 'diff', 'call', 'current tree', 'current tree'),
      edge('diff', 'commands', 'data', 'minimal changes', 'minimal changes'),
      edge('commands', 'appkit', 'control', 'macOS', 'macOS'),
      edge('commands', 'winui', 'control', 'Windows', 'Windows'),
      edge('commands', 'gtk', 'control', 'Linux', 'Linux'),
      edge('appkit', 'events', 'event', 'native events', 'native events'),
      edge('winui', 'events', 'event', 'native events', 'native events'),
      edge('gtk', 'events', 'event', 'native events', 'native events'),
      edge('events', 'component', 'control', 'Action ID', 'Action ID'),
    ],
  },
  {
    id: 'webview',
    name: 'WebView',
    category: 'interfaces',
    role: localized(
      'A3S Code 的独立桌面 helper：一条路径打开 RemoteUI / 本地报告，另一条路径读取私有快照并显示 Agent Island；两者都不影响 TUI 主进程。',
      'A standalone desktop helper for A3S Code: one path opens RemoteUI or local reports, while another reads private snapshots and displays Agent Island; neither can block the TUI process.',
    ),
    href: '/docs/webview',
    evidence: [
      {
        label: 'WebView surfaces and lifecycle',
        href: 'https://github.com/A3S-Lab/WebView#readme',
      },
    ],
    groups: [
      group(
        'remote',
        'RemoteUI / report window',
        'RemoteUI / report window',
        2,
        7,
        46,
        86,
      ),
      group('island', 'Agent Island', 'Agent Island', 51, 7, 47, 86),
    ],
    nodes: [
      node(
        'launcher',
        'A3S Code launcher',
        'entry',
        8,
        20,
        '按需要启动 helper；启动失败时回退浏览器或跳过 Island。',
        'Starts the helper on demand; failures fall back to a browser or skip Island.',
      ),
      node(
        'url',
        'URL + auth validation',
        'security',
        22,
        31,
        '只接受 http(s) 或可信 file URL，并从环境读取 token。',
        'Accepts only http(s) or trusted file URLs and reads tokens from the environment.',
      ),
      node(
        'seed',
        'WebView auth seed',
        'process',
        36,
        58,
        '导航前把 token 写入 localStorage，不放入 argv。',
        'Seeds localStorage before navigation without placing tokens in argv.',
      ),
      node(
        'window',
        'Tao / Wry window',
        'runtime',
        22,
        78,
        '创建有尺寸限制的 WKWebView、WebKitGTK 或 WebView2 窗口。',
        'Creates a size-bounded WKWebView, WebKitGTK, or WebView2 window.',
      ),
      node(
        'page',
        'RemoteUI / local report',
        'output',
        41,
        24,
        '显示认证远程 UI 或可信本地静态报告。',
        'Displays authenticated RemoteUI or a trusted local static report.',
      ),
      node(
        'publisher',
        'TUI snapshot publisher',
        'entry',
        58,
        20,
        '把系统 Agent 状态写入私有 snapshot 和 sibling control queue。',
        'Writes system-agent state into a private snapshot and sibling control queue.',
      ),
      node(
        'lock',
        'Snapshot + singleton lock',
        'security',
        72,
        20,
        '校验绝对 sibling path、权限、新鲜度并保证每用户单实例。',
        'Validates absolute sibling paths, permissions, freshness, and one instance per user.',
      ),
      node(
        'island-html',
        'Embedded Island HTML/CSS/JS',
        'store',
        61,
        55,
        '离线渲染 compact/expanded 视图，不依赖 React、TUI 或 GUI crate。',
        'Renders compact and expanded views offline without React, TUI, or the GUI crate.',
      ),
      node(
        'island-window',
        'Transparent native window',
        'runtime',
        80,
        49,
        '处理 top-center、notch safe area、drag、focus 和 always-on-top。',
        'Handles top-center placement, notch safe areas, drag, focus, and always-on-top behavior.',
      ),
      node(
        'controls',
        'Bounded control request queue',
        'store',
        70,
        80,
        '写入短期 one-shot approval、stop、cancel 或 reply 请求。',
        'Writes short-lived one-shot approval, stop, cancel, or reply requests.',
      ),
      node(
        'revalidate',
        'TUI revalidation',
        'security',
        91,
        78,
        '主 TUI 按当前 session、activity 和 token 再校验后执行。',
        'The main TUI revalidates current session, activity, and tokens before execution.',
      ),
    ],
    edges: [
      edge('launcher', 'url', 'call', '--url', '--url'),
      edge('url', 'seed', 'control', 'validated origin', 'validated origin'),
      edge(
        'seed',
        'window',
        'call',
        'initialization script',
        'initialization script',
      ),
      edge('window', 'page', 'call', 'navigate', 'navigate'),
      edge('launcher', 'lock', 'call', '--agent-island', '--agent-island'),
      edge('publisher', 'lock', 'data', 'private snapshot', 'private snapshot'),
      edge(
        'lock',
        'island-html',
        'data',
        'sanitized status',
        'sanitized status',
      ),
      edge(
        'island-html',
        'island-window',
        'call',
        'render surface',
        'render surface',
      ),
      edge(
        'island-window',
        'controls',
        'control',
        'user action',
        'user action',
      ),
      edge(
        'controls',
        'revalidate',
        'data',
        'one-shot request',
        'one-shot request',
      ),
      edge(
        'revalidate',
        'publisher',
        'event',
        'updated state',
        'updated state',
      ),
    ],
  },
  {
    id: 'observer',
    name: 'Observer',
    category: 'interfaces',
    role: localized(
      'Linux 内核观测与可选拦截：eBPF probe 把进程、网络、DNS、文件和 LLM 信号送到 collector；独立 guard 可按外部 deny file 拒绝 egress、open 或 exec。',
      'Linux kernel observation with optional intervention: eBPF probes send process, network, DNS, file, and LLM signals to a collector; separate guards can deny egress, open, or exec using external deny files.',
    ),
    href: '/docs/observer',
    evidence: [
      {
        label: 'Observer architecture',
        href: 'https://github.com/A3S-Lab/Observer#architecture',
      },
    ],
    groups: [
      group('kernel-observe', '内核观测', 'Kernel observation', 2, 7, 25, 86),
      group(
        'userspace',
        '用户态关联与导出',
        'Userspace correlation and export',
        30,
        7,
        40,
        86,
      ),
      group('intervene', '可选拦截', 'Optional intervention', 73, 7, 25, 86),
    ],
    nodes: [
      node(
        'agents',
        'Unmodified agent processes',
        'entry',
        9,
        20,
        '任何语言的 Agent 和 tool 子进程无需集成 SDK。',
        'Agents and tool subprocesses in any language require no SDK integration.',
      ),
      node(
        'probes',
        'eBPF probes + fanotify',
        'runtime',
        18,
        48,
        '采集 exec、exit、connect、SNI、DNS、file、SSL 和 security syscall。',
        'Captures exec, exit, connect, SNI, DNS, file, SSL, and security syscalls.',
      ),
      node(
        'rings',
        'Kernel ring buffers',
        'store',
        9,
        79,
        '把有界事件从内核送到用户态并统计 drop。',
        'Moves bounded events from kernel to userspace and counts drops.',
      ),
      node(
        'collector',
        'Aya collector',
        'process',
        37,
        22,
        '加载 probe、读取 ring buffer 并生成 CollectorHeartbeat。',
        'Loads probes, reads ring buffers, and emits CollectorHeartbeat.',
      ),
      node(
        'identity',
        'Identity resolver',
        'process',
        52,
        18,
        '从 Kubernetes cgroup、/proc 或 comm 识别 agent、task 和 process。',
        'Resolves agents, tasks, and processes from Kubernetes cgroups, /proc, or comm.',
      ),
      node(
        'correlation',
        'PID/FD correlation',
        'process',
        42,
        55,
        '把 socket FD、peer、DNS、SNI 和 LLM call 关联起来。',
        'Correlates socket FDs, peers, DNS, SNI, and LLM calls.',
      ),
      node(
        'classifier',
        'Service classifier',
        'process',
        59,
        53,
        '把 SNI 映射到已知 LLM provider 或自定义 service。',
        'Maps SNI to known LLM providers or custom services.',
      ),
      node(
        'ndjson',
        'NDJSON events',
        'output',
        42,
        82,
        '输出稳定的 ToolExec、Egress、FileAccess、LlmCall 等记录。',
        'Emits stable ToolExec, Egress, FileAccess, LlmCall, and related records.',
      ),
      node(
        'otel',
        'OTel Collector / backend',
        'output',
        63,
        82,
        '将 NDJSON 转送到 OTLP 和运维后端。',
        'Routes NDJSON into OTLP and operations backends.',
      ),
      node(
        'controller',
        'External policy controller',
        'entry',
        79,
        20,
        '读取事件或其他规则，写入 egress / file deny list。',
        'Reads events or other policy inputs and writes egress/file deny lists.',
      ),
      node(
        'egress-guard',
        'cgroup connect4 guard',
        'security',
        89,
        46,
        '热加载 IP/hostname deny state，在 connect() 返回 EPERM。',
        'Hot-loads IP/hostname deny state and returns EPERM from connect().',
      ),
      node(
        'file-guard',
        'fanotify file / exec guard',
        'security',
        82,
        78,
        '按路径拒绝 open 和 executable launch。',
        'Denies open and executable launch by path.',
      ),
    ],
    edges: [
      edge(
        'agents',
        'probes',
        'event',
        'syscalls / network',
        'syscalls / network',
      ),
      edge('probes', 'rings', 'event', 'kernel events', 'kernel events'),
      edge('rings', 'collector', 'data', 'bounded records', 'bounded records'),
      edge('collector', 'identity', 'call', 'process facts', 'process facts'),
      edge(
        'identity',
        'correlation',
        'data',
        'agent identity',
        'agent identity',
      ),
      edge('correlation', 'classifier', 'data', 'peer / SNI', 'peer / SNI'),
      edge('classifier', 'ndjson', 'data', 'enriched event', 'enriched event'),
      edge('ndjson', 'otel', 'data', 'event stream', 'event stream'),
      edge(
        'ndjson',
        'controller',
        'event',
        'optional feedback',
        'optional feedback',
      ),
      edge(
        'controller',
        'egress-guard',
        'control',
        'egress deny file',
        'egress deny file',
      ),
      edge(
        'controller',
        'file-guard',
        'control',
        'path deny file',
        'path deny file',
      ),
      edge('egress-guard', 'agents', 'control', 'deny connect', 'deny connect'),
      edge(
        'file-guard',
        'agents',
        'control',
        'deny open / exec',
        'deny open / exec',
      ),
    ],
  },
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'interfaces',
    role: localized(
      '分层安全判断：Observer 事件先过 L1 规则，必要时升级到 L2 模型、L3 Code Agent 或 SAE；另有 inline wire 路径在 Gateway 中屏蔽敏感片段。',
      'Tiered security decisions: Observer events pass L1 rules and may escalate to an L2 model, an L3 Code Agent, or SAE; a separate inline-wire path masks sensitive spans inside Gateway.',
    ),
    href: '/docs/sentry',
    evidence: [
      {
        label: 'Sentry tiers and inline gate',
        href: 'https://github.com/A3S-Lab/Sentry#readme',
      },
    ],
    groups: [
      group(
        'events',
        '运行时事件判断',
        'Runtime event evaluation',
        2,
        7,
        65,
        86,
      ),
      group(
        'inline',
        '请求内联检查',
        'Inline request inspection',
        70,
        7,
        28,
        86,
      ),
    ],
    nodes: [
      node(
        'observer',
        'Observer events',
        'entry',
        8,
        22,
        '接收 ToolExec、Egress、DNS、FileAccess、SslContent 等。',
        'Receives ToolExec, Egress, DNS, FileAccess, SslContent, and related events.',
      ),
      node(
        'l1',
        'L1 ACL rules',
        'security',
        22,
        22,
        '对完整事件执行确定性规则并产生 allow、block 或 escalate。',
        'Runs deterministic rules over complete events and returns allow, block, or escalate.',
      ),
      node(
        'l2',
        'L2 fast LLM',
        'service',
        38,
        15,
        '只判断升级事件；可快速 block 或继续升级。',
        'Evaluates only escalated events and can block quickly or escalate further.',
      ),
      node(
        'l3',
        'L3 Code agent',
        'service',
        38,
        45,
        '加载安全 Skills，调查 actor、attack chain 和 blast radius。',
        'Loads security Skills to investigate the actor, attack chain, and blast radius.',
      ),
      node(
        'power',
        'Power SAE activations',
        'entry',
        22,
        78,
        '从 TEE 内模型取得 sparse feature IDs / activations，不读取明文。',
        'Receives sparse feature IDs and activations from a model inside a TEE without plaintext.',
      ),
      node(
        'sae',
        'SAE judge',
        'process',
        38,
        78,
        '按 feature dictionary 线性计算风险和解释。',
        'Scores risk linearly against a feature dictionary and explains the drivers.',
      ),
      node(
        'pipeline',
        'Tier arbitration',
        'process',
        54,
        35,
        '串行或 speculative 并行组合 L1、L2、L3 与 SAE 结果。',
        'Combines L1, L2, L3, and SAE serially or with speculative parallelism.',
      ),
      node(
        'decision',
        'Decision + action',
        'output',
        54,
        70,
        '输出 verdict、severity、reason 和 DenyEgress / DenyFile / DenyExec。',
        'Outputs verdict, severity, reason, and DenyEgress/DenyFile/DenyExec actions.',
      ),
      node(
        'enforcer',
        'Observer guards',
        'security',
        67,
        82,
        '把 deny state 写入 Observer 的 kernel guards。',
        'Writes deny state into Observer kernel guards.',
      ),
      node(
        'gateway',
        'Gateway wire proxy',
        'entry',
        77,
        20,
        '在 LLM/MCP 请求转发前提交 decoded body。',
        'Submits decoded LLM/MCP bodies before forwarding.',
      ),
      node(
        'inspect',
        'Inline inspector',
        'security',
        85,
        42,
        '复用 SslContent 规则和可选 L2 判断 wire content。',
        'Reuses SslContent rules and optional L2 for wire content.',
      ),
      node(
        'redact',
        'Span masking + restore map',
        'process',
        78,
        72,
        '把 secret/PII 替换为 placeholder，并只在配对响应中恢复。',
        'Replaces secrets/PII with placeholders and restores them only in the paired response.',
      ),
      node(
        'provider',
        'Model / MCP provider',
        'runtime',
        93,
        73,
        '只看到被允许且已屏蔽的 outbound request。',
        'Sees only allowed and masked outbound requests.',
      ),
    ],
    edges: [
      edge('observer', 'l1', 'call', 'security event', 'security event'),
      edge('l1', 'l2', 'control', 'escalate', 'escalate'),
      edge(
        'l1',
        'l3',
        'control',
        'direct / speculative',
        'direct / speculative',
      ),
      edge('l2', 'pipeline', 'data', 'fast verdict', 'fast verdict'),
      edge(
        'l3',
        'pipeline',
        'data',
        'investigation verdict',
        'investigation verdict',
      ),
      edge('power', 'sae', 'data', 'sparse features', 'sparse features'),
      edge('sae', 'pipeline', 'data', 'feature score', 'feature score'),
      edge('l1', 'pipeline', 'data', 'rule verdict', 'rule verdict'),
      edge('pipeline', 'decision', 'data', 'final verdict', 'final verdict'),
      edge('decision', 'enforcer', 'control', 'deny action', 'deny action'),
      edge('gateway', 'inspect', 'call', 'decoded body', 'decoded body'),
      edge('inspect', 'redact', 'data', 'allowed spans', 'allowed spans'),
      edge('redact', 'provider', 'call', 'masked request', 'masked request'),
      edge('inspect', 'pipeline', 'optional', 'L2 escalation', 'L2 escalation'),
    ],
  },
];
