import {
  architectureEdge as edge,
  architectureGroup as group,
  architectureNode as node,
  localized,
  type ArchitectureProject,
} from './architecture-types';

export const operationalArchitectureProjects: readonly ArchitectureProject[] = [
  {
    id: 'updater',
    name: 'Updater',
    category: 'interfaces',
    role: localized(
      '两条更新路径：单机 CLI 从 GitHub Release 校验并原子替换自身；fleet 更新验证签名 metadata，经过 drain、启动和健康门后激活或回滚。',
      'Two update paths: a standalone CLI verifies a GitHub Release and atomically replaces itself; fleet updates verify signed metadata, then pass drain, startup, and health gates before activation or rollback.',
    ),
    href: '/docs/updater',
    evidence: [
      {
        label: 'Updater source modules',
        href: 'https://github.com/A3S-Lab/a3s/tree/main/crates/updater/src',
      },
    ],
    groups: [
      group('self', '单机自更新', 'Standalone self-update', 2, 7, 47, 86),
      group('fleet', 'Fleet 更新', 'Fleet update', 52, 7, 46, 86),
    ],
    nodes: [
      node(
        'config',
        'UpdateConfig',
        'entry',
        7,
        18,
        '声明 binary、crate、当前版本和 GitHub repository。',
        'Declares the binary, crate, current version, and GitHub repository.',
      ),
      node(
        'release',
        'GitHub Release API',
        'service',
        21,
        18,
        '查询 latest 或指定 release 及其 assets。',
        'Queries the latest or a specified release and its assets.',
      ),
      node(
        'asset',
        'Platform asset selector',
        'process',
        33,
        31,
        '按 OS、architecture 和 binary name 选择唯一归档。',
        'Selects one archive by OS, architecture, and binary name.',
      ),
      node(
        'download',
        'Bounded download + SHA-256',
        'security',
        20,
        57,
        '下载 archive 并校验 release checksum。',
        'Downloads the archive and verifies the release checksum.',
      ),
      node(
        'probe',
        'Extract + version probe',
        'process',
        34,
        70,
        '安全解压 binary，并执行 --version 确认目标版本。',
        'Safely extracts the binary and runs --version to confirm the target version.',
      ),
      node(
        'replace',
        'Atomic binary replacement',
        'runtime',
        43,
        43,
        '同目录 staging、sync、backup、rename；失败时恢复旧 binary。',
        'Stages and syncs in the same directory, backs up, renames, and restores the old binary on failure.',
      ),
      node(
        'metadata',
        'Signed target metadata',
        'entry',
        59,
        18,
        '声明 component、version、channel、protocol range、URL、hash 和 rollback policy。',
        'Declares component, version, channel, protocol range, URL, hash, and rollback policy.',
      ),
      node(
        'verify',
        'Ed25519 + policy validation',
        'security',
        73,
        18,
        '验证 trusted key、component、channel、protocol 和 downgrade 约束。',
        'Validates trusted keys, components, channels, protocols, and downgrade constraints.',
      ),
      node(
        'stage',
        'Versioned staging area',
        'store',
        61,
        51,
        '限制下载大小并把新版本放入固定 upgrade root。',
        'Bounds download size and places the new version under a fixed upgrade root.',
      ),
      node(
        'host',
        'FleetUpgradeHost',
        'adapter',
        76,
        48,
        '由 Cloud 节点实现 drain、stop、start、health 和 applied_version。',
        'Implemented by Cloud nodes for drain, stop, start, health, and applied_version.',
      ),
      node(
        'health',
        'Health + applied-version gate',
        'security',
        89,
        27,
        '确认新进程健康且报告目标版本。',
        'Confirms the new process is healthy and reports the target version.',
      ),
      node(
        'rollback',
        'Activation / rollback',
        'runtime',
        89,
        59,
        '成功后切换固定 executable；失败时恢复 previous version。',
        'Switches the fixed executable on success and restores the previous version on failure.',
      ),
      node(
        'receipts',
        'Upgrade + component receipts',
        'store',
        72,
        80,
        '按阶段保存 durable state、provenance、owned paths 和结果。',
        'Stores durable phases, provenance, owned paths, and results.',
      ),
    ],
    edges: [
      edge(
        'config',
        'release',
        'call',
        'repository + version',
        'repository + version',
      ),
      edge('release', 'asset', 'data', 'release assets', 'release assets'),
      edge(
        'asset',
        'download',
        'call',
        'asset URL + checksum',
        'asset URL + checksum',
      ),
      edge('download', 'probe', 'data', 'verified archive', 'verified archive'),
      edge('probe', 'replace', 'control', 'verified binary', 'verified binary'),
      edge('metadata', 'verify', 'call', 'signed JSON', 'signed JSON'),
      edge('verify', 'stage', 'control', 'allowed target', 'allowed target'),
      edge('stage', 'host', 'call', 'staged executable', 'staged executable'),
      edge('host', 'health', 'call', 'start + inspect', 'start + inspect'),
      edge('health', 'rollback', 'control', 'pass / fail', 'pass / fail'),
      edge('rollback', 'receipts', 'data', 'terminal state', 'terminal state'),
      edge('stage', 'receipts', 'data', 'phase journal', 'phase journal'),
      edge('receipts', 'host', 'data', 'recovery state', 'recovery state'),
    ],
  },
  {
    id: 'homebrew',
    name: 'Homebrew Tap',
    category: 'interfaces',
    role: localized(
      'Homebrew 分发仓库：Formula / Cask 固定 release URL、版本、SHA-256、依赖和安装步骤，brew 再完成下载、校验、Cellar 安装与 PATH 链接。',
      'A Homebrew distribution repository: Formulae and Casks pin release URLs, versions, SHA-256 values, dependencies, and install steps; brew handles download, verification, Cellar installation, and PATH links.',
    ),
    href: '/docs/homebrew',
    evidence: [
      {
        label: 'Tap repository structure',
        href: 'https://github.com/A3S-Lab/homebrew-tap#repository-structure',
      },
    ],
    groups: [
      group('release', '上游发布', 'Upstream release', 2, 8, 26, 84),
      group('tap', 'Tap 索引', 'Tap index', 31, 8, 37, 84),
      group('brew', 'Homebrew 生命周期', 'Homebrew lifecycle', 71, 8, 27, 84),
    ],
    nodes: [
      node(
        'projects',
        'A3S project releases',
        'entry',
        10,
        28,
        'Box、Code、Gateway、Power、Search、Use、WebView、a3s 等发布平台资产。',
        'Box, Code, Gateway, Power, Search, Use, WebView, a3s, and others publish platform assets.',
      ),
      node(
        'archives',
        'Archives + checksums',
        'store',
        20,
        68,
        '每个平台归档附带固定版本和 SHA-256。',
        'Each platform archive has a fixed version and SHA-256.',
      ),
      node(
        'formulae',
        'Formula/*.rb',
        'store',
        39,
        24,
        '声明 source/bottle URL、hash、dependency、install 和 test。',
        'Declares source/bottle URLs, hashes, dependencies, install, and tests.',
      ),
      node(
        'casks',
        'Casks/*.rb',
        'store',
        39,
        70,
        '分发桌面 app 或需要 Cask 语义的资产。',
        'Distributes desktop apps or assets that need Cask semantics.',
      ),
      node(
        'tap',
        'a3s-lab/tap',
        'service',
        59,
        47,
        '作为可审查的 Homebrew repository index。',
        'Acts as a reviewable Homebrew repository index.',
      ),
      node(
        'brew',
        'brew tap / update',
        'entry',
        77,
        20,
        '克隆或刷新 tap metadata。',
        'Clones or refreshes tap metadata.',
      ),
      node(
        'install',
        'brew install / upgrade',
        'process',
        85,
        49,
        '选择 Formula/Cask，下载并校验归档，再执行安装 recipe。',
        'Selects a Formula or Cask, downloads and verifies its archive, then runs the install recipe.',
      ),
      node(
        'cellar',
        'Cellar + bin links',
        'runtime',
        77,
        79,
        '保存版本目录，并把命令链接到 Homebrew prefix。',
        'Stores version directories and links commands into the Homebrew prefix.',
      ),
      node(
        'commands',
        'Installed A3S commands',
        'output',
        94,
        79,
        '用户最终从 PATH 运行 a3s、a3s-box、a3s-use 等命令。',
        'Users ultimately run a3s, a3s-box, a3s-use, and related commands from PATH.',
      ),
    ],
    edges: [
      edge(
        'projects',
        'archives',
        'data',
        'release artifacts',
        'release artifacts',
      ),
      edge('archives', 'formulae', 'data', 'URL + SHA-256', 'URL + SHA-256'),
      edge('archives', 'casks', 'data', 'URL + SHA-256', 'URL + SHA-256'),
      edge('formulae', 'tap', 'data', 'Formula index', 'Formula index'),
      edge('casks', 'tap', 'data', 'Cask index', 'Cask index'),
      edge('brew', 'tap', 'call', 'clone / fetch', 'clone / fetch'),
      edge('tap', 'install', 'data', 'selected recipe', 'selected recipe'),
      edge(
        'install',
        'archives',
        'call',
        'download + verify',
        'download + verify',
      ),
      edge('install', 'cellar', 'call', 'install files', 'install files'),
      edge('cellar', 'commands', 'data', 'symlink', 'symlink'),
    ],
  },
];
