import {
  architectureEdge as edge,
  architectureGroup as group,
  architectureNode as node,
  localized,
  type ArchitectureProject,
} from './architecture-types';

export const productContentArchitectures: readonly ArchitectureProject[] = [
  {
    id: 'office',
    name: 'Office',
    category: 'products',
    role: localized(
      '浏览器编辑平面与原生自动化平面分开：编辑器使用 Worker、WASM 和 PDFium，CLI/MCP 使用 Rust OOXML core 和真实文件系统。',
      'Separate browser editing and native automation planes: editors use Workers, WASM, and PDFium while CLI/MCP use a Rust OOXML core and the real filesystem.',
    ),
    href: 'https://github.com/A3S-Lab/Office',
    evidence: [
      {
        label: 'Office browser architecture',
        href: 'https://github.com/A3S-Lab/Office/blob/main/docs/browser-editor-architecture.md',
      },
      {
        label: 'Office native engine',
        href: 'https://github.com/A3S-Lab/Office/blob/main/docs/native-office-engine.md',
      },
    ],
    groups: [
      group(
        'browser',
        '浏览器编辑平面',
        'Browser editing plane',
        2,
        27,
        57,
        68,
      ),
      group(
        'native',
        '原生自动化平面',
        'Native automation plane',
        62,
        27,
        36,
        68,
      ),
      group('contracts', '宿主与契约', 'Host and contracts', 2, 5, 96, 18),
    ],
    nodes: [
      node(
        'hosts',
        'Web / Playground / automation',
        'entry',
        11,
        14,
        '宿主选择文件、编辑体验和权限策略。',
        'The host chooses files, editing UX, and permission policy.',
      ),
      node(
        'contracts',
        'Typed content + operations',
        'adapter',
        40,
        14,
        '浏览器与原生平面共享受限内容模型和操作定义。',
        'Browser and native planes share bounded content models and operation definitions.',
      ),
      node(
        'formats',
        'DOCX / XLSX / PPTX / PDF',
        'store',
        82,
        14,
        '输入输出保持真实 Office/PDF 文件格式。',
        'Inputs and outputs remain real Office and PDF formats.',
      ),
      node(
        'editors',
        'Document / Sheet / Slides',
        'entry',
        13,
        47,
        'React 编辑器负责交互、选择、布局和编辑命令。',
        'React editors own interaction, selection, layout, and editing commands.',
      ),
      node(
        'worker',
        'Editor Worker',
        'process',
        34,
        43,
        '把解析、分页和重计算移出主线程。',
        'Moves parsing, pagination, and recalculation off the main thread.',
      ),
      node(
        'wasm',
        'Rust WebAssembly',
        'runtime',
        49,
        62,
        '在 Worker 中执行需要 Rust 核心的格式处理。',
        'Runs Rust-backed format work inside the Worker.',
      ),
      node(
        'pdf-viewer',
        'EmbedPDF editor',
        'entry',
        13,
        78,
        '负责 PDF 搜索、表单、批注、签名、redaction 和 history。',
        'Owns PDF search, forms, annotations, signatures, redaction, and history.',
      ),
      node(
        'pdfium',
        'PDFium WASM',
        'runtime',
        41,
        82,
        '加载、渲染并导出修改后的真实 PDF bytes。',
        'Loads, renders, and exports modified real PDF bytes.',
      ),
      node(
        'surfaces',
        'CLI / MCP / Skill',
        'entry',
        69,
        42,
        '自动化入口直接操作文件，不启动桌面 Office。',
        'Automation surfaces operate on files without launching desktop Office.',
      ),
      node(
        'rust-core',
        'Native Rust OOXML core',
        'process',
        83,
        43,
        '解析 OPC package、关系、parts 和格式专属结构。',
        'Parses OPC packages, relationships, parts, and format-specific structures.',
      ),
      node(
        'filesystem',
        'Bounded filesystem I/O',
        'security',
        69,
        78,
        '限制路径、大小、原子写入和源文件指纹。',
        'Bounds paths and sizes and handles atomic writes and source fingerprints.',
      ),
      node(
        'package',
        'OOXML package pipeline',
        'process',
        86,
        78,
        '读取、修改、验证并重写 DOCX/XLSX/PPTX package。',
        'Reads, modifies, validates, and rewrites DOCX/XLSX/PPTX packages.',
      ),
      node(
        'report',
        'Compatibility report',
        'output',
        55,
        88,
        '在降级保存前明确列出未支持或归一化的内容。',
        'Lists unsupported or normalized content before a degraded save.',
      ),
    ],
    edges: [
      edge('hosts', 'contracts', 'control', '产品策略', 'product policy'),
      edge('contracts', 'editors', 'data', '内容模型', 'content model'),
      edge('editors', 'worker', 'call', '编辑任务', 'editing task'),
      edge('worker', 'wasm', 'call', '格式处理', 'format work'),
      edge('contracts', 'pdf-viewer', 'data', 'PDF 操作', 'PDF operations'),
      edge('pdf-viewer', 'pdfium', 'call', 'PDFium API', 'PDFium API'),
      edge(
        'contracts',
        'surfaces',
        'data',
        '自动化操作',
        'automation operations',
      ),
      edge(
        'surfaces',
        'rust-core',
        'call',
        'CLI / MCP request',
        'CLI / MCP request',
      ),
      edge('filesystem', 'rust-core', 'data', '源文件', 'source file'),
      edge('rust-core', 'package', 'call', 'OPC parts', 'OPC parts'),
      edge(
        'wasm',
        'formats',
        'data',
        '浏览器导入 / 导出',
        'browser import / export',
      ),
      edge('pdfium', 'formats', 'data', 'modified PDF', 'modified PDF'),
      edge('package', 'formats', 'data', 'OOXML bytes', 'OOXML bytes'),
      edge(
        'package',
        'report',
        'data',
        '兼容性差异',
        'compatibility differences',
      ),
      edge('worker', 'report', 'data', '编辑器降级项', 'editor fallbacks'),
    ],
  },
  {
    id: 'science',
    name: 'Science',
    category: 'products',
    role: localized(
      '科研资源目录与分发仓库：把三类来源归一到同一 taxonomy 和 catalog，再生成可搜索 Atlas、详情页与 TUF 签名包仓库。',
      'A scientific catalog and distribution repository: normalize three source sets into one taxonomy and catalog, then build a searchable Atlas, detail pages, and a TUF-signed package registry.',
    ),
    href: 'https://github.com/A3S-Lab/Science',
    evidence: [
      {
        label: 'Science repository data flow',
        href: 'https://github.com/A3S-Lab/Science#data-layout',
      },
    ],
    groups: [
      group('sources', '目录来源', 'Catalog sources', 2, 7, 23, 86),
      group('catalog', '分类与目录', 'Taxonomy and catalog', 28, 7, 38, 86),
      group('delivery', '浏览与分发', 'Browse and distribute', 69, 7, 29, 86),
    ],
    nodes: [
      node(
        'native',
        'A3S native resources',
        'entry',
        11,
        18,
        'Science 自有 Skills、MCP、AutoDock、Amber MD 和 STORM 工具。',
        'Science-owned Skills, MCP, AutoDock, Amber MD, and STORM tools.',
      ),
      node(
        'ecosystem',
        'Awesome AI for Science',
        'entry',
        11,
        48,
        '按固定 commit 收录经过筛选的生态资源。',
        'Imports curated ecosystem resources from a pinned commit.',
      ),
      node(
        'software',
        'ScienceSoftware',
        'entry',
        11,
        78,
        '只保留研究相关目录元数据和 canonical link。',
        'Keeps only research-relevant directory metadata and canonical links.',
      ),
      node(
        'normalize',
        'Resource normalizer',
        'process',
        34,
        30,
        '统一 id、kind、来源、链接、双语描述和 tags。',
        'Normalizes IDs, kinds, origins, links, bilingual descriptions, and tags.',
      ),
      node(
        'fields',
        'OECD FORD fields',
        'store',
        48,
        15,
        '维护学科与子学科的双语规范表。',
        'Maintains the bilingual discipline and subdiscipline table.',
      ),
      node(
        'capabilities',
        'Research capabilities',
        'store',
        48,
        44,
        '独立标注检索、计算、模拟、可视化和复现能力。',
        'Separately labels discovery, compute, simulation, visualization, and reproducibility capabilities.',
      ),
      node(
        'catalog',
        'JSONL catalog + manifest',
        'store',
        56,
        72,
        '保存 472 条资源、来源计数和 provenance。',
        'Stores 472 resources, source counts, and provenance.',
      ),
      node(
        'atlas',
        '3D Science Atlas',
        'entry',
        76,
        19,
        '生成可搜索图谱、邻居高亮和可访问列表。',
        'Builds a searchable graph, neighbor highlighting, and an accessible list.',
      ),
      node(
        'pages',
        'Permanent detail pages',
        'output',
        88,
        37,
        '为每个资源生成固定 URL、分类、来源和生命周期命令。',
        'Generates a permanent URL, classification, source, and lifecycle commands for every resource.',
      ),
      node(
        'packages',
        'Package index',
        'process',
        73,
        61,
        '把每条目录记录映射为 A3S component ID 和 package contract。',
        'Maps every catalog record to an A3S component ID and package contract.',
      ),
      node(
        'tuf',
        'TUF registry builder',
        'security',
        85,
        76,
        '生成 root、timestamp、snapshot、targets metadata 和归档。',
        'Builds root, timestamp, snapshot, targets metadata, and archives.',
      ),
      node(
        'install',
        'a3s install use/a3s/*',
        'output',
        94,
        58,
        '通过 A3S Use 安装、升级或卸载已签名资源包。',
        'Installs, upgrades, or removes signed resource packages through A3S Use.',
      ),
    ],
    edges: [
      edge('native', 'normalize', 'data', 'native records', 'native records'),
      edge(
        'ecosystem',
        'normalize',
        'data',
        'curated records',
        'curated records',
      ),
      edge(
        'software',
        'normalize',
        'data',
        'filtered metadata',
        'filtered metadata',
      ),
      edge('fields', 'normalize', 'data', 'discipline IDs', 'discipline IDs'),
      edge(
        'capabilities',
        'normalize',
        'data',
        'capability IDs',
        'capability IDs',
      ),
      edge(
        'normalize',
        'catalog',
        'data',
        'normalized resources',
        'normalized resources',
      ),
      edge('catalog', 'atlas', 'data', 'graph data', 'graph data'),
      edge(
        'atlas',
        'pages',
        'data',
        'resource selection',
        'resource selection',
      ),
      edge(
        'catalog',
        'packages',
        'data',
        'one package per resource',
        'one package per resource',
      ),
      edge('packages', 'tuf', 'call', 'portable archives', 'portable archives'),
      edge('tuf', 'install', 'data', 'signed targets', 'signed targets'),
      edge(
        'pages',
        'install',
        'control',
        'lifecycle command',
        'lifecycle command',
      ),
    ],
  },
  {
    id: 'docs',
    name: 'Documentation',
    category: 'products',
    role: localized(
      '静态 Next.js 站点：App Router 组合首页、双语文档、教程和博客，构建时生成版本导航并发布到 GitHub Pages。',
      'A static Next.js site: App Router combines the homepage, bilingual docs, tutorials, and blog, builds version navigation, and publishes to GitHub Pages.',
    ),
    href: 'https://github.com/A3S-Lab/a3s/tree/main/apps/docs',
    evidence: [
      {
        label: 'Documentation app architecture',
        href: 'https://github.com/A3S-Lab/a3s/blob/main/apps/docs/README.md#architecture',
      },
    ],
    groups: [
      group('routing', '路由与页面', 'Routing and pages', 2, 7, 29, 86),
      group('content', '内容系统', 'Content system', 34, 7, 34, 86),
      group('publish', '构建与发布', 'Build and publish', 71, 7, 27, 86),
    ],
    nodes: [
      node(
        'router',
        'Next.js App Router',
        'entry',
        11,
        24,
        '提供首页、docs、tutorials、blog 和 metadata 路由。',
        'Provides homepage, docs, tutorials, blog, and metadata routes.',
      ),
      node(
        'locale',
        'Locale router',
        'process',
        24,
        24,
        '统一中文默认路径、/en 前缀、canonical 和语言切换。',
        'Owns default Chinese paths, /en prefixes, canonicals, and language switching.',
      ),
      node(
        'home',
        'Home components',
        'entry',
        18,
        68,
        '把文案、交互、架构数据和 CSS token 分开维护。',
        'Keeps copy, interactions, architecture data, and CSS tokens separate.',
      ),
      node(
        'fumadocs',
        'Fumadocs loader',
        'service',
        41,
        24,
        '加载 MDX 页面树、导航元数据和全文内容。',
        'Loads MDX page trees, navigation metadata, and full content.',
      ),
      node(
        'content',
        'Docs / tutorials / blog',
        'store',
        54,
        52,
        '按语言和产品保存内容目录。',
        'Stores content by language and product.',
      ),
      node(
        'versions',
        'Version discovery',
        'process',
        41,
        78,
        '从 product-local vX.Y.Z 目录生成版本选择器。',
        'Builds version selectors from product-local vX.Y.Z directories.',
      ),
      node(
        'render',
        'Static Next build',
        'process',
        75,
        27,
        '为中文、英文和兼容路由生成完整 out/。',
        'Generates the complete out/ tree for Chinese, English, and compatibility routes.',
      ),
      node(
        'checks',
        'Tests + site validator',
        'security',
        75,
        68,
        '检查类型、数据、双语首页和最终静态资源。',
        'Checks types, data, bilingual homepages, and final static assets.',
      ),
      node(
        'actions',
        'GitHub Actions',
        'service',
        89,
        40,
        '在 main 上构建并上传 Pages artifact。',
        'Builds on main and uploads the Pages artifact.',
      ),
      node(
        'pages',
        'GitHub Pages',
        'output',
        90,
        76,
        '托管生成的静态 out/ 目录。',
        'Hosts the generated static out/ directory.',
      ),
    ],
    edges: [
      edge('router', 'locale', 'call', '请求路径', 'request path'),
      edge('locale', 'home', 'control', '首页语言', 'homepage locale'),
      edge('locale', 'fumadocs', 'control', '内容语言', 'content locale'),
      edge('fumadocs', 'content', 'data', 'MDX tree', 'MDX tree', true),
      edge('versions', 'content', 'data', 'vX.Y.Z 目录', 'vX.Y.Z directories'),
      edge('home', 'render', 'data', 'React 页面', 'React pages'),
      edge('fumadocs', 'render', 'data', '文档页面', 'documentation pages'),
      edge('versions', 'render', 'data', '版本导航', 'version navigation'),
      edge('render', 'checks', 'data', 'out/', 'out/'),
      edge('checks', 'actions', 'control', '通过发布门', 'release gate passed'),
      edge('actions', 'pages', 'data', 'Pages artifact', 'Pages artifact'),
    ],
  },
];
