import {
  architectureEdge as edge,
  architectureGroup as group,
  architectureNode as node,
  localized,
  type ArchitectureProject,
} from './architecture-types';

export const productExecutionArchitectures: readonly ArchitectureProject[] = [
  {
    id: 'bench',
    name: 'Bench',
    category: 'products',
    role: localized(
      '可复现评测流水线：先冻结 Task 与 Candidate，再分别运行 Candidate 和 Task 自带的 Judge，最后保存可核对的结果。',
      'A reproducible evaluation pipeline: freeze the Task and Candidate, run the Candidate and the Task-owned Judge separately, then store a verifiable result.',
    ),
    href: 'https://github.com/A3S-Lab/Bench',
    evidence: [
      {
        label: 'Bench design',
        href: 'https://github.com/A3S-Lab/Bench/blob/main/docs/design.md#9-architecture',
      },
    ],
    groups: [
      group('assets', '不可变输入', 'Immutable inputs', 2, 7, 26, 86),
      group('control', '持久编排', 'Durable orchestration', 31, 7, 35, 86),
      group('execution', '执行与判分', 'Execution and judging', 69, 7, 29, 86),
    ],
    nodes: [
      node(
        'control',
        'Bench control component',
        'entry',
        8,
        48,
        'CLI 调用的应用层入口；不实现另一套队列。',
        'Application entrypoint used by the CLI; it does not implement a second queue.',
      ),
      node(
        'task',
        'Task → TaskLock',
        'store',
        21,
        20,
        '冻结题目、资源、Judge 契约和版本身份。',
        'Freezes the task, assets, Judge contract, and version identity.',
      ),
      node(
        'candidate',
        'Candidate → CandidateLock',
        'store',
        21,
        48,
        '冻结 Candidate adapter、控制器、模型和来源。',
        'Freezes the Candidate adapter, controller, model, and source.',
      ),
      node(
        'resolver',
        'Asset resolver',
        'adapter',
        21,
        76,
        '从本地目录、内置资产或 digest-pinned OCI 解析输入。',
        'Resolves inputs from local directories, built-ins, or digest-pinned OCI.',
      ),
      node(
        'flow',
        'Embedded A3S Flow',
        'process',
        42,
        24,
        '持久化步骤、等待、重试和重启后的继续执行。',
        'Persists steps, waits, retries, and restart-safe continuation.',
      ),
      node(
        'store',
        'BenchStore + outbox',
        'store',
        43,
        72,
        '保存 Experiment、Trial、lock、结果、分数和 disposition。',
        'Stores Experiments, Trials, locks, results, scores, and disposition.',
      ),
      node(
        'runtime',
        'A3sRuntimeClient',
        'adapter',
        60,
        45,
        '向 Runtime 提交两个独立执行，并按 handle 重连。',
        'Submits two separate executions to Runtime and reattaches by handle.',
      ),
      node(
        'candidate-run',
        'Candidate execution',
        'runtime',
        75,
        18,
        '在隔离运行时中执行 Candidate。',
        'Runs the Candidate in an isolated runtime.',
      ),
      node(
        'snapshot',
        'SubmissionSnapshot',
        'store',
        75,
        47,
        '从 Candidate 的终态 checkpoint 导出只读提交快照。',
        'Derives a read-only submission snapshot from the Candidate terminal checkpoint.',
      ),
      node(
        'judge-run',
        'Task-owned Judge',
        'runtime',
        75,
        77,
        'Judge 读取提交快照并产生规定格式的 JudgeResult。',
        'The Judge reads the submission snapshot and emits the required JudgeResult.',
      ),
      node(
        'artifacts',
        'ArtifactStore',
        'store',
        91,
        25,
        '保存输入锁、checkpoint、submission 和运行证据。',
        'Stores input locks, checkpoints, submissions, and runtime evidence.',
      ),
      node(
        'report',
        'Score + report',
        'output',
        91,
        70,
        '校验 JudgeResult 后确定分数、状态和报告。',
        'Validates JudgeResult before committing the score, status, and report.',
      ),
    ],
    edges: [
      edge('control', 'resolver', 'call', '解析输入', 'resolve inputs'),
      edge('resolver', 'task', 'data', 'TaskLock', 'TaskLock'),
      edge('resolver', 'candidate', 'data', 'CandidateLock', 'CandidateLock'),
      edge('task', 'flow', 'data', '实验定义', 'experiment definition'),
      edge('candidate', 'flow', 'data', '候选定义', 'candidate definition'),
      edge('flow', 'store', 'event', '运行状态', 'run state'),
      edge(
        'flow',
        'runtime',
        'call',
        '稳定 operation ID',
        'stable operation ID',
      ),
      edge(
        'runtime',
        'candidate-run',
        'call',
        'Candidate spec',
        'Candidate spec',
      ),
      edge(
        'candidate-run',
        'snapshot',
        'data',
        'terminal checkpoint',
        'terminal checkpoint',
      ),
      edge('snapshot', 'judge-run', 'data', '只读提交', 'read-only submission'),
      edge('runtime', 'judge-run', 'call', 'Judge spec', 'Judge spec'),
      edge(
        'candidate-run',
        'artifacts',
        'data',
        '运行证据',
        'runtime evidence',
      ),
      edge('judge-run', 'report', 'data', 'JudgeResult', 'JudgeResult'),
      edge('report', 'store', 'data', '结果与分数', 'result and score'),
      edge('artifacts', 'report', 'data', '证据引用', 'evidence refs'),
    ],
  },
  {
    id: 'test',
    name: 'Test',
    category: 'products',
    role: localized(
      '两条 E2E 路径共用同一 SurfaceDriver：CLI 执行经过准入的确定性 TestSuite；SDK host 运行受 schema、能力、来源和预算约束的 LLM action loop。Web 已可用，GUI 与 TUI 仍在规划中。',
      'Two E2E paths share one SurfaceDriver: the CLI runs admitted deterministic TestSuites, while an SDK host runs an LLM action loop bounded by schema, capabilities, origins, and budgets. Web works today; GUI and TUI remain planned.',
    ),
    href: 'https://github.com/A3S-Lab/Test',
    evidence: [
      {
        label: 'Test architecture',
        href: 'https://github.com/A3S-Lab/Test/blob/main/docs/architecture.md',
      },
      {
        label: 'Agentic SDK contract',
        href: 'https://github.com/A3S-Lab/Test/blob/main/docs/agentic.md',
      },
    ],
    groups: [
      group('input', '规范与准入', 'Specification and admission', 2, 7, 20, 86),
      group('runner', '确定性与 Agent 编排', 'Deterministic and agentic orchestration', 25, 7, 41, 86),
      group('surfaces', 'Surface 与证据', 'Surfaces and evidence', 69, 7, 29, 86),
    ],
    nodes: [
      node(
        'agent',
        'Agent / CI / SDK host',
        'entry',
        9,
        18,
        '提交 ACL 场景，或向 library AgentLoop 提供目标、真实 LLM 和策略对象。',
        'Submits ACL scenarios or supplies a goal, real LLM, and policy object to the library AgentLoop.',
      ),
      node(
        'cli',
        'a3s-test CLI + JSON',
        'entry',
        9,
        48,
        '提供 check、run、稳定 JSON 字段和进程退出码。',
        'Provides check, run, stable JSON fields, and process exit codes.',
      ),
      node(
        'admission',
        'ACL admission',
        'security',
        9,
        80,
        '在启动 surface 前拒绝未知字段、歧义条件和无效 locator。',
        'Rejects unknown fields, ambiguous conditions, and invalid locators before a surface starts.',
      ),
      node(
        'ir',
        'TestSuite typed IR',
        'store',
        29,
        24,
        '保存 Suite、Scenario、Step、Action 与显式 surface。',
        'Stores suites, scenarios, steps, actions, and an explicit surface.',
      ),
      node(
        'agent-loop',
        'Schema-constrained AgentLoop',
        'process',
        29,
        51,
        '按 observe、decide、policy、act 循环，并在明确预算或终态停止。',
        'Runs observe, decide, policy, and act, then stops at explicit budgets or a terminal decision.',
      ),
      node(
        'llm',
        'Injected LlmProvider',
        'service',
        43,
        18,
        '接收版本化指令、typed context 和 AgentDecision JSON Schema。',
        'Receives versioned instructions, typed context, and the AgentDecision JSON Schema.',
      ),
      node(
        'runner',
        'Cancellation-safe Runner',
        'process',
        43,
        48,
        '逐场景打开 session、执行步骤、聚合状态并关闭 driver。',
        'Opens a session per scenario, executes steps, aggregates status, and closes the driver.',
      ),
      node(
        'policy',
        'ActionPolicy + budgets',
        'security',
        43,
        80,
        '在执行前校验 action kind、navigation origin、turn、token、cost、context 和时间。',
        'Checks action kind, navigation origin, turns, tokens, cost, context, and time before execution.',
      ),
      node(
        'lifecycle',
        'Lifecycle + cancellation',
        'control',
        29,
        80,
        '统一 deadline、取消、清理期限、首次 SIGINT 和二次 SIGINT。',
        'Unifies deadlines, cancellation, cleanup bounds, first SIGINT, and second SIGINT.',
      ),
      node(
        'registry',
        'Driver registry',
        'service',
        57,
        20,
        '按 Surface 注册类型化 driver object，不用后端名称分支。',
        'Registers typed driver objects by Surface without backend-name branching.',
      ),
      node(
        'contract',
        'SurfaceDriver / Session',
        'adapter',
        57,
        57,
        '统一 open、observe、execute 和 close，并让每个 scenario 独占 session。',
        'Unifies open, observe, execute, and close while each scenario owns its session.',
      ),
      node(
        'web-driver',
        'Web Driver',
        'runtime',
        76,
        18,
        '把类型化 Action 映射到现有浏览器协议；当前已实现。',
        'Maps typed Actions onto the existing browser protocol; implemented today.',
      ),
      node(
        'gui-driver',
        'GUI Driver (planned)',
        'adapter',
        76,
        50,
        '计划适配 A3S CUA 的可访问性树、窗口和指针能力。',
        'Planned adapter for A3S CUA accessibility, window, and pointer capabilities.',
      ),
      node(
        'tui-driver',
        'TUI Driver (planned)',
        'adapter',
        76,
        82,
        '计划管理 PTY、语义终端状态、按键和录制。',
        'Planned owner of PTY lifecycle, semantic terminal state, keys, and recordings.',
      ),
      node(
        'browser',
        'A3S Browser / agent-browser',
        'runtime',
        92,
        18,
        '通过 a3s use browser 或兼容独立命令执行 Web 操作。',
        'Executes Web operations through a3s use browser or a compatible standalone command.',
      ),
      node(
        'containment',
        'Process groups + namespace',
        'security',
        92,
        54,
        '隔离每次 run 的 browser namespace，并只终止自己拥有的进程树。',
        'Isolates each run namespace and terminates only process trees it owns.',
      ),
      node(
        'report',
        'Evidence + structured report',
        'output',
        92,
        86,
        '保存确定性结果或 Agent turn trace，并区分断言、策略、预算、基础设施和清理失败。',
        'Stores deterministic results or agent turn traces and separates assertion, policy, budget, infrastructure, and cleanup failures.',
      ),
    ],
    edges: [
      edge('agent', 'cli', 'call', 'check / run', 'check / run'),
      edge('cli', 'admission', 'data', 'ACL manifest', 'ACL manifest'),
      edge('admission', 'ir', 'data', 'validated suite', 'validated suite'),
      edge('ir', 'runner', 'data', 'scenario sequence', 'scenario sequence'),
      edge('agent', 'agent-loop', 'call', 'goal + SDK host', 'goal + SDK host'),
      edge('agent-loop', 'llm', 'call', 'schema + context', 'schema + context', true),
      edge('policy', 'agent-loop', 'control', 'typed action gate', 'typed action gate'),
      edge('lifecycle', 'agent-loop', 'control', 'cancel / timeout', 'cancel / timeout'),
      edge('lifecycle', 'runner', 'control', 'deadline / SIGINT', 'deadline / SIGINT'),
      edge('runner', 'registry', 'call', 'Surface', 'Surface'),
      edge('registry', 'contract', 'call', 'typed driver', 'typed driver'),
      edge('agent-loop', 'contract', 'call', 'observe / execute', 'observe / execute'),
      edge('contract', 'web-driver', 'control', 'Web', 'Web'),
      edge('contract', 'gui-driver', 'optional', 'GUI（规划）', 'GUI (planned)'),
      edge('contract', 'tui-driver', 'optional', 'TUI（规划）', 'TUI (planned)'),
      edge('web-driver', 'browser', 'call', 'typed browser command', 'typed browser command'),
      edge('web-driver', 'containment', 'control', 'owned command group', 'owned command group'),
      edge('browser', 'containment', 'control', 'private session PID', 'private session PID'),
      edge('gui-driver', 'containment', 'optional', 'owned app tree', 'owned app tree'),
      edge('tui-driver', 'containment', 'optional', 'owned PTY tree', 'owned PTY tree'),
      edge('web-driver', 'report', 'data', 'step output', 'step output'),
      edge('runner', 'report', 'data', 'RunResult', 'RunResult'),
      edge('agent-loop', 'report', 'data', 'turn trace + usage', 'turn trace + usage'),
      edge('containment', 'report', 'event', 'cleanup outcome', 'cleanup outcome'),
    ],
  },
  {
    id: 'cloud',
    name: 'Cloud',
    category: 'products',
    role: localized(
      '自托管控制平面：Boot API 和 DDD 模块保存期望状态，Node Agent 通过 outbound mTLS 驱动 Runtime、Box、Power 与 Gateway。',
      'A self-hosted control plane: Boot APIs and DDD modules store desired state while outbound-mTLS node agents drive Runtime, Box, Power, and Gateway.',
    ),
    href: '/docs/cloud',
    evidence: [
      {
        label: 'Cloud technical architecture',
        href: 'https://github.com/A3S-Lab/Cloud/blob/main/docs/architecture.md',
      },
    ],
    groups: [
      group('clients', '客户端', 'Clients', 2, 9, 15, 82),
      group('control', '控制平面', 'Control plane', 20, 9, 48, 82),
      group('node', '节点数据面', 'Node data plane', 71, 9, 27, 82),
    ],
    nodes: [
      node(
        'clients',
        'Web / API / CLI',
        'entry',
        9,
        50,
        'React console、Cloud client 和 CLI 使用同一租户 API。',
        'The React console, Cloud client, and CLI use the same tenant API.',
      ),
      node(
        'api',
        'A3S Boot API',
        'service',
        25,
        50,
        '负责认证、路由、CQRS、OpenAPI 和模块生命周期。',
        'Owns authentication, routing, CQRS, OpenAPI, and module lifecycle.',
      ),
      node(
        'modules',
        'DDD modules',
        'process',
        40,
        50,
        '处理 Sources、Artifacts、Deployments、Nodes、Secrets、Edges 等业务。',
        'Handles Sources, Artifacts, Deployments, Nodes, Secrets, Edges, and related domains.',
      ),
      node(
        'postgres',
        'PostgreSQL',
        'store',
        40,
        82,
        '保存业务期望状态、操作、outbox 和租户边界。',
        'Stores business desired state, operations, outbox, and tenant boundaries.',
      ),
      node(
        'worker',
        'Flow worker + reconcilers',
        'process',
        54,
        18,
        '推进构建、部署、更新、证书和清理操作。',
        'Advances build, deploy, update, certificate, and cleanup operations.',
      ),
      node(
        'flow-store',
        'A3S Flow store',
        'store',
        54,
        41,
        '保存长操作的事件历史和下一步。',
        'Stores long-operation history and the next durable step.',
      ),
      node(
        'outbox',
        'Outbox relay',
        'service',
        52,
        66,
        '读取已提交 outbox，并发布领域事件。',
        'Reads committed outbox rows and publishes domain events.',
      ),
      node(
        'event',
        'A3S Event',
        'service',
        65,
        66,
        '向内部消费者分发已提交事件。',
        'Distributes committed events to internal consumers.',
      ),
      node(
        'objects',
        'Registry + object storage',
        'store',
        62,
        84,
        '保存 OCI 图、构建证据、日志块和不可变工件。',
        'Stores OCI graphs, build evidence, log chunks, and immutable artifacts.',
      ),
      node(
        'agent',
        'Node Agent',
        'adapter',
        75,
        30,
        '通过 outbound mTLS long poll 领取命令并提交回执。',
        'Receives commands by outbound-mTLS long poll and submits receipts.',
      ),
      node(
        'runtime',
        'A3S Runtime',
        'service',
        84,
        14,
        '管理 Task 和 Service 的 provider-neutral 生命周期。',
        'Manages provider-neutral Task and Service lifecycle.',
      ),
      node(
        'box',
        'A3S Box',
        'runtime',
        94,
        30,
        'Cloud 唯一的本地执行和镜像构建 provider。',
        'Cloud’s sole local execution and image-build provider.',
      ),
      node(
        'power',
        'Power Service',
        'runtime',
        85,
        46,
        '作为 Box 承载的 Runtime Service 提供本地推理。',
        'Provides local inference as a Box-hosted Runtime Service.',
      ),
      node(
        'gateway',
        'A3S Gateway',
        'runtime',
        82,
        69,
        '接收完整配置快照并执行路由切换。',
        'Receives complete configuration snapshots and performs route cutover.',
      ),
      node(
        'workload',
        'Healthy workload',
        'output',
        94,
        82,
        '运行已验证的服务 revision，并由 Gateway 转发流量。',
        'Runs a verified service revision behind Gateway traffic.',
      ),
    ],
    edges: [
      edge('clients', 'api', 'call', '租户 API', 'tenant API'),
      edge('api', 'modules', 'call', 'command / query', 'command / query'),
      edge('modules', 'postgres', 'data', '事务', 'transactions', true),
      edge('modules', 'worker', 'control', '持久操作', 'durable operations'),
      edge(
        'worker',
        'flow-store',
        'event',
        '工作流历史',
        'workflow history',
        true,
      ),
      edge('modules', 'outbox', 'data', '已提交 outbox', 'committed outbox'),
      edge('outbox', 'event', 'event', '领域事件', 'domain events'),
      edge(
        'modules',
        'objects',
        'data',
        '内容寻址工件',
        'content-addressed artifacts',
        true,
      ),
      edge('agent', 'api', 'control', 'outbound mTLS', 'outbound mTLS', true),
      edge('worker', 'agent', 'control', '节点命令', 'node command'),
      edge(
        'agent',
        'runtime',
        'call',
        'apply / inspect / logs',
        'apply / inspect / logs',
      ),
      edge('runtime', 'box', 'call', 'Box provider', 'Box provider'),
      edge('box', 'power', 'call', 'Service', 'Service'),
      edge('agent', 'gateway', 'control', '配置快照', 'configuration snapshot'),
      edge(
        'runtime',
        'workload',
        'control',
        'Service lifecycle',
        'Service lifecycle',
      ),
      edge('gateway', 'workload', 'call', '路由流量', 'route traffic'),
    ],
  },
];
