import { architectureNode as node, localized, type ArchitectureProject } from './architecture-types';
import { getProjectPrimaryHref } from '../project-links';

export const productArchitectureProjects: readonly ArchitectureProject[] = [
  {
    id: 'cli',
    name: 'CLI',
    category: 'products',
    role: localized('安装和管理 A3S 组件，并提供 Code 终端和本地 Web API。', 'Installs and manages A3S components, with the Code terminal and a local Web API.'),
    href: getProjectPrimaryHref('cli'),
    nodes: [
      node('entry', 'a3s CLI', 'surface', '解析统一命令，并把产品选择留在用户可见的入口。', 'Parses the umbrella command while keeping product selection visible at the entrypoint.'),
      node('policy', 'Host Policy', 'core', '拥有账户、模型、权限、工作区与展示策略。', 'Owns account, model, permission, workspace, and presentation policy.'),
      node('code', 'Code Runtime', 'contract', '通过稳定运行时契约启动并恢复 Agent 会话。', 'Starts and resumes agent sessions through stable runtime contracts.'),
      node('components', 'Components', 'runtime', '发现、安装并管理 Box、Use 等独立组件。', 'Discovers, installs, and manages independent components such as Box and Use.'),
      node('surfaces', 'TUI / Web API', 'evidence', '把会话、活动与组件状态投影到终端和本地接口。', 'Projects sessions, activity, and component state into terminal and local API surfaces.'),
    ],
  },
  {
    id: 'code',
    name: 'Code',
    category: 'products',
    role: localized('用于构建 Agent 的异步运行时，提供 Rust、Node.js、Python 和 Go SDK。', 'An async agent runtime with Rust, Node.js, Python, and Go SDKs.'),
    href: getProjectPrimaryHref('code'),
    nodes: [
      node('hosts', 'Hosts & SDKs', 'surface', '终端、Rust、Node.js、Python 与 Go 共享同一核心。', 'Terminal, Rust, Node.js, Python, and Go share the same core.'),
      node('agent', 'Agent', 'core', '组合模型、指令、工具与宿主提供的治理策略。', 'Composes models, instructions, tools, and host-supplied governance.'),
      node('session', 'AgentSession', 'contract', '拥有有序事件、运行、恢复和生命周期语义。', 'Owns ordered events, runs, recovery, and lifecycle semantics.'),
      node('extensions', 'Extension Contracts', 'runtime', '通过类型化 Provider、Store、Tool、Hook 与 MCP 扩展。', 'Extends through typed providers, stores, tools, hooks, and MCP.'),
      node('evidence', 'Evidence & State', 'evidence', '持久化 trace、artifact、snapshot 与可选状态图。', 'Persists traces, artifacts, snapshots, and the optional state graph.'),
    ],
  },
  {
    id: 'web',
    name: 'Web',
    category: 'products',
    role: localized('把任务、文件、知识库和 Office 工具放在一个本地工作台里。', 'A local workspace for tasks, files, knowledge, Office tools, and research.'),
    href: getProjectPrimaryHref('web'),
    nodes: [
      node('work', 'Work Surface', 'surface', '用一个任务入口承载代码、文件、Office 与扩展场景。', 'Uses one task entrypoint for code, files, Office, and extension scenes.'),
      node('loopback', 'Loopback API', 'core', '只在本机边界内协调浏览器界面与可信宿主能力。', 'Coordinates the browser UI and trusted host capabilities inside the local boundary.'),
      node('tasks', 'Task Runtime', 'contract', '持久化任务、会话、提案与审批状态。', 'Persists tasks, sessions, proposals, and approval state.'),
      node('files', 'Files & Office', 'runtime', '提供真实文件系统、代码编辑器与原生文档编辑路径。', 'Provides real filesystem, code editor, and native document editing paths.'),
      node('knowledge', 'Knowledge & Packages', 'evidence', '编译本地知识并投影经过审查的 Use 包能力。', 'Compiles local knowledge and projects reviewed Use package capabilities.'),
    ],
  },
  {
    id: 'windhole',
    name: 'Windhole',
    category: 'products',
    role: localized('在本地运行 A3S Bench 评测，并查看过程和结果。', 'Runs A3S Bench evaluations locally and shows each run and result.'),
    href: getProjectPrimaryHref('windhole'),
    nodes: [
      node('catalog', 'Bench Catalog', 'surface', '读取真实 Task、Candidate 与运行时诊断。', 'Reads real Tasks, Candidates, and runtime diagnostics.'),
      node('roster', 'Hangar Roster', 'core', '把机体、Pilot、模型和 effort 固化为部署快照。', 'Freezes aircraft, pilot, model, and effort into a deployment snapshot.'),
      node('bridge', 'Loopback Bridge', 'contract', '验证本地来源与参数，并且从不让浏览器直接启动进程。', 'Validates local origins and arguments without letting the browser spawn processes.'),
      node('run', 'Bench Process', 'runtime', '以 shell-free 参数调用真实 a3s-bench 运行。', 'Invokes real a3s-bench runs with shell-free arguments.'),
      node('report', 'Battle Report', 'evidence', '用权威 Run ID、进度和结果驱动 3D 状态。', 'Drives the 3D state from authoritative run IDs, progress, and results.'),
    ],
  },
  {
    id: 'box',
    name: 'Box',
    category: 'products',
    role: localized('用 MicroVM 运行 OCI 容器，命令体验接近 Docker。', 'Runs OCI containers in MicroVMs with a Docker-like command line.'),
    href: getProjectPrimaryHref('box'),
    nodes: [
      node('entry', 'Entry Points', 'surface', 'CLI、SDK、CRI 与 containerd shim 提交同一种本地请求。', 'CLI, SDKs, CRI, and the containerd shim submit one local request shape.'),
      node('manager', 'ExecutionManager', 'core', '拥有生命周期、持久状态与 generation fencing。', 'Owns lifecycle, durable state, and generation fencing.'),
      node('resolver', 'Policy Resolver', 'contract', '在分配前探测能力并显式解析隔离策略。', 'Probes capabilities and resolves explicit isolation policy before allocation.'),
      node('backends', 'Runtime Backends', 'runtime', '选择 libkrun MicroVM 或显式共享内核 Sandbox。', 'Selects the libkrun MicroVM or an explicit shared-kernel Sandbox.'),
      node('state', 'State & Telemetry', 'evidence', '统一镜像、网络、快照、日志、审计、指标与 TEE 证据。', 'Unifies images, networks, snapshots, logs, audit, metrics, and TEE evidence.'),
    ],
  },
  {
    id: 'bench',
    name: 'Bench',
    category: 'products',
    role: localized('用固定输入和评审规则重复运行 Agent 评测。', 'Runs repeatable agent evaluations from fixed inputs and judge rules.'),
    href: getProjectPrimaryHref('bench'),
    nodes: [
      node('sources', 'Task + Candidate', 'surface', '接纳明确来源、资产和 Judge 契约。', 'Admits explicit sources, assets, and Judge contracts.'),
      node('locks', 'Immutable Locks', 'core', '把可变输入解析为内容寻址的 TaskLock 与 CandidateLock。', 'Resolves mutable inputs into content-addressed TaskLock and CandidateLock values.'),
      node('runtime', 'Runtime Provider', 'contract', '按显式配置选择 Docker、OS Runtime 或诊断中的 Box。', 'Selects Docker, OS Runtime, or diagnostic Box paths through explicit policy.'),
      node('submission', 'Submission Snapshot', 'runtime', '隔离执行并封存候选输出与运行证据。', 'Executes in isolation and seals candidate output with runtime evidence.'),
      node('result', 'Judge Result', 'evidence', '将完整 Judge 结果绑定到两份输入锁与 Run ID。', 'Binds the complete Judge result to both input locks and the run ID.'),
    ],
  },
  {
    id: 'search',
    name: 'Search',
    category: 'products',
    role: localized('同时搜索多个来源，完成排序、去重和网页渲染。', 'Searches multiple sources, ranks and deduplicates results, and can render pages.'),
    href: getProjectPrimaryHref('search'),
    nodes: [
      node('providers', 'Providers & Engines', 'surface', '接入类型化 API Provider 与传统 HTTP/RSS 引擎。', 'Accepts typed API providers and conventional HTTP/RSS engines.'),
      node('adapter', 'ProviderEngine', 'core', '把丰富 Provider 输出适配到稳定 Engine 契约。', 'Adapts rich provider output into the stable Engine contract.'),
      node('search', 'Search Orchestrator', 'contract', '并发执行、超时、熔断并保留部分失败。', 'Owns parallel execution, timeouts, circuit state, and partial failures.'),
      node('aggregate', 'Aggregator', 'runtime', '归一化 URL、合并、去重并执行共识排序。', 'Normalizes URLs, merges, deduplicates, and applies consensus ranking.'),
      node('results', 'Results & Evidence', 'evidence', '返回带来源、Provider 结果与失败边界的统一结果。', 'Returns unified results with provenance, provider output, and failure boundaries.'),
    ],
  },
  {
    id: 'browser',
    name: 'Browser',
    category: 'products',
    role: localized('为 Agent 提供隔离运行的浏览器自动化。', 'Runs browser automation for agents in an isolated process.'),
    href: getProjectPrimaryHref('browser'),
    nodes: [
      node('caller', 'SDK Caller', 'surface', 'Search 与嵌入式宿主只依赖对象安全接口。', 'Search and embedded hosts depend only on the object-safe interface.'),
      node('renderer', 'PageRenderer', 'core', '承载类型化渲染请求、结果与会话原语。', 'Carries typed render requests, results, and session primitives.'),
      node('library', 'Typed Library', 'contract', '管理浏览器发现、Provider 选择与有界缓存。', 'Manages browser discovery, provider selection, and bounded cache behavior.'),
      node('driver', 'Isolated Driver', 'runtime', '在独立进程中拥有 CLI、MCP 与高级自动化状态。', 'Owns CLI, MCP, and advanced automation state in a separate process.'),
      node('assets', 'Browser + Skills', 'evidence', '组合真实浏览器、Skills 与静态 Dashboard。', 'Combines the real browser, Skills, and static Dashboard.'),
    ],
  },
  {
    id: 'ocr',
    name: 'OCR',
    category: 'products',
    role: localized('从图片中提取文字，并保留来源与模型信息。', 'Extracts text from images while recording the source and model used.'),
    href: getProjectPrimaryHref('ocr'),
    nodes: [
      node('image', 'Bounded Image', 'surface', '规范化本地路径、媒体类型、大小和 SHA-256。', 'Canonicalizes local path, media type, size, and SHA-256.'),
      node('client', 'Evidence Envelope', 'core', 'OcrClient 在识别前后都拥有来源证据边界。', 'OcrClient owns the source evidence boundary before and after recognition.'),
      node('provider', 'OcrProvider', 'contract', '用类型化对象选择本地或显式远程 Provider。', 'Selects local or explicit remote providers through typed objects.'),
      node('pipeline', 'Recognition Pipeline', 'runtime', 'PP-OCRv6 执行检测、排序、裁剪、识别与 CTC 解码。', 'PP-OCRv6 performs detection, ordering, crops, recognition, and CTC decoding.'),
      node('result', 'OcrResult', 'evidence', '将文本、可选几何与模型身份绑定回原始来源。', 'Binds text, optional geometry, and model identity back to the original source.'),
    ],
  },
  {
    id: 'use',
    name: 'Use',
    category: 'products',
    role: localized('安装、校验和管理 Agent 能力包，并提供 Browser 与 OCR 内置路由。', 'Installs, verifies, and manages agent capability packages, with built-in Browser and OCR routes.'),
    href: getProjectPrimaryHref('use'),
    nodes: [
      node('cli', 'Umbrella CLI', 'surface', '通过 a3s use 暴露一致的领域入口。', 'Exposes a consistent domain entrypoint through a3s use.'),
      node('host', 'Use Host', 'core', '拥有 catalog、source、receipt、route lease 与生命周期。', 'Owns catalog, sources, receipts, route leases, and lifecycle.'),
      node('builtin', 'Built-in Routes', 'contract', '用各自原生契约连接 Browser、OCR 与 Box。', 'Connects Browser, OCR, and Box through their native contracts.'),
      node('registry', 'Extension Registry', 'runtime', '原子发布 Office、Science 等 CLI/MCP/Skill 包快照。', 'Atomically publishes CLI/MCP/Skill package snapshots for Office, Science, and more.'),
      node('snapshot', 'Capability Snapshot', 'evidence', '向 Code 提供只读、可 watch 的能力投影。', 'Provides Code with a read-only, watchable capability projection.'),
    ],
  },
  {
    id: 'office',
    name: 'Office',
    category: 'products',
    role: localized('读取、编辑和生成 Office 文件，支持 CLI、MCP 和 Skill。', 'Reads, edits, and creates Office files through the CLI, MCP, and Skill.'),
    href: getProjectPrimaryHref('office'),
    nodes: [
      node('host', 'Host Product', 'surface', '由 Web、独立 Playground 或自动化宿主提供产品策略。', 'Receives product policy from Web, the standalone Playground, or automation hosts.'),
      node('contracts', 'Typed Contracts', 'core', '编辑与自动化平面共享有界内容模型和操作契约。', 'Editing and automation planes share bounded content models and operation contracts.'),
      node('browser', 'Browser Plane', 'contract', '组合编辑器、Worker、WASM 与 PDFium。', 'Combines editors, workers, WebAssembly, and PDFium.'),
      node('native', 'Native Rust Plane', 'runtime', '用独立 Rust 核心处理文件系统与 OOXML package。', 'Handles filesystem and OOXML package concerns in a separate Rust core.'),
      node('artifacts', 'OOXML / PDF', 'evidence', '导入、验证、修改并导出可追踪的文档工件。', 'Imports, validates, modifies, and exports traceable document artifacts.'),
    ],
    links: [['host', 'contracts'], ['contracts', 'browser'], ['contracts', 'native'], ['browser', 'artifacts'], ['native', 'artifacts']],
  },
  {
    id: 'science',
    name: 'Science',
    category: 'products',
    role: localized('提供科学研究用的 Skills、数据接口和计算工具。', 'Provides Skills, data services, and compute tools for scientific research.'),
    href: getProjectPrimaryHref('science'),
    nodes: [
      node('hosts', 'Code / Use', 'surface', '从 Agent 或能力门面接收明确的科学任务。', 'Receives explicit scientific tasks from agents or the capability facade.'),
      node('skills', 'Skills & MCP', 'core', '用可审查 Skills 与类型化 MCP 工具描述能力。', 'Describes capabilities with reviewable Skills and typed MCP tools.'),
      node('data', 'Data Services', 'contract', '把外部科学数据源封装在稳定查询边界后。', 'Wraps external scientific data sources behind stable query boundaries.'),
      node('compute', 'Compute Workflows', 'runtime', '执行可复现的分析、模拟与研究计算。', 'Executes reproducible analysis, simulation, and research compute.'),
      node('artifacts', 'Research Evidence', 'evidence', '产出带来源、参数与计算上下文的研究工件。', 'Produces research artifacts with sources, parameters, and compute context.'),
    ],
  },
  {
    id: 'cloud',
    name: 'Cloud',
    category: 'products',
    role: localized('自托管 A3S 控制平面，管理节点、任务和 OCI 部署。', 'A self-hosted control plane for A3S nodes, operations, and OCI deployments.'),
    href: getProjectPrimaryHref('cloud'),
    nodes: [
      node('clients', 'Web / API / CLI', 'surface', '共享经过验证的客户端与租户范围。', 'Shares one validated client and tenant scope across surfaces.'),
      node('api', 'Boot API', 'core', '提供认证、CQRS、OpenAPI、健康与模块生命周期。', 'Provides authentication, CQRS, OpenAPI, health, and module lifecycle.'),
      node('domain', 'DDD + Durable Core', 'contract', '业务模块通过 ORM、Flow、Event 与 outbox 持久化。', 'Persists business modules through ORM, Flow, Event, and the outbox.'),
      node('agent', 'Node Agent', 'runtime', '用 outbound mTLS lease 接收命令并提交可验证回执。', 'Receives commands over outbound mTLS leases and submits verifiable receipts.'),
      node('execution', 'Box / Gateway / Power', 'evidence', '执行工作负载、边缘路由与推理，并返回运行证据。', 'Executes workloads, edge routing, and inference while returning runtime evidence.'),
    ],
  },
  {
    id: 'form',
    name: 'Form',
    category: 'products',
    role: localized('用可视化编辑器设计 AI Native 表单，并编译成可嵌入产物。', 'Designs AI Native forms visually and compiles them into embeddable output.'),
    href: getProjectPrimaryHref('form'),
    nodes: [
      node('designer', 'Form Designer', 'surface', '提供字段目录、结构树、布局拖放、实时预览与撤销重做。', 'Provides a field catalog, structure tree, layout drag and drop, live preview, and undo/redo.'),
      node('document', 'FormDocument', 'core', '用一份版本化文档保存 schema、界面、规则、引用与元数据。', 'Stores schema, UI, rules, references, and metadata in one versioned document.'),
      node('compiler', 'Deterministic Compiler', 'contract', '验证能力与依赖关系，并生成不可变 FormPlan 和规范摘要。', 'Validates capabilities and dependencies, then produces an immutable FormPlan and canonical digest.'),
      node('adapters', 'React / Vue / Web Component', 'runtime', '通过受控值、动作回调与宿主注册表嵌入不同产品。', 'Embeds into products through controlled values, action callbacks, and host registries.'),
      node('evidence', 'Revision + SHA-256', 'evidence', '把 Agent 提交的 FormPatch 绑定到基准版本并保留可核验摘要。', 'Binds agent-authored FormPatch changes to a base revision and verifiable digest.'),
    ],
  },
  {
    id: 'site',
    name: 'Site',
    category: 'products',
    role: localized('A3S 中英文生态项目索引。', 'The bilingual A3S ecosystem project index.'),
    href: getProjectPrimaryHref('site'),
    nodes: [
      node('routes', 'Rspress Routes', 'surface', '提供中文与英文生态首页。', 'Serves the Chinese and English ecosystem homepages.'),
      node('locale', 'Locale Builds', 'core', '分别构建中文根路径与英文 /en 路径。', 'Builds the Chinese root and English /en route separately.'),
      node('content', 'Homepage Content', 'contract', '用类型化内容和 MDX 入口维护两个语言版本。', 'Maintains both locales through typed content and MDX entrypoints.'),
      node('home', 'Ecosystem Index', 'runtime', '展示项目职责、开发阶段、网站预览与仓库入口。', 'Shows project ownership, delivery stages, site previews, and repositories.'),
      node('export', 'Static Build', 'evidence', '检查路由和资源后发布完整静态站点。', 'Checks routes and assets before publishing the complete static site.'),
    ],
  },
];
