import {
  architectureEdge as edge,
  architectureGroup as group,
  architectureNode as node,
  localized,
  type ArchitectureProject,
} from './architecture-types';

export const productApplicationArchitectures: readonly ArchitectureProject[] = [
  {
    id: 'cli',
    name: 'CLI',
    category: 'products',
    role: localized(
      '统一命令入口：解析参数，装配运行上下文，再进入内置命令、Code TUI 或独立子进程。',
      'The umbrella command: parse arguments, build one invocation context, then enter a built-in command, the Code TUI, or a child process.',
    ),
    href: '/docs/cli',
    evidence: [
      {
        label: 'CLI technical architecture',
        href: 'https://github.com/A3S-Lab/CLI/blob/main/docs/cli-technical-architecture.md',
      },
    ],
    groups: [
      group('input', '命令解析', 'Command parsing', 2, 7, 22, 86),
      group('dispatch', '分发与执行', 'Dispatch and execution', 27, 7, 51, 86),
      group('output', '结果输出', 'Result output', 81, 7, 17, 86),
    ],
    nodes: [
      node(
        'argv',
        'argv / env / TTY',
        'entry',
        11,
        24,
        '原始参数、环境变量和终端能力。',
        'Raw arguments, environment, and terminal capabilities.',
      ),
      node(
        'parser',
        'Clap parser',
        'process',
        11,
        65,
        '负责命令、别名、补全、冲突和用法错误。',
        'Owns commands, aliases, completion, conflicts, and usage errors.',
      ),
      node(
        'context',
        'InvocationContext',
        'service',
        34,
        24,
        '一次性解析配置、路径、输出策略、网络策略和取消信号。',
        'Resolves configuration, paths, output policy, network policy, and cancellation once.',
      ),
      node(
        'dispatcher',
        'Typed dispatcher',
        'process',
        49,
        48,
        '把类型化命令交给唯一的处理路径。',
        'Routes each typed command to one handling path.',
      ),
      node(
        'handlers',
        'Root handlers',
        'service',
        66,
        20,
        '处理 auth、config、model、component、web 和 top。',
        'Handles auth, config, model, components, web, and top.',
      ),
      node(
        'code-tui',
        'Code TUI host',
        'runtime',
        66,
        48,
        '在当前进程运行终端应用，并连接 a3s-code-core。',
        'Runs the terminal application in-process and connects a3s-code-core.',
      ),
      node(
        'proxies',
        'Product proxies',
        'adapter',
        66,
        76,
        '用原始 argv 和标准流启动 Box、Bench、Search、Use 等组件。',
        'Starts Box, Bench, Search, Use, and other components with raw argv and stdio.',
      ),
      node(
        'outcome',
        'CommandOutcome',
        'output',
        86,
        34,
        '所有内置处理器返回同一种结果，不自行退出进程。',
        'Every built-in handler returns one result type and never exits the process itself.',
      ),
      node(
        'renderer',
        'Human / JSON / JSONL',
        'output',
        89,
        70,
        '统一写入 stdout、stderr，并确定最终退出码。',
        'Writes stdout and stderr consistently and determines the final exit code.',
      ),
    ],
    edges: [
      edge('argv', 'parser', 'data', '命令行输入', 'command input'),
      edge('parser', 'context', 'data', '规范化命令', 'canonical command'),
      edge(
        'context',
        'dispatcher',
        'control',
        '运行上下文',
        'invocation context',
      ),
      edge('dispatcher', 'handlers', 'call', '内置命令', 'built-in command'),
      edge('dispatcher', 'code-tui', 'call', 'a3s code', 'a3s code'),
      edge('dispatcher', 'proxies', 'call', '委派命令', 'delegated command'),
      edge('handlers', 'outcome', 'data', '类型化结果', 'typed result'),
      edge('code-tui', 'outcome', 'data', '会话结果', 'session result'),
      edge('proxies', 'outcome', 'data', '子进程状态', 'child status'),
      edge('outcome', 'renderer', 'call', '一次渲染', 'single render pass'),
    ],
  },
  {
    id: 'code',
    name: 'Code',
    category: 'products',
    role: localized(
      '可嵌入的 Agent 核心：AgentSession 负责顺序、生命周期和事件，宿主注入模型、工具、存储与权限。',
      'An embeddable agent core: AgentSession owns ordering, lifecycle, and events while hosts inject models, tools, stores, and permissions.',
    ),
    href: '/docs/code',
    evidence: [
      {
        label: 'Code architecture',
        href: 'https://github.com/A3S-Lab/Code#architecture',
      },
    ],
    groups: [
      group('hosts', '宿主与 SDK', 'Hosts and SDKs', 2, 8, 20, 84),
      group('core', '会话核心', 'Session core', 25, 8, 53, 84),
      group('state', '持久状态', 'Durable state', 81, 8, 17, 84),
    ],
    nodes: [
      node(
        'hosts',
        'Rust / Node / Python / Go',
        'entry',
        11,
        28,
        '语言 SDK 和 a3s code 共用同一 Rust Core。',
        'Language SDKs and a3s code share the same Rust Core.',
      ),
      node(
        'agent-dir',
        'AgentDir / releases',
        'entry',
        11,
        70,
        '从 instructions、ACL、Skills、Tools 和 schedules 装载 Agent。',
        'Loads agents from instructions, ACL, Skills, tools, and schedules.',
      ),
      node(
        'agent',
        'Agent',
        'service',
        33,
        22,
        '组合模型、指令、默认工具和宿主配置。',
        'Combines the model, instructions, default tools, and host configuration.',
      ),
      node(
        'session',
        'AgentSession',
        'process',
        52,
        22,
        '串行化会话操作，生成有序事件并支持恢复。',
        'Serializes session operations, emits ordered events, and supports resume.',
      ),
      node(
        'context',
        'Context + Memory',
        'adapter',
        34,
        62,
        '由 ContextProvider 和 MemoryStore 提供提示上下文。',
        'Supplies prompt context through ContextProvider and MemoryStore.',
      ),
      node(
        'llm',
        'LLM adapters',
        'adapter',
        52,
        62,
        '通过 LlmClient 连接具体模型提供方。',
        'Connects model providers through LlmClient.',
      ),
      node(
        'tools',
        'Tools / Workspace / MCP',
        'runtime',
        69,
        62,
        '在权限、确认和工作区边界内运行工具。',
        'Runs tools within permission, confirmation, and workspace boundaries.',
      ),
      node(
        'records',
        'Events / traces / artifacts',
        'store',
        89,
        30,
        '保存运行事件、trace、artifact、snapshot 和会话记录。',
        'Stores run events, traces, artifacts, snapshots, and session records.',
      ),
      node(
        'graph',
        'StateGraph / Flow bridge',
        'service',
        89,
        72,
        '可选地把会话状态投影到状态图或持久工作流。',
        'Optionally projects session state into a state graph or durable workflow.',
      ),
    ],
    edges: [
      edge('hosts', 'agent', 'call', '构建', 'construct'),
      edge('agent-dir', 'agent', 'data', '文件定义', 'file definition'),
      edge('agent', 'session', 'call', '创建会话', 'create session'),
      edge('session', 'context', 'call', '取上下文', 'load context'),
      edge('session', 'llm', 'call', '模型调用', 'model call'),
      edge('session', 'tools', 'call', '工具调用', 'tool call'),
      edge('session', 'records', 'event', '有序事件', 'ordered events'),
      edge('records', 'graph', 'event', '状态投影', 'state projection'),
      edge(
        'graph',
        'session',
        'control',
        '恢复 / 下一步',
        'resume / next step',
      ),
    ],
  },
  {
    id: 'web',
    name: 'Web',
    category: 'products',
    role: localized(
      '本地浏览器工作台：Work 统一承载任务、文件、Office、代码和 Copilot，Knowledge、Memory 与插件保持独立页面。',
      'A local browser workspace: Work contains tasks, files, Office, code, and Copilot while Knowledge, Memory, and plugins remain separate destinations.',
    ),
    href: 'https://github.com/A3S-Lab/a3s/tree/main/apps/web',
    evidence: [
      {
        label: 'Web product architecture',
        href: 'https://github.com/A3S-Lab/a3s/blob/main/apps/web/docs/PRODUCT_ARCHITECTURE.md',
      },
    ],
    groups: [
      group('shell', '应用外壳', 'Application shell', 2, 6, 96, 24),
      group('work', 'Work', 'Work', 2, 34, 70, 62),
      group('service', '本地服务', 'Local service', 75, 34, 23, 62),
    ],
    nodes: [
      node(
        'boot',
        'Bootstrap + recovery',
        'process',
        9,
        18,
        '恢复本地状态并完成服务启动检查。',
        'Restores local state and checks service startup.',
      ),
      node(
        'shell',
        'AppShell + ActivityBar',
        'entry',
        24,
        18,
        '切换 Work、Knowledge、Memory、插件和 Settings。',
        'Switches Work, Knowledge, Memory, plugins, and Settings.',
      ),
      node(
        'knowledge',
        'Knowledge',
        'service',
        45,
        18,
        '管理知识库、来源包、编译代次和本地搜索。',
        'Manages knowledge bases, source packages, compile generations, and local search.',
      ),
      node(
        'memory',
        'Memory',
        'service',
        63,
        18,
        '显示记忆检索、过滤、图谱、时间线和演化审查。',
        'Shows memory retrieval, filters, graph, timeline, and evolution review.',
      ),
      node(
        'plugins',
        'Verified plugin host',
        'runtime',
        84,
        18,
        '只加载已验证的 A3S Use workbench contribution。',
        'Loads only verified A3S Use workbench contributions.',
      ),
      node(
        'work',
        'WorkProduct',
        'service',
        12,
        51,
        '持有当前任务、场景、工作区和 Assistant 状态。',
        'Owns the current task, scene, workspace, and Assistant state.',
      ),
      node(
        'tasks',
        'TaskLibrary + controller',
        'store',
        31,
        48,
        '维护统一会话目录、草稿、队列、事件和恢复状态。',
        'Maintains the unified session catalog, drafts, queues, events, and recovery state.',
      ),
      node(
        'scene',
        'Scene router',
        'process',
        27,
        76,
        '根据打开的真实文件选择 Files、Office 或 Code 场景。',
        'Selects Files, Office, or Code from the actual opened file.',
      ),
      node(
        'files',
        'Files workspace',
        'entry',
        46,
        62,
        '读写选定根目录下的真实文件。',
        'Reads and writes real files under the selected root.',
      ),
      node(
        'office',
        'Office editor shell',
        'entry',
        46,
        78,
        '打开 DOCX、XLSX、PPTX 和 PDF 编辑器。',
        'Opens DOCX, XLSX, PPTX, and PDF editors.',
      ),
      node(
        'code',
        'Monaco code scene',
        'entry',
        61,
        70,
        '编辑文本和代码并提供诊断与语义导航。',
        'Edits text and code with diagnostics and semantic navigation.',
      ),
      node(
        'copilot',
        'WorkCopilot',
        'entry',
        63,
        48,
        '所有 Work 场景共用一个会话和执行流。',
        'Shares one conversation and execution stream across Work scenes.',
      ),
      node(
        'api',
        'Typed loopback API',
        'adapter',
        86,
        52,
        '提供 session、workspace、Git、Office、knowledge、memory 和 plugin 接口。',
        'Provides session, workspace, Git, Office, knowledge, memory, and plugin APIs.',
      ),
      node(
        'host',
        'A3S local host',
        'runtime',
        86,
        79,
        '保留文件系统、凭据和本机进程等浏览器外能力。',
        'Keeps filesystem, credentials, and local processes outside the browser.',
      ),
    ],
    edges: [
      edge('boot', 'shell', 'control', '启动', 'start'),
      edge('shell', 'work', 'control', '#home', '#home'),
      edge('shell', 'knowledge', 'control', '#knowledge', '#knowledge'),
      edge('shell', 'memory', 'control', '#memory', '#memory'),
      edge('shell', 'plugins', 'control', '#plugin/*', '#plugin/*'),
      edge('work', 'tasks', 'data', '活动会话', 'active session'),
      edge('work', 'scene', 'control', '文件类型', 'file type'),
      edge('scene', 'files', 'control', '目录 / 文件', 'folder / file'),
      edge('scene', 'office', 'control', 'Office / PDF', 'Office / PDF'),
      edge('scene', 'code', 'control', '文本 / 代码', 'text / code'),
      edge(
        'tasks',
        'copilot',
        'event',
        '消息与执行事件',
        'messages and run events',
      ),
      edge('tasks', 'api', 'call', 'session API', 'session API'),
      edge('files', 'api', 'call', 'workspace API', 'workspace API'),
      edge('office', 'api', 'call', 'Office binary API', 'Office binary API'),
      edge(
        'code',
        'api',
        'call',
        '文件 / intelligence API',
        'file / intelligence API',
      ),
      edge('api', 'host', 'call', '本机操作', 'local operation'),
    ],
  },
  {
    id: 'desktop',
    name: 'Desktop',
    category: 'products',
    role: localized(
      '原生桌面宿主：RSX 与 Tailwind 在 Rust 中生成 UiFrame，reducer 驱动 DesktopState，并直接连接 a3s-code-core；AppKit、GTK4 或 WinUI 承载本机控件。',
      'A native desktop host: RSX and Tailwind produce UiFrame data in Rust, a reducer drives DesktopState, and a3s-code-core connects directly while AppKit, GTK4, or WinUI owns the native controls.',
    ),
    href: 'https://github.com/A3S-Lab/a3s/tree/main/apps/desktop',
    evidence: [
      {
        label: 'Desktop runtime architecture',
        href: 'https://github.com/A3S-Lab/a3s/blob/main/apps/desktop/README.md#runtime',
      },
    ],
    groups: [
      group('authoring', '界面与动作', 'UI and actions', 2, 7, 23, 86),
      group('state', '状态与 Agent', 'State and agent', 28, 7, 42, 86),
      group('native', '原生宿主', 'Native hosts', 73, 7, 25, 86),
    ],
    nodes: [
      node(
        'rsx',
        'RSX Command Center',
        'entry',
        9,
        18,
        '命令中心片段用 RSX 编写，并保留 Tailwind class。',
        'Command Center fragments are authored in RSX and retain Tailwind classes.',
      ),
      node(
        'frame',
        'UiFrame / native tree',
        'process',
        18,
        50,
        'Rust 解析 RSX、解析样式并生成可渲染的原生控件树。',
        'Rust parses RSX, resolves styles, and builds a renderable native control tree.',
      ),
      node(
        'actions',
        'Registered native actions',
        'control',
        9,
        82,
        '按钮和选择器发送显式 action，不复用终端命令文本。',
        'Buttons and selectors emit explicit actions instead of terminal command text.',
      ),
      node(
        'reducer',
        'desktop_reduce',
        'process',
        39,
        20,
        '把原生 action 归约为单一 DesktopState 变更。',
        'Reduces native actions into changes on one DesktopState.',
      ),
      node(
        'state',
        'DesktopState',
        'store',
        39,
        50,
        '保存面板、转录、计划、工具、审批、Git 与工作区投影。',
        'Stores panels, transcript, plans, tools, approvals, Git, and workspace projections.',
      ),
      node(
        'tick',
        '50 ms event drain',
        'control',
        39,
        80,
        '非阻塞轮询活动 run，排空事件后请求重绘。',
        'Polls the active run without blocking and requests redraws after draining events.',
      ),
      node(
        'session',
        'a3s-code-core AgentSession',
        'runtime',
        60,
        20,
        '直接运行与 TUI 相同的会话、工具、计划和权限逻辑。',
        'Runs the same session, tool, planning, and permission logic used by the TUI.',
      ),
      node(
        'events',
        'AgentEvent projection',
        'output',
        60,
        52,
        '把文本、reasoning、工具、审批和子 Agent 事件投影到原生面板。',
        'Projects text, reasoning, tool, approval, and subagent events into native panels.',
      ),
      node(
        'workspace',
        '.a3s stores + workspace',
        'store',
        60,
        82,
        '保存桌面会话，并读取 ACL、模型目录、Git 和文件概览。',
        'Stores desktop sessions and reads ACL, model catalog, Git, and file overviews.',
      ),
      node(
        'native-runtime',
        'a3s-gui native runtime',
        'adapter',
        78,
        50,
        '将 UiFrame 降为平台控件，并把宿主事件送回 reducer。',
        'Lowers UiFrame data into platform controls and returns host events to the reducer.',
      ),
      node(
        'appkit',
        'AppKit',
        'runtime',
        92,
        18,
        'macOS 原生窗口与事件循环。',
        'Native macOS windows and event loop.',
      ),
      node(
        'gtk',
        'GTK4',
        'runtime',
        92,
        50,
        'Linux 原生窗口与事件循环。',
        'Native Linux windows and event loop.',
      ),
      node(
        'winui',
        'WinUI',
        'runtime',
        92,
        82,
        'Windows 原生窗口与事件循环。',
        'Native Windows windows and event loop.',
      ),
    ],
    edges: [
      edge('rsx', 'frame', 'data', 'RSX source', 'RSX source'),
      edge('actions', 'reducer', 'event', 'ActionInvocation', 'ActionInvocation'),
      edge('reducer', 'state', 'data', 'state transition', 'state transition', true),
      edge('state', 'frame', 'data', 'render state', 'render state'),
      edge('reducer', 'session', 'call', 'send / stop / confirm', 'send / stop / confirm'),
      edge('session', 'events', 'event', 'AgentEvent stream', 'AgentEvent stream'),
      edge('tick', 'events', 'control', 'poll active run', 'poll active run'),
      edge('events', 'state', 'data', 'native projections', 'native projections'),
      edge('workspace', 'state', 'data', 'sessions + context', 'sessions + context'),
      edge('frame', 'native-runtime', 'data', 'UiFrame', 'UiFrame'),
      edge('native-runtime', 'reducer', 'event', 'host actions', 'host actions'),
      edge('native-runtime', 'appkit', 'control', 'macOS backend', 'macOS backend'),
      edge('native-runtime', 'gtk', 'control', 'Linux backend', 'Linux backend'),
      edge('native-runtime', 'winui', 'control', 'Windows backend', 'Windows backend'),
    ],
  },
  {
    id: 'windhole',
    name: 'Windhole',
    category: 'products',
    role: localized(
      'Bench 的可视化前端：冻结 Task 与机组配置，通过本地 bridge 启动真实评测，再按 Run ID 归档结果。',
      'A visual Bench frontend: freeze a Task and roster, start real evaluations through a loopback bridge, then archive results by Run ID.',
    ),
    href: 'https://github.com/A3S-Lab/a3s/tree/main/apps/windhole',
    evidence: [
      {
        label: 'Windhole architecture',
        href: 'https://github.com/A3S-Lab/a3s/blob/main/apps/windhole/docs/ARCHITECTURE.md',
      },
    ],
    groups: [
      group('presentation', '界面与场景', 'UI and scene', 2, 7, 24, 86),
      group(
        'application',
        '控制器与状态',
        'Controllers and state',
        29,
        7,
        38,
        86,
      ),
      group('execution', '真实评测', 'Real evaluation', 70, 7, 28, 86),
    ],
    nodes: [
      node(
        'catalog',
        'Task catalog',
        'entry',
        11,
        20,
        '从 Bench 读取 Task 列表、详情和 readiness。',
        'Reads Task lists, details, and readiness from Bench.',
      ),
      node(
        'hangar',
        'Hangar roster',
        'entry',
        11,
        48,
        '保存 1–5 个 Candidate、模型、effort 和机体外观。',
        'Stores 1–5 Candidates, models, effort, and aircraft appearance.',
      ),
      node(
        'scene',
        'Three.js battlefield',
        'entry',
        11,
        78,
        '只呈现 Task、机组和真实运行状态，不生成评测数据。',
        'Renders Tasks, roster, and real run state without inventing evaluation data.',
      ),
      node(
        'snapshot',
        'Frozen sortie snapshot',
        'process',
        36,
        22,
        '启动前固化 Task、机组成员和完整 Bench 输入。',
        'Freezes the Task, roster member, and complete Bench input before launch.',
      ),
      node(
        'single',
        'Single-run controller',
        'service',
        52,
        22,
        '跟踪一个 sortie 的 bridge ID 与最终 Run ID。',
        'Tracks one sortie bridge ID and final Run ID.',
      ),
      node(
        'campaign',
        'Campaign controller',
        'service',
        52,
        48,
        '最多并发两个成员，每个成员保留独立 tracking ID。',
        'Runs at most two members concurrently, each with its own tracking ID.',
      ),
      node(
        'engineering',
        'Doctor + lock controller',
        'service',
        52,
        75,
        '执行 Doctor、Task 验证以及 Task/Candidate lock。',
        'Runs Doctor, Task validation, and Task/Candidate locks.',
      ),
      node(
        'state',
        'Valtio + browser stores',
        'store',
        35,
        70,
        '保存 roster、运行恢复记录和 Run ID 到快照的映射。',
        'Stores roster, recovery records, and Run-ID-to-snapshot mappings.',
      ),
      node(
        'bridge',
        'Loopback Bench bridge',
        'adapter',
        74,
        34,
        '校验来源和参数，以无 shell 方式启动 a3s-bench。',
        'Validates origin and arguments, then starts a3s-bench without a shell.',
      ),
      node(
        'bench',
        'a3s-bench process',
        'runtime',
        89,
        34,
        '执行真实 Candidate、Judge 和结果持久化。',
        'Executes the real Candidate, Judge, and result persistence.',
      ),
      node(
        'result',
        'Exact Run result',
        'output',
        82,
        72,
        '只使用返回的确切 Run ID 查询并归属结果。',
        'Queries and attributes results only by the exact returned Run ID.',
      ),
    ],
    edges: [
      edge('catalog', 'snapshot', 'data', '选定 Task', 'selected Task'),
      edge('hangar', 'snapshot', 'data', '活动成员', 'active member'),
      edge('snapshot', 'single', 'call', '单次评测', 'single run'),
      edge('snapshot', 'campaign', 'call', '编队评测', 'campaign'),
      edge('single', 'bridge', 'call', '启动 / 轮询', 'start / poll'),
      edge(
        'campaign',
        'bridge',
        'call',
        '最多两个 worker',
        'up to two workers',
      ),
      edge(
        'engineering',
        'bridge',
        'call',
        'doctor / validate / lock',
        'doctor / validate / lock',
      ),
      edge('bridge', 'bench', 'call', '参数数组', 'argument vector'),
      edge('bench', 'result', 'data', 'Run ID', 'Run ID'),
      edge('result', 'state', 'data', '已验证结果', 'verified result'),
      edge('state', 'scene', 'event', '可视化状态', 'visual state'),
    ],
  },
  {
    id: 'box',
    name: 'Box',
    category: 'products',
    role: localized(
      'OCI 工作负载运行产品：ExecutionManager 在分配资源前解析隔离策略，再进入 libkrun MicroVM 或显式 Sandbox。',
      'An OCI workload product: ExecutionManager resolves isolation policy before allocating either a libkrun MicroVM or an explicit Sandbox.',
    ),
    href: '/docs/box',
    evidence: [
      {
        label: 'Box architecture',
        href: 'https://github.com/A3S-Lab/Box#architecture',
      },
    ],
    groups: [
      group('entry', '入口', 'Entrypoints', 2, 8, 19, 84),
      group('control', '生命周期控制', 'Lifecycle control', 24, 8, 38, 84),
      group(
        'backends',
        '执行与基础设施',
        'Execution and infrastructure',
        65,
        8,
        33,
        84,
      ),
    ],
    nodes: [
      node(
        'entrypoints',
        'CLI / SDK / CRI / shim',
        'entry',
        10,
        26,
        '所有入口提交同一种本地执行请求。',
        'All entrypoints submit the same local execution request.',
      ),
      node(
        'bridge',
        'Machine bridge',
        'adapter',
        10,
        66,
        'Python、TypeScript 和 Go SDK 通过机器协议连接管理器。',
        'Python, TypeScript, and Go SDKs reach the manager through a machine protocol.',
      ),
      node(
        'manager',
        'ExecutionManager',
        'process',
        32,
        25,
        '拥有 create、start、exec、logs、stop、remove 等生命周期。',
        'Owns create, start, exec, logs, stop, remove, and related lifecycle operations.',
      ),
      node(
        'state',
        'Durable state + fencing',
        'store',
        32,
        68,
        '持久化请求、generation、provider identity 和恢复记录。',
        'Persists requests, generations, provider identity, and recovery records.',
      ),
      node(
        'resolver',
        'Capability + policy resolver',
        'security',
        53,
        25,
        '探测宿主能力并拒绝未满足或未声明的隔离要求。',
        'Probes host capabilities and rejects unmet or undeclared isolation requirements.',
      ),
      node(
        'images',
        'OCI image + rootfs',
        'store',
        53,
        70,
        '拉取 manifest/layer，构建 guest rootfs。',
        'Pulls manifests and layers, then builds the guest rootfs.',
      ),
      node(
        'microvm',
        'libkrun MicroVM',
        'runtime',
        72,
        19,
        '在独立 Linux guest kernel 中运行工作负载。',
        'Runs the workload inside a separate Linux guest kernel.',
      ),
      node(
        'sandbox',
        'a3s-oci Sandbox',
        'runtime',
        72,
        49,
        '在明确选择时使用共享宿主内核隔离。',
        'Uses shared-host-kernel isolation only when explicitly selected.',
      ),
      node(
        'guest',
        'Shim / guest init / vsock',
        'adapter',
        89,
        33,
        '负责宿主与 guest 的控制、健康检查和进程通道。',
        'Owns host/guest control, health checks, and process channels.',
      ),
      node(
        'resources',
        'Storage / network / snapshots',
        'service',
        73,
        79,
        '管理卷、网络、快照、warm pool 和临时文件系统。',
        'Manages volumes, networks, snapshots, warm pools, and tmpfs.',
      ),
      node(
        'evidence',
        'Logs / audit / metrics / TEE',
        'output',
        90,
        75,
        '返回日志、资源指标、审计记录和可选证明。',
        'Returns logs, resource metrics, audit records, and optional attestation.',
      ),
    ],
    edges: [
      edge('entrypoints', 'manager', 'call', '本地请求', 'local request'),
      edge('bridge', 'manager', 'call', '机器协议', 'machine protocol'),
      edge(
        'manager',
        'state',
        'data',
        '生命周期记录',
        'lifecycle record',
        true,
      ),
      edge(
        'manager',
        'resolver',
        'call',
        '分配前解析',
        'resolve before allocation',
      ),
      edge('resolver', 'microvm', 'control', 'microvm', 'microvm'),
      edge('resolver', 'sandbox', 'control', 'sandbox', 'sandbox'),
      edge('images', 'microvm', 'data', 'guest rootfs', 'guest rootfs'),
      edge('images', 'sandbox', 'data', 'OCI rootfs', 'OCI rootfs'),
      edge('microvm', 'guest', 'call', 'vsock', 'vsock'),
      edge('sandbox', 'guest', 'call', '本地控制', 'local control'),
      edge(
        'manager',
        'resources',
        'call',
        '资源生命周期',
        'resource lifecycle',
      ),
      edge(
        'guest',
        'evidence',
        'event',
        '进程与 guest 事件',
        'process and guest events',
      ),
      edge('resources', 'evidence', 'event', '资源状态', 'resource state'),
    ],
  },
];
