import {
  architectureEdge as edge,
  architectureGroup as group,
  architectureNode as node,
  localized,
  type ArchitectureProject,
} from './architecture-types';

export const productCapabilityArchitectures: readonly ArchitectureProject[] = [
  {
    id: 'search',
    name: 'Search',
    category: 'products',
    role: localized(
      '同时接入类型化 API Provider、传统网页引擎和 Browser 渲染引擎，再统一并发、失败、去重、排序与全文提取。',
      'Combines typed API providers, conventional web engines, and Browser-backed engines, then handles concurrency, failures, deduplication, ranking, and full-text extraction.',
    ),
    href: '/docs/search',
    evidence: [
      {
        label: 'Search architecture',
        href: 'https://github.com/A3S-Lab/Search#architecture',
      },
    ],
    groups: [
      group('sources', '检索来源', 'Retrieval sources', 2, 7, 29, 86),
      group('orchestration', '检索编排', 'Search orchestration', 34, 7, 38, 86),
      group('results', '聚合与结果', 'Aggregation and results', 75, 7, 23, 86),
    ],
    nodes: [
      node(
        'providers',
        'AnySearch / Tavily / custom',
        'entry',
        12,
        19,
        '返回带 capabilities、usage 和 provider 证据的类型化结果。',
        'Returns typed results with capabilities, usage, and provider evidence.',
      ),
      node(
        'provider-engine',
        'ProviderEngine',
        'adapter',
        23,
        40,
        '把 SearchProvider 输出适配到稳定 Engine 接口。',
        'Adapts SearchProvider output to the stable Engine interface.',
      ),
      node(
        'http-engines',
        'HTTP / RSS engines',
        'entry',
        12,
        58,
        'DuckDuckGo、Brave、Bing、Wikipedia、Sogou、360 等直接抓取。',
        'Fetches DuckDuckGo, Brave, Bing, Wikipedia, Sogou, 360, and similar engines directly.',
      ),
      node(
        'browser-engines',
        'Google / Baidu engines',
        'entry',
        12,
        84,
        '需要渲染的引擎只依赖 PageRenderer。',
        'Rendering-dependent engines use only PageRenderer.',
      ),
      node(
        'renderer',
        'A3S PageRenderer',
        'adapter',
        28,
        78,
        'Browser 负责浏览器发现、进程和标签页限制。',
        'Browser owns discovery, process lifecycle, and tab limits.',
      ),
      node(
        'search',
        'Search orchestrator',
        'process',
        46,
        39,
        '并发运行引擎，保存每个成功或失败 outcome。',
        'Runs engines concurrently and keeps every success or failure outcome.',
      ),
      node(
        'controls',
        'Timeout / circuit / bulkhead',
        'security',
        59,
        18,
        '限制超时、共享熔断、并发和重试预算。',
        'Bounds timeouts, shared circuit state, concurrency, and retry budgets.',
      ),
      node(
        'aggregator',
        'Aggregator + ranker',
        'process',
        62,
        58,
        '规范化 URL、合并重复项并计算最终排序。',
        'Normalizes URLs, merges duplicates, and computes final ranking.',
      ),
      node(
        'fetcher',
        'PageFetcher',
        'adapter',
        59,
        82,
        '用 HTTP 或 Browser 抓取结果页正文。',
        'Fetches result-page content through HTTP or Browser.',
      ),
      node(
        'enrich',
        'Full-text enrichment',
        'process',
        80,
        75,
        '提取正文；失败时保留原始 snippet。',
        'Extracts main text and keeps the original snippet on failure.',
      ),
      node(
        'results',
        'SearchResults + report',
        'output',
        88,
        35,
        '返回排序项、provenance、provider report 和部分失败。',
        'Returns ranked items, provenance, provider reports, and partial failures.',
      ),
    ],
    edges: [
      edge(
        'providers',
        'provider-engine',
        'data',
        '丰富 Provider 输出',
        'rich provider output',
      ),
      edge('provider-engine', 'search', 'call', 'Engine', 'Engine'),
      edge('http-engines', 'search', 'call', 'Engine', 'Engine'),
      edge('browser-engines', 'renderer', 'call', '渲染请求', 'render request'),
      edge('renderer', 'browser-engines', 'data', 'HTML', 'HTML'),
      edge('browser-engines', 'search', 'call', 'Engine', 'Engine'),
      edge('controls', 'search', 'control', '执行限制', 'execution limits'),
      edge(
        'search',
        'aggregator',
        'data',
        'engine outcomes',
        'engine outcomes',
      ),
      edge(
        'aggregator',
        'results',
        'data',
        '去重排序项',
        'deduplicated ranked items',
      ),
      edge(
        'aggregator',
        'enrich',
        'optional',
        '可选全文',
        'optional full text',
      ),
      edge('fetcher', 'enrich', 'call', '页面内容', 'page content'),
      edge(
        'enrich',
        'results',
        'data',
        '正文或原 snippet',
        'full text or original snippet',
      ),
    ],
  },
  {
    id: 'browser',
    name: 'Browser',
    category: 'products',
    role: localized(
      '一个仓库中的两层：可嵌入的 PageRenderer 库，以及隔离进程中的完整自动化 driver、MCP、Skills 和 Dashboard。',
      'Two layers in one repository: an embeddable PageRenderer library and a process-isolated automation driver with MCP, Skills, and Dashboard.',
    ),
    href: 'https://github.com/A3S-Lab/Browser',
    evidence: [
      {
        label: 'Browser repository architecture',
        href: 'https://github.com/A3S-Lab/Browser#readme',
      },
    ],
    groups: [
      group('library', '类型化渲染库', 'Typed rendering library', 2, 7, 57, 86),
      group('driver', '自动化进程', 'Automation process', 62, 7, 36, 86),
    ],
    nodes: [
      node(
        'embedded',
        'Search / embedded host',
        'entry',
        10,
        25,
        '只注入 Arc<dyn PageRenderer>，不启动 MCP 或 daemon。',
        'Injects Arc<dyn PageRenderer> without starting MCP or a daemon.',
      ),
      node(
        'renderer',
        'PageRenderer',
        'adapter',
        27,
        25,
        '接收类型化 RenderRequest 并返回 HTML、截图和页面元数据。',
        'Accepts typed RenderRequest values and returns HTML, screenshots, and page metadata.',
      ),
      node(
        'runtime',
        'BrowserRuntime',
        'service',
        44,
        25,
        '管理 deadline、provider 选择、排队和 bounded cache。',
        'Manages deadlines, provider selection, queueing, and the bounded cache.',
      ),
      node(
        'chrome',
        'Discovered Chrome',
        'runtime',
        27,
        69,
        '复用本机 Chrome-compatible 浏览器并支持完整 CDP 能力。',
        'Uses a local Chrome-compatible browser with full CDP capabilities.',
      ),
      node(
        'lightpanda',
        'Lightpanda',
        'runtime',
        47,
        69,
        '通过 bounded fetch 提供轻量 HTML 渲染。',
        'Provides lightweight HTML rendering through bounded fetch.',
      ),
      node(
        'use',
        'A3S Use CLI / MCP',
        'entry',
        69,
        20,
        '完整自动化请求从 Use 的标准 CLI 或 MCP surface 进入。',
        'Full automation requests enter through the standard Use CLI or MCP surface.',
      ),
      node(
        'boundary',
        'Sibling process boundary',
        'security',
        69,
        48,
        '把高级自动化状态与可嵌入库隔开。',
        'Separates advanced automation state from the embeddable library.',
      ),
      node(
        'driver',
        'browser-driver',
        'process',
        84,
        36,
        '拥有 CLI 兼容、31+ MCP tools、页面交互和进程生命周期。',
        'Owns CLI compatibility, 31+ MCP tools, page interaction, and process lifecycle.',
      ),
      node(
        'sessions',
        'Persistent sessions',
        'store',
        84,
        68,
        '保存 tab、snapshot 和 element reference，支持跨 CLI 调用继续。',
        'Keeps tabs, snapshots, and element references across CLI invocations.',
      ),
      node(
        'assets',
        'Skills + Dashboard',
        'output',
        69,
        78,
        '随 driver 发布可审查 Skills 和静态 Dashboard。',
        'Ships reviewable Skills and a static Dashboard with the driver.',
      ),
    ],
    edges: [
      edge('embedded', 'renderer', 'call', 'RenderRequest', 'RenderRequest'),
      edge('renderer', 'runtime', 'call', '渲染生命周期', 'render lifecycle'),
      edge(
        'runtime',
        'chrome',
        'control',
        'Chrome provider',
        'Chrome provider',
      ),
      edge(
        'runtime',
        'lightpanda',
        'control',
        'Lightpanda provider',
        'Lightpanda provider',
      ),
      edge('use', 'boundary', 'call', 'CLI / MCP stdio', 'CLI / MCP stdio'),
      edge('boundary', 'driver', 'call', '子进程', 'child process'),
      edge(
        'driver',
        'sessions',
        'data',
        'tab / snapshot state',
        'tab / snapshot state',
        true,
      ),
      edge('driver', 'chrome', 'call', 'CDP automation', 'CDP automation'),
      edge(
        'assets',
        'driver',
        'data',
        'Skill 与 UI 资源',
        'Skill and UI assets',
      ),
    ],
  },
  {
    id: 'ocr',
    name: 'OCR',
    category: 'products',
    role: localized(
      'OcrClient 先读取并固定源文件证据，再调用本地 PP-OCRv6 或明确配置的远程 Provider；Provider 不能改写来源。',
      'OcrClient reads and fixes source evidence before calling local PP-OCRv6 or an explicitly configured remote provider; providers cannot rewrite provenance.',
    ),
    href: 'https://github.com/A3S-Lab/OCR',
    evidence: [
      {
        label: 'OCR provider contract',
        href: 'https://github.com/A3S-Lab/OCR#the-contract-ocr-plus-provenance',
      },
    ],
    groups: [
      group('client', '输入与证据', 'Input and evidence', 2, 7, 30, 86),
      group(
        'providers',
        '识别 Provider',
        'Recognition providers',
        35,
        7,
        45,
        86,
      ),
      group('result', '结果', 'Result', 83, 7, 15, 86),
    ],
    nodes: [
      node(
        'surfaces',
        'Use / CLI / MCP / Rust',
        'entry',
        10,
        20,
        '四种入口调用同一个 OcrClient。',
        'Four surfaces call the same OcrClient.',
      ),
      node(
        'image',
        'Bounded local image',
        'entry',
        10,
        67,
        '只接受大小受限且签名受支持的本地图片。',
        'Accepts only bounded local images with supported signatures.',
      ),
      node(
        'client',
        'OcrClient',
        'process',
        25,
        39,
        '规范化路径、读取一次并校验 provider 输出。',
        'Canonicalizes the path, reads once, and validates provider output.',
      ),
      node(
        'source',
        'SourceEvidence',
        'store',
        25,
        76,
        '固定 media type、byte size 和 SHA-256。',
        'Fixes media type, byte size, and SHA-256.',
      ),
      node(
        'provider',
        'OcrProvider',
        'adapter',
        42,
        28,
        '通过对象安全接口选择具体识别实现。',
        'Selects a recognition implementation through an object-safe interface.',
      ),
      node(
        'detect',
        'Decode + DB detection',
        'process',
        53,
        55,
        '本地流水线解码图片并检测文本区域。',
        'The local pipeline decodes the image and detects text regions.',
      ),
      node(
        'crop',
        'Order + perspective crop',
        'process',
        66,
        55,
        '排序文本块并按透视变换裁剪。',
        'Orders text regions and applies perspective crops.',
      ),
      node(
        'recognize',
        'Batch recognition + CTC',
        'runtime',
        75,
        29,
        'ONNX Runtime 执行 PP-OCRv6 批量识别和 CTC 解码。',
        'ONNX Runtime performs PP-OCRv6 batch recognition and CTC decoding.',
      ),
      node(
        'unlimited',
        'Unlimited-OCR endpoint',
        'runtime',
        57,
        20,
        '可选 Provider 调用 operator-managed vLLM，并明确标记 off-device。',
        'The optional provider calls operator-managed vLLM and declares off-device transfer.',
      ),
      node(
        'result',
        'OcrResult',
        'output',
        90,
        40,
        '组合文本、模型、可选 confidence、polygon 和 warnings。',
        'Combines text, model identity, optional confidence, polygons, and warnings.',
      ),
      node(
        'evidence',
        'Result provenance',
        'output',
        90,
        75,
        '把识别输出绑定回不可改写的 SourceEvidence。',
        'Binds recognition output back to immutable SourceEvidence.',
      ),
    ],
    edges: [
      edge('surfaces', 'client', 'call', 'OcrRequest', 'OcrRequest'),
      edge('image', 'client', 'data', '文件 bytes', 'file bytes'),
      edge('client', 'source', 'data', '规范化来源', 'canonical source'),
      edge('client', 'provider', 'call', 'OcrInput', 'OcrInput'),
      edge('provider', 'detect', 'control', 'PP-OCRv6', 'PP-OCRv6'),
      edge('detect', 'crop', 'data', '检测区域', 'detected regions'),
      edge('crop', 'recognize', 'data', '批量 crops', 'batched crops'),
      edge(
        'provider',
        'unlimited',
        'optional',
        'Unlimited-OCR',
        'Unlimited-OCR',
      ),
      edge(
        'recognize',
        'result',
        'data',
        '本地识别输出',
        'local recognition output',
      ),
      edge('unlimited', 'result', 'data', 'Markdown 输出', 'Markdown output'),
      edge(
        'source',
        'evidence',
        'data',
        'path / type / size / hash',
        'path / type / size / hash',
      ),
      edge('result', 'evidence', 'data', '识别内容', 'recognized content'),
    ],
  },
  {
    id: 'parser',
    name: 'Parser',
    category: 'products',
    role: localized(
      '文档智能编排层：先绑定并校验一个来源，再让受限的 A3S Code 会话生成 ParsePlan；Office 与 OCR 只返回证据，宿主负责预算、对账、checkpoint 和规范文档。',
      'A document-intelligence orchestration layer: bind and admit one source, then let a restricted A3S Code session produce a ParsePlan. Office and OCR return evidence while the host owns budgets, reconciliation, checkpoints, and the canonical document.',
    ),
    href: 'https://github.com/A3S-Lab/Parser',
    evidence: [
      {
        label: 'Parser architecture',
        href: 'https://github.com/A3S-Lab/Parser/blob/main/docs/architecture.md',
      },
    ],
    groups: [
      group('source', '来源准入', 'Source admission', 2, 7, 20, 86),
      group('control', 'Code 控制面', 'Code control plane', 26, 7, 36, 86),
      group('evidence', '证据与输出', 'Evidence and output', 66, 7, 32, 86),
    ],
    nodes: [
      node(
        'source',
        'Read-only source',
        'entry',
        9,
        18,
        '调用方授权边界内的一份只读文档。',
        'One read-only document inside the caller-authorized boundary.',
      ),
      node(
        'admission',
        'Admit + hash + sniff',
        'security',
        9,
        50,
        '流式限制大小、计算 SHA-256、识别格式并拒绝路径或压缩歧义。',
        'Streams under size limits, computes SHA-256, detects format, and rejects path or archive ambiguity.',
      ),
      node(
        'inventory',
        'Admitted UnitLocator set',
        'store',
        9,
        82,
        '冻结允许访问的页、幻灯片、工作表、图片或文档单元。',
        'Freezes the allowed page, slide, worksheet, image, or document units.',
      ),
      node(
        'session',
        'Restricted AgentSession',
        'runtime',
        34,
        18,
        'A3S Code 提供唯一的 Agent loop、权限、HITL、预算和审计。',
        'A3S Code provides the only agent loop, permissions, HITL, budgets, and audit.',
      ),
      node(
        'tools',
        'Source-bound parser tools',
        'adapter',
        34,
        50,
        '模型只能提交 admitted locator、opaque ID、cursor 和类型化选项。',
        'The model can submit only admitted locators, opaque IDs, cursors, and typed options.',
      ),
      node(
        'plan',
        'ParsePlan + host validation',
        'security',
        34,
        82,
        'Schema 只验证形状；宿主再检查来源、工具、依赖、阶段和预算权限。',
        'Schema validates shape; the host then checks source, tools, dependencies, stages, and budget authority.',
      ),
      node(
        'workflow',
        'Host-controlled workflow',
        'process',
        53,
        50,
        '按 admission、structure、visual、OCR、reconcile、validate、publish 分阶段执行。',
        'Executes admission, structure, visual, OCR, reconciliation, validation, and publication phases.',
      ),
      node(
        'manifest',
        'ParseManifest CAS',
        'store',
        53,
        82,
        '按自然单元保存可恢复进度，并在 Code session 保存前提交 revision。',
        'Stores resumable progress per natural unit and commits its revision before the Code session is saved.',
      ),
      node(
        'office',
        'A3S Office adapter',
        'service',
        71,
        18,
        '提供 OOXML 结构、稳定路径、分页和受限 raster。',
        'Provides OOXML structure, stable paths, pagination, and bounded raster output.',
      ),
      node(
        'ocr',
        'A3S OCR adapter',
        'service',
        71,
        50,
        '只识别本次 run 生成的已知 raster artifact，并声明传输策略。',
        'Recognizes only known raster artifacts from this run and declares transfer policy.',
      ),
      node(
        'evidence-store',
        'Host evidence store',
        'store',
        71,
        82,
        '把完整结构、raster、OCR 和 provenance 留在宿主侧内容寻址存储中。',
        'Keeps full structure, raster, OCR, and provenance in host-side content-addressed storage.',
      ),
      node(
        'browser',
        'Browser visual bridge',
        'adapter',
        91,
        18,
        '仅由 Office adapter 用于固定来源的分页、PDFium 或 richer rendering。',
        'Used only inside the Office adapter for fixed-source pagination, PDFium, or richer rendering.',
      ),
      node(
        'reconcile',
        'Reconcile + geometry checks',
        'process',
        90,
        50,
        '合并 Office 与 OCR 证据，同时保留冲突、canvas identity 和固定坐标。',
        'Merges Office and OCR evidence while preserving conflicts, canvas identity, and fixed coordinates.',
      ),
      node(
        'output',
        'ParsedDocument + projections',
        'output',
        90,
        82,
        '先发布通过校验的规范图，再派生 Markdown、HTML、JSONL 和 chunks。',
        'Publishes the validated canonical graph first, then derives Markdown, HTML, JSONL, and chunks.',
      ),
    ],
    edges: [
      edge('source', 'admission', 'data', 'source bytes', 'source bytes'),
      edge('admission', 'inventory', 'data', 'hash + units', 'hash + units'),
      edge('inventory', 'session', 'data', 'bound authority', 'bound authority'),
      edge('tools', 'session', 'call', 'dynamic tools', 'dynamic tools', true),
      edge('session', 'plan', 'data', 'schema-constrained plan', 'schema-constrained plan'),
      edge('plan', 'workflow', 'control', 'validated steps', 'validated steps'),
      edge('workflow', 'tools', 'call', 'governed batches', 'governed batches'),
      edge('tools', 'office', 'call', 'structure / render', 'structure / render'),
      edge('tools', 'ocr', 'call', 'opaque raster ID', 'opaque raster ID'),
      edge('office', 'browser', 'optional', 'fixed-source visual bridge', 'fixed-source visual bridge'),
      edge('office', 'evidence-store', 'data', 'structure + raster', 'structure + raster'),
      edge('browser', 'evidence-store', 'data', 'layout-faithful raster', 'layout-faithful raster'),
      edge('ocr', 'evidence-store', 'data', 'regions + confidence', 'regions + confidence'),
      edge('evidence-store', 'reconcile', 'data', 'evidence chains', 'evidence chains'),
      edge('reconcile', 'manifest', 'data', 'validated unit state', 'validated unit state'),
      edge('workflow', 'manifest', 'control', 'phase checkpoint', 'phase checkpoint'),
      edge('manifest', 'session', 'data', 'commit before save', 'commit before save'),
      edge('manifest', 'output', 'data', 'canonical publication', 'canonical publication'),
    ],
  },
  {
    id: 'use',
    name: 'Use',
    category: 'products',
    role: localized(
      '能力入口与包生命周期：Browser、OCR 是内置路由，Box 是组件路由，Office、Science 等通过可验证扩展包接入。',
      'Capability routing and package lifecycle: Browser and OCR are built in, Box is component-backed, and Office, Science, and others arrive as verified extension packages.',
    ),
    href: 'https://github.com/A3S-Lab/Use',
    evidence: [
      {
        label: 'Use architecture',
        href: 'https://github.com/A3S-Lab/Use/blob/main/docs/architecture.md',
      },
    ],
    groups: [
      group('host', 'Use host', 'Use host', 2, 7, 30, 86),
      group('routes', '路由与包', 'Routes and packages', 35, 7, 43, 86),
      group('projection', '宿主投影', 'Host projection', 81, 7, 17, 86),
    ],
    nodes: [
      node(
        'umbrella',
        'a3s umbrella CLI',
        'entry',
        10,
        22,
        '负责组件发现、安装权限和可执行文件所有权。',
        'Owns component discovery, installation authority, and executable ownership.',
      ),
      node(
        'host',
        'a3s-use host',
        'process',
        24,
        44,
        '解析 use domain、route 和生命周期命令。',
        'Resolves use domains, routes, and lifecycle commands.',
      ),
      node(
        'browser',
        'Built-in Browser',
        'service',
        42,
        17,
        '连接 typed renderer、driver、持久 session 和 MCP。',
        'Connects the typed renderer, driver, persistent sessions, and MCP.',
      ),
      node(
        'ocr',
        'Built-in OCR',
        'service',
        42,
        42,
        '注入本地 PP-OCRv6，并提供 CLI、MCP 与 Skill。',
        'Injects local PP-OCRv6 and exposes CLI, MCP, and Skill surfaces.',
      ),
      node(
        'box',
        'Component-backed Box',
        'adapter',
        42,
        68,
        '只执行 umbrella CLI 提供的 canonical Box executable。',
        'Runs only the canonical Box executable supplied by the umbrella CLI.',
      ),
      node(
        'receipts',
        'Receipts + package store',
        'store',
        59,
        82,
        '保存来源、digest、owned files、activation 和 generation。',
        'Stores source, digest, owned files, activation, and generation.',
      ),
      node(
        'registry',
        'Hot-plug registry',
        'process',
        59,
        35,
        '从 receipts 原子发布不可变 route snapshot。',
        'Atomically publishes an immutable route snapshot from receipts.',
      ),
      node(
        'leases',
        'Route leases',
        'security',
        71,
        54,
        '运行中的 CLI/MCP 保留接受时的 package generation。',
        'Running CLI/MCP calls retain the package generation they accepted.',
      ),
      node(
        'packages',
        'Office / Science / …',
        'runtime',
        59,
        16,
        '外部仓库以 CLI、MCP、Skill 或 workbench package 运行。',
        'External repositories run as CLI, MCP, Skill, or workbench packages.',
      ),
      node(
        'snapshot',
        'Capability snapshot / watch',
        'output',
        88,
        35,
        '统一投影内置和扩展 route、MCP、Skill 与 content hash。',
        'Projects built-in and extension routes, MCP, Skills, and content hashes together.',
      ),
      node(
        'consumers',
        'A3S Code / Web',
        'entry',
        89,
        72,
        'Code 热更新能力；Web 只加载已验证 workbench contribution。',
        'Code hot-reloads capabilities; Web loads only verified workbench contributions.',
      ),
    ],
    edges: [
      edge('umbrella', 'host', 'call', 'a3s use', 'a3s use'),
      edge('host', 'browser', 'call', 'browser route', 'browser route'),
      edge('host', 'ocr', 'call', 'ocr route', 'ocr route'),
      edge('host', 'box', 'call', 'box route', 'box route'),
      edge('host', 'registry', 'call', 'extension route', 'extension route'),
      edge(
        'packages',
        'registry',
        'data',
        'manifest surfaces',
        'manifest surfaces',
      ),
      edge(
        'receipts',
        'registry',
        'data',
        'authoritative state',
        'authoritative state',
      ),
      edge('registry', 'leases', 'control', 'admit / drain', 'admit / drain'),
      edge(
        'leases',
        'packages',
        'call',
        'native child process',
        'native child process',
      ),
      edge(
        'browser',
        'snapshot',
        'data',
        'built-in readiness',
        'built-in readiness',
      ),
      edge('ocr', 'snapshot', 'data', 'provider + Skill', 'provider + Skill'),
      edge('registry', 'snapshot', 'data', 'generation', 'generation'),
      edge(
        'snapshot',
        'consumers',
        'event',
        'snapshot / long poll',
        'snapshot / long poll',
      ),
    ],
  },
];
