import {
  architectureEdge as edge,
  architectureGroup as group,
  architectureNode as node,
  localized,
  type ArchitectureProject,
} from './architecture-types';

export const coordinationArchitectureProjects: readonly ArchitectureProject[] =
  [
    {
      id: 'runtime',
      name: 'Runtime',
      category: 'runtime',
      role: localized(
        '通用 Task / Service 生命周期契约：Managed Runtime 负责校验、幂等、generation 和持久状态，具体执行留给 Provider Driver。',
        'A general Task and Service lifecycle contract: Managed Runtime owns validation, idempotency, generations, and durable state while Provider Drivers own execution.',
      ),
      href: 'https://github.com/A3S-Lab/Runtime',
      evidence: [
        {
          label: 'Runtime model and architecture',
          href: 'https://github.com/A3S-Lab/Runtime#runtime-model',
        },
      ],
      groups: [
        group('contract', '调用方与契约', 'Caller and contract', 2, 8, 31, 84),
        group('managed', '受管生命周期', 'Managed lifecycle', 36, 8, 37, 84),
        group('provider', 'Provider', 'Provider', 76, 8, 22, 84),
      ],
      nodes: [
        node(
          'caller',
          'Caller policy / workflow',
          'entry',
          10,
          30,
          '上层产品决定 artifact、资源、网络、隔离和健康策略。',
          'The product decides artifact, resources, network, isolation, and health policy.',
        ),
        node(
          'client',
          'RuntimeClient',
          'adapter',
          25,
          30,
          '提供 capabilities、apply、inspect、stop、remove、logs 和 exec。',
          'Exposes capabilities, apply, inspect, stop, remove, logs, and exec.',
        ),
        node(
          'protocol',
          'Protocol + capability checks',
          'security',
          18,
          70,
          '在保留状态或调用 Provider 前校验 wire schema 与能力。',
          'Validates wire schemas and capabilities before reserving state or calling a provider.',
        ),
        node(
          'managed',
          'Managed Runtime',
          'process',
          45,
          31,
          '执行状态迁移、请求重放、终态不可变和 deadline 规则。',
          'Enforces state transitions, request replay, terminal immutability, and deadlines.',
        ),
        node(
          'state',
          'State + operation receipts',
          'store',
          45,
          72,
          '在跨进程锁下保存 unit、generation、request 和 tombstone。',
          'Stores units, generations, requests, and tombstones under cross-process locks.',
        ),
        node(
          'registry',
          'Provider registry',
          'service',
          64,
          29,
          '按显式 Provider ID 和 capability 注册 Driver。',
          'Registers Drivers by explicit Provider ID and capability.',
        ),
        node(
          'driver',
          'RuntimeDriver',
          'adapter',
          82,
          28,
          '把通用操作映射到具体运行时。',
          'Maps general operations onto a concrete runtime.',
        ),
        node(
          'external',
          'External runtime',
          'runtime',
          90,
          67,
          'Docker、Box、远程 Runtime 或其他实现实际创建资源。',
          'Docker, Box, a remote runtime, or another implementation creates resources.',
        ),
        node(
          'observation',
          'Observation / logs / outputs',
          'output',
          67,
          75,
          '返回健康、usage、日志、artifact、attestation 和结构化失败。',
          'Returns health, usage, logs, artifacts, attestation, and structured failures.',
        ),
      ],
      edges: [
        edge('caller', 'client', 'call', 'RuntimeUnitSpec', 'RuntimeUnitSpec'),
        edge(
          'client',
          'protocol',
          'call',
          'wire validation',
          'wire validation',
        ),
        edge(
          'protocol',
          'managed',
          'control',
          '已验证请求',
          'validated request',
        ),
        edge(
          'managed',
          'state',
          'data',
          'generation / receipt',
          'generation / receipt',
          true,
        ),
        edge('managed', 'registry', 'call', 'Provider ID', 'Provider ID'),
        edge('registry', 'driver', 'call', '选择 Driver', 'select Driver'),
        edge(
          'driver',
          'external',
          'call',
          'provider operation',
          'provider operation',
        ),
        edge(
          'external',
          'observation',
          'data',
          'provider state',
          'provider state',
        ),
        edge(
          'observation',
          'managed',
          'data',
          'RuntimeObservation',
          'RuntimeObservation',
        ),
        edge('managed', 'client', 'data', '稳定结果', 'stable result'),
      ],
    },
    {
      id: 'oci-runtime',
      name: 'OCI Runtime',
      category: 'runtime',
      role: localized(
        '实验性 OCI 生命周期基础：平台无关控制面保存 config、journal 和 fencing，LinuxExecutor 分别运行在宿主内核或 utility VM guest 中。',
        'An experimental OCI lifecycle foundation: a platform-neutral control plane stores config, journals, and fencing while LinuxExecutor runs either on the host kernel or inside a utility-VM guest.',
      ),
      href: 'https://github.com/A3S-Lab/OCI-Runtime',
      evidence: [
        {
          label: 'OCI Runtime architecture',
          href: 'https://github.com/A3S-Lab/OCI-Runtime#architecture',
        },
      ],
      groups: [
        group('consumer', 'SDK 与入口', 'SDK and entrypoints', 2, 7, 17, 86),
        group(
          'control',
          '平台无关控制面',
          'Platform-neutral control plane',
          22,
          7,
          43,
          86,
        ),
        group('execution', '隔离执行', 'Isolation execution', 68, 7, 30, 86),
      ],
      nodes: [
        node(
          'consumers',
          'CLI / SDK / Box (planned)',
          'entry',
          9,
          25,
          '通过进程内 API 或 bounded local IPC 提交 OCI 操作。',
          'Submits OCI operations through in-process APIs or bounded local IPC.',
        ),
        node(
          'ipc',
          'Private Unix IPC',
          'adapter',
          9,
          69,
          'Linux 的同 UID SDK service 提供本机进程边界。',
          'The same-UID Linux SDK service provides a local process boundary.',
        ),
        node(
          'service',
          'OciRuntimeService',
          'service',
          28,
          31,
          '统一 create、start、kill、delete、exec、wait 和 update。',
          'Unifies create, start, kill, delete, exec, wait, and update.',
        ),
        node(
          'validation',
          'OCI validation',
          'security',
          43,
          19,
          '校验 OCI 1.3 schema、语义、hook 和平台能力。',
          'Validates OCI 1.3 schemas, semantics, hooks, and platform capabilities.',
        ),
        node(
          'lifecycle',
          'Durable lifecycle',
          'process',
          51,
          49,
          '保存 generation、operation replay、reconciliation 和 quarantine。',
          'Stores generations, operation replay, reconciliation, and quarantine.',
        ),
        node(
          'state',
          'Exact config + journal',
          'store',
          41,
          78,
          '记录完整 config digest、状态、操作 intent 和终态结果。',
          'Records exact config digests, states, operation intent, and terminal results.',
        ),
        node(
          'selection',
          'RuntimeDriver selection',
          'control',
          62,
          25,
          '显式选择 shared-host-kernel 或 utility-VM 路径，不降级。',
          'Explicitly selects shared-host-kernel or utility-VM paths without fallback.',
        ),
        node(
          'native',
          'NativeLinuxDriver',
          'runtime',
          76,
          17,
          '在 Linux 宿主上直接调用共享 LinuxExecutor。',
          'Calls the shared LinuxExecutor directly on a Linux host.',
        ),
        node(
          'utility',
          'Utility VM driver',
          'runtime',
          75,
          53,
          '规划中的 driver 把同一执行器放入 libkrun guest。',
          'The planned driver places the same executor inside a libkrun guest.',
        ),
        node(
          'shim',
          'libkrun shim + hypervisor',
          'adapter',
          88,
          60,
          '隔离加载 checksum-pinned libkrun，并连接 HVF、WHPX 或 KVM。',
          'Loads checksum-pinned libkrun in isolation and connects HVF, WHPX, or KVM.',
        ),
        node(
          'agent',
          'Guest agent + bridge',
          'adapter',
          84,
          83,
          '用认证 host/guest 协议把 OCI 请求送进静态 Linux agent。',
          'Uses an authenticated host/guest protocol to reach the static Linux agent.',
        ),
        node(
          'executor',
          'LinuxExecutor',
          'process',
          91,
          26,
          '实现 namespace、pivot_root、mount、hook、PID 1、signal 和 cleanup。',
          'Implements namespaces, pivot_root, mounts, hooks, PID 1, signals, and cleanup.',
        ),
        node(
          'events',
          'State / stats / events',
          'output',
          61,
          82,
          '返回生命周期、资源统计、I/O、exit 和清理证据。',
          'Returns lifecycle, resource statistics, I/O, exits, and cleanup evidence.',
        ),
      ],
      edges: [
        edge(
          'consumers',
          'service',
          'call',
          'in-process SDK',
          'in-process SDK',
        ),
        edge('consumers', 'ipc', 'call', 'local client', 'local client'),
        edge('ipc', 'service', 'call', 'bounded protocol', 'bounded protocol'),
        edge('service', 'validation', 'call', 'OCI config', 'OCI config'),
        edge(
          'validation',
          'lifecycle',
          'control',
          'validated operation',
          'validated operation',
        ),
        edge('lifecycle', 'state', 'data', 'journal', 'journal', true),
        edge(
          'lifecycle',
          'selection',
          'call',
          'isolation requirement',
          'isolation requirement',
        ),
        edge(
          'selection',
          'native',
          'control',
          'shared host kernel',
          'shared host kernel',
        ),
        edge(
          'selection',
          'utility',
          'optional',
          'utility VM（尚未接入）',
          'utility VM (not yet wired)',
        ),
        edge('native', 'executor', 'call', 'direct', 'direct'),
        edge(
          'utility',
          'shim',
          'optional',
          'native runtime bundle',
          'native runtime bundle',
        ),
        edge('shim', 'agent', 'call', 'vsock / pipe', 'vsock / pipe'),
        edge('agent', 'executor', 'call', 'guest execution', 'guest execution'),
        edge(
          'executor',
          'events',
          'event',
          'lifecycle + stats',
          'lifecycle + stats',
        ),
        edge(
          'events',
          'lifecycle',
          'data',
          'terminal / recovery facts',
          'terminal / recovery facts',
        ),
      ],
    },
    {
      id: 'flow',
      name: 'Flow',
      category: 'runtime',
      role: localized(
        '事件溯源工作流：每次从完整历史重放，运行时只返回一个 command；step 执行副作用，wait 和 hook 持久挂起。',
        'An event-sourced workflow engine: replay from full history each time and accept one runtime command; steps perform side effects while waits and hooks suspend durably.',
      ),
      href: 'https://github.com/A3S-Lab/Flow',
      evidence: [
        {
          label: 'Flow architecture',
          href: 'https://github.com/A3S-Lab/Flow/blob/main/docs/ARCHITECTURE.md',
        },
      ],
      groups: [
        group('definition', '工作流定义', 'Workflow definition', 2, 7, 22, 86),
        group('engine', '重放引擎', 'Replay engine', 27, 7, 43, 86),
        group(
          'durability',
          '持久化与调度',
          'Durability and dispatch',
          73,
          7,
          25,
          86,
        ),
      ],
      nodes: [
        node(
          'sdk',
          'Rust SDK / workflow',
          'entry',
          10,
          22,
          '工作流根据 input 和已提交历史决定下一条 command。',
          'The workflow chooses its next command from input and committed history.',
        ),
        node(
          'runtime',
          'FlowRuntime / NativeTs',
          'adapter',
          16,
          69,
          '运行 Rust workflow，或通过编译后的 native TypeScript 进程协议运行。',
          'Runs Rust workflows or compiled native TypeScript through a process protocol.',
        ),
        node(
          'engine',
          'FlowEngine replay loop',
          'process',
          37,
          27,
          '加载历史、调用 runtime、验证确定性，再提交 command 对应事件。',
          'Loads history, calls the runtime, checks determinism, and commits command events.',
        ),
        node(
          'steps',
          'Steps + retries',
          'runtime',
          55,
          18,
          '执行副作用，记录 step_completed、retry_after 或 step_failed。',
          'Executes side effects and records completion, retry, or failure.',
        ),
        node(
          'waits',
          'Waits + timers',
          'control',
          55,
          46,
          '记录 wait_created，直到 deadline 或显式 resume。',
          'Records wait_created until a deadline or explicit resume.',
        ),
        node(
          'hooks',
          'Hooks + callbacks',
          'control',
          55,
          74,
          '按唯一 token 挂起，接收 hook_received 或 hook_disposed。',
          'Suspends on a unique token until hook_received or hook_disposed.',
        ),
        node(
          'store',
          'Append-only event store',
          'store',
          79,
          20,
          'Memory、JSONL、SQLite 或 PostgreSQL 保存有序 envelope。',
          'Memory, JSONL, SQLite, or PostgreSQL stores ordered envelopes.',
        ),
        node(
          'projection',
          'Run projection',
          'output',
          79,
          46,
          '从事件计算 snapshot、open suspensions、next wakeup 和 active hooks。',
          'Projects snapshots, open suspensions, next wakeups, and active hooks from events.',
        ),
        node(
          'scheduler',
          'FlowScheduler',
          'service',
          79,
          73,
          '扫描到期 wait / retry，并生成粗粒度恢复任务。',
          'Scans due waits and retries and creates coarse resume tasks.',
        ),
        node(
          'queue',
          'Task queue + leases',
          'store',
          92,
          71,
          'Memory、文件或 PostgreSQL 队列保存 pending、inflight 和 dead-letter。',
          'Memory, file, or PostgreSQL queues store pending, inflight, and dead-letter tasks.',
        ),
        node(
          'worker',
          'FlowWorker',
          'runtime',
          92,
          42,
          '租赁任务、调用 FlowEngine，成功后再 ack。',
          'Leases a task, calls FlowEngine, and acknowledges only after success.',
        ),
        node(
          'observer',
          'Committed-event observers',
          'output',
          93,
          14,
          '在提交后输出 audit、metrics 或 A3S event bridge。',
          'Emits audit, metrics, or A3S event bridge records after commit.',
        ),
      ],
      edges: [
        edge(
          'sdk',
          'runtime',
          'data',
          'workflow implementation',
          'workflow implementation',
        ),
        edge('runtime', 'engine', 'call', 'one command', 'one command', true),
        edge(
          'engine',
          'steps',
          'control',
          'schedule_step(s)',
          'schedule_step(s)',
        ),
        edge('engine', 'waits', 'control', 'wait_until', 'wait_until'),
        edge('engine', 'hooks', 'control', 'create_hook', 'create_hook'),
        edge(
          'engine',
          'store',
          'event',
          'expected-sequence append',
          'expected-sequence append',
          true,
        ),
        edge('store', 'projection', 'data', 'event history', 'event history'),
        edge(
          'store',
          'observer',
          'event',
          'committed envelope',
          'committed envelope',
        ),
        edge(
          'projection',
          'scheduler',
          'data',
          'due suspensions',
          'due suspensions',
        ),
        edge('scheduler', 'queue', 'call', 'resume tasks', 'resume tasks'),
        edge('queue', 'worker', 'control', 'lease', 'lease'),
        edge('worker', 'engine', 'call', 'drive run', 'drive run'),
      ],
    },
    {
      id: 'event',
      name: 'Event',
      category: 'runtime',
      role: localized(
        '统一 publish、subscribe 和 history 的事件总线；Memory、NATS JetStream 或自定义 Provider 共享同一 envelope 与订阅接口。',
        'An event bus with one publish, subscribe, and history API; Memory, NATS JetStream, and custom providers share the same envelope and subscription interface.',
      ),
      href: 'https://github.com/A3S-Lab/Event',
      evidence: [
        {
          label: 'Event architecture',
          href: 'https://github.com/A3S-Lab/Event#architecture',
        },
      ],
      groups: [
        group('api', '总线 API', 'Bus API', 2, 8, 32, 84),
        group('providers', 'Provider', 'Providers', 37, 8, 35, 84),
        group(
          'delivery',
          '投递与运维',
          'Delivery and operations',
          75,
          8,
          23,
          84,
        ),
      ],
      nodes: [
        node(
          'publishers',
          'Publishers / consumers',
          'entry',
          10,
          25,
          '使用 dot-separated subject 发布或订阅事件。',
          'Publishes or subscribes with dot-separated subjects.',
        ),
        node(
          'schema',
          'SchemaRegistry',
          'security',
          18,
          70,
          '校验 event type 和兼容性。',
          'Validates event types and compatibility.',
        ),
        node(
          'bus',
          'EventBus',
          'service',
          28,
          35,
          '管理 publish、subscription、history、info 和 metrics。',
          'Manages publish, subscriptions, history, info, and metrics.',
        ),
        node(
          'provider',
          'dyn EventProvider',
          'adapter',
          45,
          35,
          '定义 publish、subscribe、durable subscribe、history 和 info。',
          'Defines publish, subscribe, durable subscribe, history, and info.',
        ),
        node(
          'memory',
          'Memory provider',
          'store',
          60,
          18,
          '使用 Tokio broadcast 提供进程内事件。',
          'Uses Tokio broadcast for in-process events.',
        ),
        node(
          'nats',
          'NATS JetStream',
          'store',
          60,
          47,
          '提供持久 stream、consumer 和 at-least-once delivery。',
          'Provides persistent streams, consumers, and at-least-once delivery.',
        ),
        node(
          'custom',
          'Custom provider',
          'adapter',
          60,
          76,
          '实现同一 trait 接入其他后端。',
          'Implements the same trait for another backend.',
        ),
        node(
          'subscription',
          'Subscription + ack/nak',
          'process',
          81,
          25,
          '把 Provider 事件投影为统一 async stream 和手动确认。',
          'Projects provider events into one async stream with manual acknowledgements.',
        ),
        node(
          'dlq',
          'DLQ + subscription state',
          'store',
          90,
          48,
          '保存失败投递和 durable consumer state。',
          'Stores failed deliveries and durable consumer state.',
        ),
        node(
          'routing',
          'Broker / filters / sinks',
          'service',
          81,
          76,
          '可选地按 filter 把事件送到 topic、进程内或日志 sink。',
          'Optionally routes filtered events to topic, in-process, or log sinks.',
        ),
        node(
          'ops',
          'History / info / metrics',
          'output',
          94,
          12,
          '报告历史、消息量、consumer 和延迟指标。',
          'Reports history, message counts, consumers, and latency metrics.',
        ),
      ],
      edges: [
        edge(
          'publishers',
          'bus',
          'call',
          'publish / subscribe',
          'publish / subscribe',
        ),
        edge(
          'schema',
          'bus',
          'control',
          'schema admission',
          'schema admission',
        ),
        edge(
          'bus',
          'provider',
          'call',
          'provider-neutral API',
          'provider-neutral API',
        ),
        edge('provider', 'memory', 'control', 'in-process', 'in-process'),
        edge('provider', 'nats', 'control', 'distributed', 'distributed'),
        edge('provider', 'custom', 'control', 'custom', 'custom'),
        edge(
          'memory',
          'subscription',
          'event',
          'ReceivedEvent',
          'ReceivedEvent',
        ),
        edge('nats', 'subscription', 'event', 'ReceivedEvent', 'ReceivedEvent'),
        edge(
          'custom',
          'subscription',
          'event',
          'ReceivedEvent',
          'ReceivedEvent',
        ),
        edge(
          'subscription',
          'dlq',
          'data',
          'failed delivery',
          'failed delivery',
        ),
        edge(
          'subscription',
          'routing',
          'event',
          'matched event',
          'matched event',
        ),
        edge('provider', 'ops', 'data', 'history + status', 'history + status'),
      ],
    },
  ];
