import { architectureNode as node, localized, type ArchitectureProject } from './architecture-types';
import { getProjectPrimaryHref } from '../project-links';

export const runtimeArchitectureProjects: readonly ArchitectureProject[] = [
  {
    id: 'runtime',
    name: 'Runtime',
    category: 'runtime',
    role: localized('统一运行短任务和长期服务，底层 Provider 可以替换。', 'Runs short tasks and long-lived services through replaceable providers.'),
    href: getProjectPrimaryHref('runtime'),
    nodes: [
      node('caller', 'Caller Policy', 'surface', '宿主提交显式 Task、Service、资源与截止时间。', 'Hosts submit explicit Tasks, Services, resources, and deadlines.'),
      node('contract', 'Runtime Contract', 'core', '统一 create、start、inspect、exec、logs、cancel 与 remove 语义。', 'Unifies create, start, inspect, exec, logs, cancel, and remove semantics.'),
      node('managed', 'Managed Lifecycle', 'contract', '验证状态迁移、generation、幂等与终态不变性。', 'Validates state transitions, generations, idempotency, and terminal immutability.'),
      node('driver', 'Provider Driver', 'runtime', '把契约映射到显式注册且能力匹配的 Provider。', 'Maps the contract to an explicitly registered, capability-matched provider.'),
      node('external', 'External Runtime', 'evidence', '返回身份绑定的状态、日志、健康与清理证据。', 'Returns identity-bound state, logs, health, and cleanup evidence.'),
    ],
  },
  {
    id: 'oci-runtime',
    name: 'OCI Runtime',
    category: 'runtime',
    role: localized('在 macOS、Linux 和 Windows 上管理 OCI 工作负载与隔离。', 'Manages OCI workloads and isolation on macOS, Linux, and Windows.'),
    href: getProjectPrimaryHref('oci-runtime'),
    nodes: [
      node('consumers', 'Consumers & SDK', 'surface', 'CLI、RuntimeClient 与未来 shim 使用同一平台中立入口。', 'CLI, RuntimeClient, and future shims use one platform-neutral entrypoint.'),
      node('service', 'OciRuntimeService', 'core', '拥有 OCI schema、语义验证与宿主控制面。', 'Owns OCI schema, semantic validation, and the host control plane.'),
      node('lifecycle', 'Durable Lifecycle', 'contract', '持久化 exact config、operation journal、generation 与 fencing。', 'Persists exact config, operation journals, generations, and fencing.'),
      node('selection', 'RuntimeDriver', 'runtime', '显式选择共享宿主内核或 Utility VM 隔离。', 'Explicitly selects shared-host-kernel or Utility VM isolation.'),
      node('executor', 'Linux / VM Executor', 'evidence', '执行 namespace、mount、hook、PID 1、exec、signal 与清理。', 'Executes namespaces, mounts, hooks, PID 1, exec, signal, and cleanup.'),
    ],
  },
  {
    id: 'flow',
    name: 'Flow',
    category: 'runtime',
    role: localized('让长时间运行的工作流可以等待、重试、恢复和重放。', 'Lets long-running workflows wait, retry, resume, and replay safely.'),
    href: getProjectPrimaryHref('flow'),
    nodes: [
      node('spec', 'WorkflowSpec', 'surface', '用稳定名称、版本与输入启动一个持久 run。', 'Starts a durable run from a stable name, version, and input.'),
      node('engine', 'FlowEngine', 'core', '一次应用一个 RuntimeCommand，并保持宿主控制面。', 'Applies one RuntimeCommand at a time while retaining host control.'),
      node('history', 'Event Store', 'contract', '以有序 append-only 事件保存每次有意义的变更。', 'Stores every meaningful mutation as ordered append-only events.'),
      node('replay', 'Replay + Projection', 'runtime', '重放历史、拒绝定义漂移并构建 snapshot。', 'Replays history, rejects definition drift, and builds snapshots.'),
      node('workers', 'Worker / Scheduler', 'evidence', '恢复步骤、等待、hook 与延迟重试直到终态。', 'Resumes steps, waits, hooks, and delayed retries until terminal state.'),
    ],
  },
  {
    id: 'event',
    name: 'Event',
    category: 'runtime',
    role: localized('发布、订阅和保存 A3S 事件，底层存储可以替换。', 'Publishes, subscribes to, and stores A3S events with replaceable backends.'),
    href: getProjectPrimaryHref('event'),
    nodes: [
      node('publisher', 'Publisher', 'surface', '发布带 dot-separated subject 与 schema 身份的事件。', 'Publishes events with dot-separated subjects and schema identity.'),
      node('bus', 'EventBus', 'core', '提供 publish、subscribe、history 与订阅管理 API。', 'Provides publish, subscribe, history, and subscription management APIs.'),
      node('provider', 'EventProvider', 'contract', '用对象安全 trait 隔离传输与存储后端。', 'Isolates transport and storage backends behind an object-safe trait.'),
      node('backends', 'Memory / NATS / Custom', 'runtime', '选择广播内存、JetStream 或自定义 Provider。', 'Selects broadcast memory, JetStream, or a custom provider.'),
      node('delivery', 'Delivery & History', 'evidence', '输出带 ack、sequence、schema、DLQ 与指标的事件流。', 'Emits streams with ack, sequence, schema, DLQ, and metrics.'),
    ],
  },
  {
    id: 'lane',
    name: 'Lane',
    category: 'runtime',
    role: localized('按并发限制和优先级调度异步任务，失败后可以重试。', 'Schedules async work by concurrency limit and priority, with retries after failure.'),
    href: getProjectPrimaryHref('lane'),
    nodes: [
      node('submit', 'Typed Command', 'surface', '接收可执行 Command 或由宿主保留所有权的类型化值。', 'Accepts executable Commands or host-owned typed values.'),
      node('manager', 'QueueManager', 'core', '维护 lane 注册、提交、启动、drain 与 shutdown。', 'Owns lane registration, submission, startup, drain, and shutdown.'),
      node('scheduler', 'Priority Scheduler', 'contract', '按稳定 FIFO 和较低数值优先级选择下一项。', 'Selects the next item by stable FIFO and lower numeric priority.'),
      node('controls', 'Concurrency + Retry', 'runtime', '应用并发、超时、rate limit、backoff、boost 与 DLQ。', 'Applies concurrency, timeout, rate limit, backoff, boost, and DLQ controls.'),
      node('settlement', 'Result & Events', 'evidence', '结算 oneshot 结果并输出压力、空闲和遥测事件。', 'Settles one-shot results and emits pressure, idle, and telemetry events.'),
    ],
  },
  {
    id: 'memory',
    name: 'Memory',
    category: 'runtime',
    role: localized('保存、搜索、去重并清理 Agent 记忆。', 'Stores, searches, deduplicates, and prunes agent memory.'),
    href: getProjectPrimaryHref('memory'),
    nodes: [
      node('item', 'MemoryItem', 'surface', '记录内容、类型、重要度、标签、时间与关系 metadata。', 'Carries content, type, importance, tags, time, and relationship metadata.'),
      node('store', 'MemoryStore', 'core', '定义 store、retrieve、search、delete 与维护契约。', 'Defines store, retrieve, search, delete, and maintenance contracts.'),
      node('hygiene', 'Dedupe + Relevance', 'contract', '合并规范化精确重复，并组合匹配、重要度和衰减。', 'Merges normalized exact duplicates and combines match, importance, and decay.'),
      node('backends', 'Memory / File / SQLite', 'runtime', '在临时、原子文件或可选 SQLite 存储间替换。', 'Switches between ephemeral, atomic-file, and optional SQLite stores.'),
      node('results', 'Search + Pruning', 'evidence', '返回排序结果，并保护 pinned、常用与关系型记忆。', 'Returns ranked results while protecting pinned, recalled, and relational memories.'),
    ],
  },
  {
    id: 'orm',
    name: 'ORM',
    category: 'runtime',
    role: localized('生成参数化 SQL，并异步访问 SQLite 和 PostgreSQL。', 'Builds parameterized SQL and runs it asynchronously on SQLite and PostgreSQL.'),
    href: getProjectPrimaryHref('orm'),
    nodes: [
      node('schema', 'Schema + Expressions', 'surface', '从类型化 schema、列、值与表达式构造查询。', 'Builds queries from typed schemas, columns, values, and expressions.'),
      node('ast', 'Immutable Query AST', 'core', '用不可变结构保留查询语义与参数边界。', 'Preserves query semantics and parameter boundaries in immutable structures.'),
      node('compiler', 'Dialect Compiler', 'contract', '将同一 AST 编译为明确方言和绑定参数。', 'Compiles one AST into an explicit dialect and bound parameters.'),
      node('query', 'CompiledQuery', 'runtime', '产生可缓存、可检查、无客户端依赖的 SQL 计划。', 'Produces a cacheable, inspectable SQL plan without client dependencies.'),
      node('driver', 'Executor / Driver', 'evidence', '通过异步 SQLite 或 PostgreSQL 驱动执行、事务与迁移。', 'Executes queries, transactions, and migrations through async SQLite or PostgreSQL drivers.'),
    ],
  },
  {
    id: 'common',
    name: 'Common',
    category: 'runtime',
    role: localized('A3S crates 共用的隐私、工具、路径和通信类型。', 'Shared privacy, tool, path, and transport types for A3S crates.'),
    href: getProjectPrimaryHref('common'),
    nodes: [
      node('consumers', 'A3S Crates', 'surface', '由需要一致 wire 与安全语义的独立 crate 直接依赖。', 'Used directly by independent crates that need consistent wire and safety semantics.'),
      node('privacy', 'Privacy Types', 'core', '统一敏感值、可见性与脱敏语义。', 'Unifies sensitive values, visibility, and redaction semantics.'),
      node('tools', 'Tool + Path Types', 'contract', '规范工具描述、工作区路径与边界验证。', 'Standardizes tool descriptions, workspace paths, and boundary validation.'),
      node('transport', 'Framed Transport', 'runtime', '提供稳定 framing 与跨进程协议原语。', 'Provides stable framing and cross-process protocol primitives.'),
      node('wire', 'Shared Wire Model', 'evidence', '减少各项目重复且不一致的协议包装。', 'Reduces duplicated and inconsistent protocol wrappers across projects.'),
    ],
  },
];
