import {
  architectureEdge as edge,
  architectureGroup as group,
  architectureNode as node,
  localized,
  type ArchitectureProject,
} from './architecture-types';

export const dataArchitectureProjects: readonly ArchitectureProject[] = [
  {
    id: 'lane',
    name: 'Lane',
    category: 'runtime',
    role: localized(
      '按命名 lane 调度异步 Command：优先级决定谁先入场，并发、限流、重试和 DLQ 决定执行方式；另提供不自动执行的类型化 PriorityQueue。',
      'Schedules async Commands in named lanes: priority controls admission while concurrency, rate limits, retries, and DLQ control execution; a separate typed PriorityQueue never executes values itself.',
    ),
    href: 'https://github.com/A3S-Lab/Lane',
    evidence: [
      {
        label: 'Lane model',
        href: 'https://github.com/A3S-Lab/Lane#lane-model',
      },
    ],
    groups: [
      group('entry', '两种队列入口', 'Two queue entrypoints', 2, 7, 24, 86),
      group('scheduler', 'Command 调度', 'Command scheduling', 29, 7, 43, 86),
      group(
        'reliability',
        '可靠性与观测',
        'Reliability and observation',
        75,
        7,
        23,
        86,
      ),
    ],
    nodes: [
      node(
        'typed-values',
        'Host-owned values',
        'entry',
        10,
        20,
        '终端或 Web event loop 保留类型化值的执行所有权。',
        'A terminal or web event loop retains ownership of typed values and execution.',
      ),
      node(
        'priority-queue',
        'PriorityQueue<T>',
        'store',
        19,
        40,
        '按 priority + FIFO 排序；claim 失败可恢复原插入位置。',
        'Orders by priority and FIFO and can restore a failed claim to its original slot.',
      ),
      node(
        'submit',
        'Command submit()',
        'entry',
        10,
        76,
        '提交可执行 Command 并取得 oneshot result receiver。',
        'Submits an executable Command and receives a oneshot result receiver.',
      ),
      node(
        'manager',
        'QueueManager',
        'service',
        35,
        42,
        '管理 lane、启动、关闭、drain 和订阅。',
        'Owns lanes, startup, shutdown, draining, and subscriptions.',
      ),
      node(
        'lanes',
        'Named lane queues',
        'store',
        50,
        18,
        'system、control、query、session、skill、prompt 或自定义 lane。',
        'Holds system, control, query, session, skill, prompt, or custom lanes.',
      ),
      node(
        'policy',
        'Priority / limits / rate',
        'control',
        63,
        40,
        '应用优先级、min/max concurrency、timeout、rate limit 和 boost。',
        'Applies priority, min/max concurrency, timeouts, rate limits, and boosts.',
      ),
      node(
        'scheduler',
        'Lane scheduler',
        'process',
        50,
        66,
        '从可运行 lane 中选择下一条 Command，已运行任务不会被抢占。',
        'Selects the next Command from runnable lanes; running work is not preempted.',
      ),
      node(
        'execute',
        'Command::execute',
        'runtime',
        67,
        76,
        '在 Tokio task 中运行并返回 JSON Value 或错误。',
        'Runs in a Tokio task and returns a JSON Value or an error.',
      ),
      node(
        'retry',
        'Retry + backoff',
        'process',
        82,
        18,
        '按 fixed / exponential policy 重新排队失败任务。',
        'Requeues failed work under fixed or exponential retry policy.',
      ),
      node(
        'dlq',
        'Dead-letter queue',
        'store',
        91,
        40,
        '保存达到重试上限的命令和错误。',
        'Stores commands and errors after retries are exhausted.',
      ),
      node(
        'storage',
        'Local / Redis backend',
        'store',
        82,
        69,
        '可选地持久化 pending command、job 和 dead letter。',
        'Optionally persists pending commands, jobs, and dead letters.',
      ),
      node(
        'events',
        'Events / metrics / alerts',
        'output',
        92,
        80,
        '发布 submit、start、retry、pressure、complete、timeout 等状态。',
        'Publishes submit, start, retry, pressure, completion, timeout, and related state.',
      ),
    ],
    edges: [
      edge(
        'typed-values',
        'priority-queue',
        'data',
        'typed value',
        'typed value',
      ),
      edge(
        'priority-queue',
        'typed-values',
        'control',
        'claim / restore',
        'claim / restore',
      ),
      edge('submit', 'manager', 'call', 'Command', 'Command'),
      edge('manager', 'lanes', 'data', 'lane ID', 'lane ID'),
      edge(
        'lanes',
        'policy',
        'control',
        'pending candidates',
        'pending candidates',
      ),
      edge('policy', 'scheduler', 'control', 'admission', 'admission'),
      edge('scheduler', 'execute', 'call', 'Tokio task', 'Tokio task'),
      edge('execute', 'retry', 'event', 'retryable error', 'retryable error'),
      edge('retry', 'lanes', 'control', 'requeue', 'requeue'),
      edge('retry', 'dlq', 'data', 'exhausted', 'exhausted'),
      edge('manager', 'storage', 'data', 'queue state', 'queue state', true),
      edge('manager', 'events', 'event', 'queue lifecycle', 'queue lifecycle'),
      edge(
        'execute',
        'events',
        'event',
        'result / latency',
        'result / latency',
      ),
    ],
  },
  {
    id: 'memory',
    name: 'Memory',
    category: 'runtime',
    role: localized(
      '只负责 MemoryStore 存储层：保存 MemoryItem、合并完全重复项、计算词法相关性并按策略修剪；会话记忆与 prompt 注入留在 Code。',
      'Owns only the MemoryStore layer: persist MemoryItems, merge exact duplicates, score lexical relevance, and prune by policy; session memory and prompt injection stay in Code.',
    ),
    href: 'https://github.com/A3S-Lab/Memory',
    evidence: [
      {
        label: 'Memory design',
        href: 'https://github.com/A3S-Lab/Memory#design',
      },
    ],
    groups: [
      group('api', '稳定存储接口', 'Stable store interface', 2, 7, 31, 86),
      group(
        'hygiene',
        '写入与检索规则',
        'Write and retrieval rules',
        36,
        7,
        34,
        86,
      ),
      group('backends', '存储实现', 'Store implementations', 73, 7, 25, 86),
    ],
    nodes: [
      node(
        'caller',
        'Agent / application',
        'entry',
        10,
        26,
        '直接依赖 MemoryStore；Code 的三层记忆不在本 crate。',
        'Depends directly on MemoryStore; Code’s three-tier memory is outside this crate.',
      ),
      node(
        'store',
        'MemoryStore trait',
        'adapter',
        25,
        42,
        '定义 store、retrieve、search、delete、list 和 prune。',
        'Defines store, retrieve, search, delete, list, and prune.',
      ),
      node(
        'item',
        'MemoryItem + MemoryType',
        'store',
        18,
        75,
        '保存 content、episodic/semantic/procedural/working 类型、tags 和 metadata。',
        'Stores content, episodic/semantic/procedural/working type, tags, and metadata.',
      ),
      node(
        'dedup',
        'Exact dedup + merge',
        'process',
        44,
        22,
        '规范化大小写和空白后合并完全重复项，并保留首个 ID。',
        'Merges exact duplicates after case/whitespace normalization and retains the first ID.',
      ),
      node(
        'score',
        'Lexical relevance scorer',
        'process',
        57,
        47,
        '组合短语、term、tag、类型、importance 和 recency。',
        'Combines phrase, term, tag, type, importance, and recency matches.',
      ),
      node(
        'prune',
        'Protected prune policy',
        'control',
        45,
        76,
        '删除旧且低重要度记录，但保护 pinned、常用和关系记录。',
        'Removes old low-importance items while protecting pinned, frequently used, and related records.',
      ),
      node(
        'memory-backend',
        'InMemoryStore',
        'store',
        82,
        18,
        '供测试和短生命周期进程使用。',
        'Used for tests and short-lived processes.',
      ),
      node(
        'file-backend',
        'FileMemoryStore',
        'store',
        89,
        46,
        '原子写 index.json 和每条 item JSON，并可重建索引。',
        'Atomically writes index.json and per-item JSON and can rebuild the index.',
      ),
      node(
        'sqlite-backend',
        'SQLite + FTS5 / vector',
        'store',
        82,
        77,
        '可选提供全文检索和 sqlite-vec 相似度搜索。',
        'Optionally provides full-text and sqlite-vec similarity search.',
      ),
      node(
        'results',
        'Ranked MemoryItems',
        'output',
        67,
        81,
        '返回具体匹配项，不在存储层推断语义等价。',
        'Returns concrete matches without inferring semantic equivalence in the store layer.',
      ),
    ],
    edges: [
      edge('caller', 'store', 'call', 'store / search', 'store / search'),
      edge('item', 'store', 'data', 'MemoryItem', 'MemoryItem'),
      edge('store', 'dedup', 'call', '写入', 'write'),
      edge('store', 'score', 'call', '查询', 'query'),
      edge('store', 'prune', 'call', 'prune', 'prune'),
      edge(
        'dedup',
        'memory-backend',
        'data',
        'canonical item',
        'canonical item',
      ),
      edge('dedup', 'file-backend', 'data', 'canonical item', 'canonical item'),
      edge(
        'dedup',
        'sqlite-backend',
        'data',
        'canonical item',
        'canonical item',
      ),
      edge('score', 'memory-backend', 'call', 'scan', 'scan'),
      edge('score', 'file-backend', 'call', 'index', 'index'),
      edge('score', 'sqlite-backend', 'call', 'FTS / vector', 'FTS / vector'),
      edge('score', 'results', 'data', 'ranked matches', 'ranked matches'),
    ],
  },
  {
    id: 'orm',
    name: 'ORM',
    category: 'runtime',
    role: localized(
      '类型化 SQL 编译与执行：builder 生成不可变 AST，compiler 只输出 SQL 和绑定参数，SQLite/PostgreSQL driver 负责连接、事务与解码。',
      'Typed SQL compilation and execution: builders create immutable ASTs, compilers emit only SQL and bound parameters, and SQLite/PostgreSQL drivers own connections, transactions, and decoding.',
    ),
    href: 'https://github.com/A3S-Lab/ORM',
    evidence: [
      {
        label: 'ORM architecture',
        href: 'https://github.com/A3S-Lab/ORM/blob/main/docs/architecture.md',
      },
    ],
    groups: [
      group('build', '查询构建', 'Query construction', 2, 7, 34, 86),
      group('compile', '编译', 'Compilation', 39, 7, 28, 86),
      group('execute', '执行与迁移', 'Execution and migrations', 70, 7, 28, 86),
    ],
    nodes: [
      node(
        'schema',
        'Schema + expressions',
        'entry',
        10,
        20,
        '用类型化 table、column、function、window 和 predicate 构建查询。',
        'Builds queries from typed tables, columns, functions, windows, and predicates.',
      ),
      node(
        'builders',
        'Immutable query builders',
        'process',
        25,
        20,
        '按 SELECT、INSERT、UPDATE、DELETE、CTE 和 raw query 生成语句。',
        'Builds SELECT, INSERT, UPDATE, DELETE, CTE, and raw statements.',
      ),
      node(
        'ast',
        'Internal query AST',
        'store',
        18,
        62,
        '保留 bound values、alias、joins、locks、subquery 和 set operation。',
        'Retains bound values, aliases, joins, locks, subqueries, and set operations.',
      ),
      node(
        'validation',
        'Statement validation',
        'security',
        43,
        23,
        '在输出 SQL 前检查语句结构、列顺序、lock target 和 dialect support。',
        'Checks statement structure, column ordering, lock targets, and dialect support before SQL output.',
      ),
      node(
        'compiler',
        'Dialect compiler',
        'process',
        55,
        49,
        '按 dialect 引用 identifier，并连续编号所有参数。',
        'Quotes identifiers by dialect and continuously numbers all parameters.',
      ),
      node(
        'compiled',
        'CompiledQuery',
        'output',
        43,
        78,
        '只包含 SQL 文本和独立绑定值，不打开连接。',
        'Contains only SQL text and separate bound values and opens no connection.',
      ),
      node(
        'executor',
        'Executor / Database',
        'adapter',
        75,
        35,
        '提供 execute、fetch、transaction 和 typed decode 入口。',
        'Provides execute, fetch, transaction, and typed decode entrypoints.',
      ),
      node(
        'sqlite',
        'SQLite driver',
        'runtime',
        88,
        17,
        '共享 connection gate、BEGIN IMMEDIATE、WAL 和取消安全 rollback。',
        'Uses a shared connection gate, BEGIN IMMEDIATE, WAL, and cancellation-safe rollback.',
      ),
      node(
        'postgres',
        'PostgreSQL driver',
        'runtime',
        88,
        45,
        '使用 pool、prepared cache、TLS rotation、advisory locks 和 typed arrays。',
        'Uses pooling, prepared caches, TLS rotation, advisory locks, and typed arrays.',
      ),
      node(
        'decode',
        'Typed row decoder',
        'process',
        88,
        74,
        '把 driver-neutral Value 转回查询推导的 Rust 输出类型。',
        'Converts driver-neutral Values into the Rust output type inferred by the query.',
      ),
      node(
        'migrations',
        'Migration runner',
        'service',
        73,
        78,
        '排序 migration、校验 checksum，并在后端锁内原子提交历史。',
        'Sorts migrations, validates checksums, and atomically commits history under a backend lock.',
      ),
    ],
    edges: [
      edge('schema', 'builders', 'call', 'typed API', 'typed API'),
      edge('builders', 'ast', 'data', 'immutable nodes', 'immutable nodes'),
      edge('ast', 'validation', 'data', 'statement AST', 'statement AST'),
      edge(
        'validation',
        'compiler',
        'control',
        'validated AST',
        'validated AST',
      ),
      edge('compiler', 'compiled', 'data', 'SQL + params', 'SQL + params'),
      edge(
        'compiled',
        'executor',
        'call',
        'parameterized query',
        'parameterized query',
      ),
      edge('executor', 'sqlite', 'control', 'sqlite', 'sqlite'),
      edge('executor', 'postgres', 'control', 'postgres', 'postgres'),
      edge('sqlite', 'decode', 'data', 'rows', 'rows'),
      edge('postgres', 'decode', 'data', 'rows', 'rows'),
      edge(
        'migrations',
        'sqlite',
        'call',
        'locked transaction',
        'locked transaction',
      ),
      edge(
        'migrations',
        'postgres',
        'call',
        'advisory-locked transaction',
        'advisory-locked transaction',
      ),
    ],
  },
  {
    id: 'common',
    name: 'Common',
    category: 'runtime',
    role: localized(
      '三个彼此独立的共享模块：隐私分类与脱敏、工具定义与安全路径、以及 framed Unix/TEE 传输。',
      'Three independent shared modules: privacy classification and redaction, tool definitions and safe paths, and framed Unix/TEE transport.',
    ),
    href: '/docs/common',
    evidence: [
      {
        label: 'Common source modules',
        href: 'https://github.com/A3S-Lab/a3s/tree/main/crates/common/src',
      },
    ],
    groups: [
      group('privacy', 'privacy', 'privacy', 26, 7, 22, 86),
      group('tools', 'tools', 'tools', 51, 7, 22, 86),
      group('transport', 'transport', 'transport', 76, 7, 22, 86),
    ],
    nodes: [
      node(
        'consumers',
        'A3S crates',
        'entry',
        9,
        50,
        '需要一致隐私、工具或传输类型的 crate 直接依赖 Common。',
        'Crates that need consistent privacy, tool, or transport types depend on Common directly.',
      ),
      node(
        'classification',
        'PII classification',
        'security',
        36,
        23,
        '按类型、正则和关键字识别敏感内容。',
        'Identifies sensitive content by type, regular expression, and keywords.',
      ),
      node(
        'redaction',
        'Redaction',
        'process',
        36,
        70,
        '在保留结构的同时替换或隐藏敏感值。',
        'Replaces or hides sensitive values while preserving structure.',
      ),
      node(
        'tool-defs',
        'Tool definitions',
        'store',
        61,
        23,
        '提供共享工具 schema、调用和结果类型。',
        'Provides shared tool schemas, calls, and result types.',
      ),
      node(
        'paths',
        'Safe path resolution',
        'security',
        61,
        70,
        '解析工作区路径并阻止边界逃逸。',
        'Resolves workspace paths and prevents boundary escape.',
      ),
      node(
        'frames',
        'Frame + codec',
        'adapter',
        83,
        20,
        '定义有界 frame、编码和异步读写。',
        'Defines bounded frames, codecs, and async reads and writes.',
      ),
      node(
        'unix',
        'Unix transport',
        'runtime',
        82,
        50,
        '在 Unix socket 上承载 framed message。',
        'Carries framed messages over Unix sockets.',
      ),
      node(
        'tee',
        'TEE transport protocol',
        'security',
        83,
        79,
        '定义可信执行环境相关的 wire message。',
        'Defines wire messages for trusted-execution-environment transport.',
      ),
    ],
    edges: [
      edge('consumers', 'classification', 'call', 'privacy API', 'privacy API'),
      edge(
        'classification',
        'redaction',
        'data',
        'classified spans',
        'classified spans',
      ),
      edge('consumers', 'tool-defs', 'call', 'tool API', 'tool API'),
      edge('tool-defs', 'paths', 'call', 'workspace path', 'workspace path'),
      edge('consumers', 'frames', 'call', 'transport API', 'transport API'),
      edge('frames', 'unix', 'data', 'framed bytes', 'framed bytes'),
      edge('frames', 'tee', 'data', 'TEE frames', 'TEE frames'),
    ],
  },
];
